

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "14", "15", "16"],
		"CDFG" : "hls_color_space_convert_top",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "s_axis_video", "Type" : "Axis", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_hls_color_space_convert_template_3_8_3_8_s_fu_176", "Port" : "s_axis_video", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "m_axis_video", "Type" : "Axis", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_hls_color_space_convert_template_3_8_3_8_s_fu_176", "Port" : "m_axis_video", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "coeffs_0_0", "Type" : "None", "Direction" : "I"},
			{"Name" : "coeffs_0_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "coeffs_0_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "coeffs_1_0", "Type" : "None", "Direction" : "I"},
			{"Name" : "coeffs_1_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "coeffs_1_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "coeffs_2_0", "Type" : "None", "Direction" : "I"},
			{"Name" : "coeffs_2_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "coeffs_2_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "offsets_0", "Type" : "None", "Direction" : "I"},
			{"Name" : "offsets_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "offsets_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "width", "Type" : "None", "Direction" : "I"},
			{"Name" : "height", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_hls_color_space_convert_template_3_8_3_8_s_fu_176", "Parent" : "0", "Child" : ["2", "13"],
		"CDFG" : "hls_color_space_convert_template_3_8_3_8_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "s_axis_video", "Type" : "Axis", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "2", "SubInstance" : "grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134", "Port" : "s_axis_video", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "m_axis_video", "Type" : "Axis", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "2", "SubInstance" : "grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134", "Port" : "m_axis_video", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "coeffs_0_0_0_0_0_0_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "coeffs_0_1_0_0_0_0_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "coeffs_0_2_0_0_0_0_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "coeffs_1_0_0_0_0_0_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "coeffs_1_1_0_0_0_0_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "coeffs_1_2_0_0_0_0_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "coeffs_2_0_0_0_0_0_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "coeffs_2_1_0_0_0_0_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "coeffs_2_2_0_0_0_0_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "offsets_0_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "offsets_1_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "offsets_2_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "width", "Type" : "None", "Direction" : "I"},
			{"Name" : "height", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "2", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_hls_color_space_convert_template_3_8_3_8_s_fu_176.grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134", "Parent" : "1", "Child" : ["3", "4", "5", "6", "7", "8", "9", "10", "11", "12"],
		"CDFG" : "hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "total_pixels", "Type" : "None", "Direction" : "I"},
			{"Name" : "s_axis_video", "Type" : "Axis", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "s_axis_video_TDATA_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln29", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln29_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln29_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln29_9", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln29_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln29_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln29_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln29_10", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln29_6", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln29_7", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln29_8", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln19", "Type" : "None", "Direction" : "I"},
			{"Name" : "add_ln43", "Type" : "None", "Direction" : "I"},
			{"Name" : "m_axis_video", "Type" : "Axis", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "m_axis_video_TDATA_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_19_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter6", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter6", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "3", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_hls_color_space_convert_template_3_8_3_8_s_fu_176.grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134.mul_16s_8ns_24_1_1_U1", "Parent" : "2"},
	{"ID" : "4", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_hls_color_space_convert_template_3_8_3_8_s_fu_176.grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134.mul_16s_8ns_24_1_1_U2", "Parent" : "2"},
	{"ID" : "5", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_hls_color_space_convert_template_3_8_3_8_s_fu_176.grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134.mul_16s_8ns_24_1_1_U3", "Parent" : "2"},
	{"ID" : "6", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_hls_color_space_convert_template_3_8_3_8_s_fu_176.grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134.mac_muladd_16s_8ns_24s_25_4_1_U4", "Parent" : "2"},
	{"ID" : "7", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_hls_color_space_convert_template_3_8_3_8_s_fu_176.grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134.mac_muladd_16s_8ns_24s_25_4_1_U5", "Parent" : "2"},
	{"ID" : "8", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_hls_color_space_convert_template_3_8_3_8_s_fu_176.grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134.mac_muladd_16s_8ns_24s_25_4_1_U6", "Parent" : "2"},
	{"ID" : "9", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_hls_color_space_convert_template_3_8_3_8_s_fu_176.grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134.mac_muladd_16s_8ns_25s_26_4_1_U7", "Parent" : "2"},
	{"ID" : "10", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_hls_color_space_convert_template_3_8_3_8_s_fu_176.grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134.mac_muladd_16s_8ns_25s_26_4_1_U8", "Parent" : "2"},
	{"ID" : "11", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_hls_color_space_convert_template_3_8_3_8_s_fu_176.grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134.mac_muladd_16s_8ns_25s_26_4_1_U9", "Parent" : "2"},
	{"ID" : "12", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_hls_color_space_convert_template_3_8_3_8_s_fu_176.grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134.flow_control_loop_pipe_sequential_init_U", "Parent" : "2"},
	{"ID" : "13", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_hls_color_space_convert_template_3_8_3_8_s_fu_176.mul_32s_32s_32_1_1_U29", "Parent" : "1"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_s_axis_video_U", "Parent" : "0"},
	{"ID" : "16", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_m_axis_video_U", "Parent" : "0"}]}
