-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hls_filter_median_3x3 is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 5;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    s_axis_video_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
    s_axis_video_TVALID : IN STD_LOGIC;
    s_axis_video_TREADY : OUT STD_LOGIC;
    m_axis_video_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
    m_axis_video_TVALID : OUT STD_LOGIC;
    m_axis_video_TREADY : IN STD_LOGIC;
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of hls_filter_median_3x3 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "hls_filter_median_3x3_hls_filter_median_3x3,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.789000,HLS_SYN_LAT=33546246,HLS_SYN_TPT=none,HLS_SYN_MEM=8,HLS_SYN_DSP=0,HLS_SYN_FF=501,HLS_SYN_LUT=1546,HLS_VERSION=2025_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv14_3FFF : STD_LOGIC_VECTOR (13 downto 0) := "11111111111111";
    constant ap_const_lv13_1FFE : STD_LOGIC_VECTOR (12 downto 0) := "1111111111110";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal width : STD_LOGIC_VECTOR (12 downto 0);
    signal height : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln134_fu_73_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln134_reg_112 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal add_ln116_fu_90_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln116_reg_117 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln34_fu_105_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln34_reg_122 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_hls_filter_median_3x3_Pipeline_VITIS_LOOP_34_1_fu_58_ap_start : STD_LOGIC;
    signal grp_hls_filter_median_3x3_Pipeline_VITIS_LOOP_34_1_fu_58_ap_done : STD_LOGIC;
    signal grp_hls_filter_median_3x3_Pipeline_VITIS_LOOP_34_1_fu_58_ap_idle : STD_LOGIC;
    signal grp_hls_filter_median_3x3_Pipeline_VITIS_LOOP_34_1_fu_58_ap_ready : STD_LOGIC;
    signal grp_hls_filter_median_3x3_Pipeline_VITIS_LOOP_34_1_fu_58_m_axis_video_TREADY : STD_LOGIC;
    signal grp_hls_filter_median_3x3_Pipeline_VITIS_LOOP_34_1_fu_58_s_axis_video_TREADY : STD_LOGIC;
    signal grp_hls_filter_median_3x3_Pipeline_VITIS_LOOP_34_1_fu_58_m_axis_video_TDATA : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_hls_filter_median_3x3_Pipeline_VITIS_LOOP_34_1_fu_58_m_axis_video_TVALID : STD_LOGIC;
    signal grp_hls_filter_median_3x3_Pipeline_VITIS_LOOP_34_1_fu_58_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal m_axis_video_TDATA_reg : STD_LOGIC_VECTOR (23 downto 0);
    signal zext_ln134_fu_69_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln109_fu_80_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln116_fu_86_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln34_fu_105_p0 : STD_LOGIC_VECTOR (12 downto 0);
    signal mul_ln34_fu_105_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal regslice_both_m_axis_video_U_apdone_blk : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal regslice_both_s_axis_video_U_apdone_blk : STD_LOGIC;
    signal s_axis_video_TDATA_int_regslice : STD_LOGIC_VECTOR (23 downto 0);
    signal s_axis_video_TVALID_int_regslice : STD_LOGIC;
    signal s_axis_video_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_s_axis_video_U_ack_in : STD_LOGIC;
    signal m_axis_video_TDATA_int_regslice : STD_LOGIC_VECTOR (23 downto 0);
    signal m_axis_video_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_m_axis_video_U_vld_out : STD_LOGIC;
    signal mul_ln34_fu_105_p00 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln34_fu_105_p10 : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component hls_filter_median_3x3_hls_filter_median_3x3_Pipeline_VITIS_LOOP_34_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        s_axis_video_TVALID : IN STD_LOGIC;
        m_axis_video_TREADY : IN STD_LOGIC;
        mul_ln34 : IN STD_LOGIC_VECTOR (25 downto 0);
        add_ln134 : IN STD_LOGIC_VECTOR (13 downto 0);
        s_axis_video_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
        s_axis_video_TREADY : OUT STD_LOGIC;
        add_ln116 : IN STD_LOGIC_VECTOR (13 downto 0);
        m_axis_video_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
        m_axis_video_TVALID : OUT STD_LOGIC );
    end component;


    component hls_filter_median_3x3_mul_13ns_13ns_26_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (12 downto 0);
        din1 : IN STD_LOGIC_VECTOR (12 downto 0);
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component hls_filter_median_3x3_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        width : OUT STD_LOGIC_VECTOR (12 downto 0);
        height : OUT STD_LOGIC_VECTOR (12 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component hls_filter_median_3x3_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_hls_filter_median_3x3_Pipeline_VITIS_LOOP_34_1_fu_58 : component hls_filter_median_3x3_hls_filter_median_3x3_Pipeline_VITIS_LOOP_34_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_hls_filter_median_3x3_Pipeline_VITIS_LOOP_34_1_fu_58_ap_start,
        ap_done => grp_hls_filter_median_3x3_Pipeline_VITIS_LOOP_34_1_fu_58_ap_done,
        ap_idle => grp_hls_filter_median_3x3_Pipeline_VITIS_LOOP_34_1_fu_58_ap_idle,
        ap_ready => grp_hls_filter_median_3x3_Pipeline_VITIS_LOOP_34_1_fu_58_ap_ready,
        s_axis_video_TVALID => s_axis_video_TVALID_int_regslice,
        m_axis_video_TREADY => grp_hls_filter_median_3x3_Pipeline_VITIS_LOOP_34_1_fu_58_m_axis_video_TREADY,
        mul_ln34 => mul_ln34_reg_122,
        add_ln134 => add_ln134_reg_112,
        s_axis_video_TDATA => s_axis_video_TDATA_int_regslice,
        s_axis_video_TREADY => grp_hls_filter_median_3x3_Pipeline_VITIS_LOOP_34_1_fu_58_s_axis_video_TREADY,
        add_ln116 => add_ln116_reg_117,
        m_axis_video_TDATA => grp_hls_filter_median_3x3_Pipeline_VITIS_LOOP_34_1_fu_58_m_axis_video_TDATA,
        m_axis_video_TVALID => grp_hls_filter_median_3x3_Pipeline_VITIS_LOOP_34_1_fu_58_m_axis_video_TVALID);

    control_s_axi_U : component hls_filter_median_3x3_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        width => width,
        height => height,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    mul_13ns_13ns_26_1_1_U7 : component hls_filter_median_3x3_mul_13ns_13ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 13,
        din1_WIDTH => 13,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln34_fu_105_p0,
        din1 => mul_ln34_fu_105_p1,
        dout => mul_ln34_fu_105_p2);

    regslice_both_s_axis_video_U : component hls_filter_median_3x3_regslice_both
    generic map (
        DataWidth => 24)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => s_axis_video_TDATA,
        vld_in => s_axis_video_TVALID,
        ack_in => regslice_both_s_axis_video_U_ack_in,
        data_out => s_axis_video_TDATA_int_regslice,
        vld_out => s_axis_video_TVALID_int_regslice,
        ack_out => s_axis_video_TREADY_int_regslice,
        apdone_blk => regslice_both_s_axis_video_U_apdone_blk);

    regslice_both_m_axis_video_U : component hls_filter_median_3x3_regslice_both
    generic map (
        DataWidth => 24)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => m_axis_video_TDATA_int_regslice,
        vld_in => grp_hls_filter_median_3x3_Pipeline_VITIS_LOOP_34_1_fu_58_m_axis_video_TVALID,
        ack_in => m_axis_video_TREADY_int_regslice,
        data_out => m_axis_video_TDATA,
        vld_out => regslice_both_m_axis_video_U_vld_out,
        ack_out => m_axis_video_TREADY,
        apdone_blk => regslice_both_m_axis_video_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_hls_filter_median_3x3_Pipeline_VITIS_LOOP_34_1_fu_58_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_hls_filter_median_3x3_Pipeline_VITIS_LOOP_34_1_fu_58_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_hls_filter_median_3x3_Pipeline_VITIS_LOOP_34_1_fu_58_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_hls_filter_median_3x3_Pipeline_VITIS_LOOP_34_1_fu_58_ap_ready = ap_const_logic_1)) then 
                    grp_hls_filter_median_3x3_Pipeline_VITIS_LOOP_34_1_fu_58_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln116_reg_117 <= add_ln116_fu_90_p2;
                add_ln134_reg_112 <= add_ln134_fu_73_p2;
                mul_ln34_reg_122 <= mul_ln34_fu_105_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_hls_filter_median_3x3_Pipeline_VITIS_LOOP_34_1_fu_58_m_axis_video_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                m_axis_video_TDATA_reg <= grp_hls_filter_median_3x3_Pipeline_VITIS_LOOP_34_1_fu_58_m_axis_video_TDATA;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_hls_filter_median_3x3_Pipeline_VITIS_LOOP_34_1_fu_58_ap_done, ap_CS_fsm_state3, ap_CS_fsm_state4, regslice_both_m_axis_video_U_apdone_blk)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_hls_filter_median_3x3_Pipeline_VITIS_LOOP_34_1_fu_58_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (regslice_both_m_axis_video_U_apdone_blk = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    add_ln109_fu_80_p2 <= std_logic_vector(unsigned(width) + unsigned(ap_const_lv13_1FFE));
    add_ln116_fu_90_p2 <= std_logic_vector(unsigned(zext_ln116_fu_86_p1) + unsigned(ap_const_lv14_3FFF));
    add_ln134_fu_73_p2 <= std_logic_vector(unsigned(zext_ln134_fu_69_p1) + unsigned(ap_const_lv14_3FFF));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_hls_filter_median_3x3_Pipeline_VITIS_LOOP_34_1_fu_58_ap_done)
    begin
        if ((grp_hls_filter_median_3x3_Pipeline_VITIS_LOOP_34_1_fu_58_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state4_blk_assign_proc : process(regslice_both_m_axis_video_U_apdone_blk)
    begin
        if ((regslice_both_m_axis_video_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state4, regslice_both_m_axis_video_U_apdone_blk)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (regslice_both_m_axis_video_U_apdone_blk = ap_const_logic_0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state4, regslice_both_m_axis_video_U_apdone_blk)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (regslice_both_m_axis_video_U_apdone_blk = ap_const_logic_0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    grp_hls_filter_median_3x3_Pipeline_VITIS_LOOP_34_1_fu_58_ap_start <= grp_hls_filter_median_3x3_Pipeline_VITIS_LOOP_34_1_fu_58_ap_start_reg;
    grp_hls_filter_median_3x3_Pipeline_VITIS_LOOP_34_1_fu_58_m_axis_video_TREADY <= (m_axis_video_TREADY_int_regslice and ap_CS_fsm_state3);

    m_axis_video_TDATA_int_regslice_assign_proc : process(grp_hls_filter_median_3x3_Pipeline_VITIS_LOOP_34_1_fu_58_m_axis_video_TDATA, grp_hls_filter_median_3x3_Pipeline_VITIS_LOOP_34_1_fu_58_m_axis_video_TVALID, ap_CS_fsm_state3, m_axis_video_TDATA_reg)
    begin
        if (((grp_hls_filter_median_3x3_Pipeline_VITIS_LOOP_34_1_fu_58_m_axis_video_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            m_axis_video_TDATA_int_regslice <= grp_hls_filter_median_3x3_Pipeline_VITIS_LOOP_34_1_fu_58_m_axis_video_TDATA;
        else 
            m_axis_video_TDATA_int_regslice <= m_axis_video_TDATA_reg;
        end if; 
    end process;

    m_axis_video_TVALID <= regslice_both_m_axis_video_U_vld_out;
    mul_ln34_fu_105_p0 <= mul_ln34_fu_105_p00(13 - 1 downto 0);
    mul_ln34_fu_105_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(height),26));
    mul_ln34_fu_105_p1 <= mul_ln34_fu_105_p10(13 - 1 downto 0);
    mul_ln34_fu_105_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(width),26));
    s_axis_video_TREADY <= regslice_both_s_axis_video_U_ack_in;

    s_axis_video_TREADY_int_regslice_assign_proc : process(grp_hls_filter_median_3x3_Pipeline_VITIS_LOOP_34_1_fu_58_s_axis_video_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            s_axis_video_TREADY_int_regslice <= grp_hls_filter_median_3x3_Pipeline_VITIS_LOOP_34_1_fu_58_s_axis_video_TREADY;
        else 
            s_axis_video_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln116_fu_86_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln109_fu_80_p2),14));
    zext_ln134_fu_69_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(width),14));
end behav;
