-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hls_rgb_2_hsv is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 4;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_stream_TVALID : IN STD_LOGIC;
    in_stream_TREADY : OUT STD_LOGIC;
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of hls_rgb_2_hsv is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "hls_rgb_2_hsv_hls_rgb_2_hsv,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=4.544000,HLS_SYN_LAT=5,HLS_SYN_TPT=1,HLS_SYN_MEM=1,HLS_SYN_DSP=0,HLS_SYN_FF=395,HLS_SYN_LUT=547,HLS_VERSION=2025_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv7_3C : STD_LOGIC_VECTOR (6 downto 0) := "0111100";
    constant ap_const_lv7_78 : STD_LOGIC_VECTOR (6 downto 0) := "1111000";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv8_B4 : STD_LOGIC_VECTOR (7 downto 0) := "10110100";

    signal ap_rst_n_inv : STD_LOGIC;
    signal INV_TBL_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal INV_TBL_q0 : STD_LOGIC_VECTOR (16 downto 0);
    signal INV_TBL_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal INV_TBL_q1 : STD_LOGIC_VECTOR (16 downto 0);
    signal in_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp1_done_reg_iter0 : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal out_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone_grp1_done_reg : BOOLEAN := false;
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal Cmax_fu_216_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal Cmax_reg_510 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal Cmax_reg_510_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal Cmax_reg_510_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal Cmax_reg_510_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal delta_fu_224_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal delta_reg_517 : STD_LOGIC_VECTOR (7 downto 0);
    signal delta_reg_517_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal delta_reg_517_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal delta_reg_517_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln57_fu_230_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln57_reg_523 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln57_reg_523_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln57_reg_523_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln57_reg_523_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp2_fu_290_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal sel_tmp2_reg_528 : STD_LOGIC_VECTOR (1 downto 0);
    signal sel_tmp2_reg_528_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal sel_tmp2_reg_528_pp0_iter2_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal sel_tmp2_reg_528_pp0_iter3_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal diff_1_fu_298_p9 : STD_LOGIC_VECTOR (8 downto 0);
    signal diff_1_reg_533 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_1_reg_544 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_reg_544_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_reg_544_pp0_iter2_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_reg_544_pp0_iter3_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln52_fu_359_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_reg_554 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal regslice_both_out_stream_U_apdone_blk : STD_LOGIC;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal zext_ln71_fu_318_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln53_1_fu_364_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal INV_TBL_ce1_local : STD_LOGIC;
    signal INV_TBL_ce0_local : STD_LOGIC;
    signal in_packet_data_fu_144_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal in_packet_data_3_fu_148_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln43_fu_168_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln44_fu_182_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal min_rg_fu_174_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal in_packet_data_4_fu_158_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln45_fu_196_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal max_rg_fu_188_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln46_fu_210_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Cmin_fu_202_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln61_fu_242_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln61_1_fu_246_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln64_fu_262_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln60_fu_236_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln63_fu_256_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln60_fu_278_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln63_fu_284_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal diff_1_fu_298_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal diff_1_fu_298_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal diff_1_fu_298_p6 : STD_LOGIC_VECTOR (8 downto 0);
    signal diff_1_fu_298_p7 : STD_LOGIC_VECTOR (8 downto 0);
    signal diff_1_fu_298_p8 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_333_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_3_fu_344_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_shl5_fu_375_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln53_fu_368_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln53_fu_382_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sat_tmp_fu_392_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sat_tmp_fu_392_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal offset_fu_398_p7 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_501_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal offset_fu_398_p9 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln_fu_417_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln72_fu_426_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal hue_calc_fu_430_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln76_fu_444_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_4_fu_436_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln75_fu_448_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln75_fu_454_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sat_tmp_fu_392_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_fu_469_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_fu_479_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal hue_out_0_fu_462_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln88_7_fu_486_p5 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_501_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_501_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to4 : STD_LOGIC;
    signal ap_reset_init_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal regslice_both_in_stream_U_apdone_blk : STD_LOGIC;
    signal in_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal in_stream_TVALID_int_regslice : STD_LOGIC;
    signal in_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_in_stream_U_ack_in : STD_LOGIC;
    signal out_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal out_stream_TVALID_int_regslice : STD_LOGIC;
    signal out_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_out_stream_U_vld_out : STD_LOGIC;
    signal grp_fu_501_p20 : STD_LOGIC_VECTOR (27 downto 0);
    signal sat_tmp_fu_392_p00 : STD_LOGIC_VECTOR (23 downto 0);
    signal sat_tmp_fu_392_p10 : STD_LOGIC_VECTOR (23 downto 0);
    signal diff_1_fu_298_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal diff_1_fu_298_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal diff_1_fu_298_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal offset_fu_398_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal offset_fu_398_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal offset_fu_398_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component hls_rgb_2_hsv_sparsemux_7_2_9_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (8 downto 0);
        din1 : IN STD_LOGIC_VECTOR (8 downto 0);
        din2 : IN STD_LOGIC_VECTOR (8 downto 0);
        def : IN STD_LOGIC_VECTOR (8 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (8 downto 0) );
    end component;


    component hls_rgb_2_hsv_mul_16ns_17ns_24_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (16 downto 0);
        dout : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;


    component hls_rgb_2_hsv_sparsemux_7_2_7_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (6 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        din2 : IN STD_LOGIC_VECTOR (6 downto 0);
        def : IN STD_LOGIC_VECTOR (6 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (6 downto 0) );
    end component;


    component hls_rgb_2_hsv_am_submul_14s_10s_17ns_28_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (13 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        din2 : IN STD_LOGIC_VECTOR (16 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (27 downto 0) );
    end component;


    component hls_rgb_2_hsv_INV_TBL_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (16 downto 0);
        address1 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component hls_rgb_2_hsv_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC );
    end component;


    component hls_rgb_2_hsv_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    INV_TBL_U : component hls_rgb_2_hsv_INV_TBL_ROM_AUTO_1R
    generic map (
        DataWidth => 17,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => INV_TBL_address0,
        ce0 => INV_TBL_ce0_local,
        q0 => INV_TBL_q0,
        address1 => INV_TBL_address1,
        ce1 => INV_TBL_ce1_local,
        q1 => INV_TBL_q1);

    control_s_axi_U : component hls_rgb_2_hsv_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1);

    sparsemux_7_2_9_1_1_U1 : component hls_rgb_2_hsv_sparsemux_7_2_9_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 9,
        CASE1 => "01",
        din1_WIDTH => 9,
        CASE2 => "00",
        din2_WIDTH => 9,
        def_WIDTH => 9,
        sel_WIDTH => 2,
        dout_WIDTH => 9)
    port map (
        din0 => diff_1_fu_298_p2,
        din1 => diff_1_fu_298_p4,
        din2 => diff_1_fu_298_p6,
        def => diff_1_fu_298_p7,
        sel => diff_1_fu_298_p8,
        dout => diff_1_fu_298_p9);

    mul_16ns_17ns_24_1_1_U2 : component hls_rgb_2_hsv_mul_16ns_17ns_24_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 17,
        dout_WIDTH => 24)
    port map (
        din0 => sat_tmp_fu_392_p0,
        din1 => sat_tmp_fu_392_p1,
        dout => sat_tmp_fu_392_p2);

    sparsemux_7_2_7_1_1_U3 : component hls_rgb_2_hsv_sparsemux_7_2_7_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 7,
        CASE1 => "01",
        din1_WIDTH => 7,
        CASE2 => "00",
        din2_WIDTH => 7,
        def_WIDTH => 7,
        sel_WIDTH => 2,
        dout_WIDTH => 7)
    port map (
        din0 => ap_const_lv7_0,
        din1 => ap_const_lv7_3C,
        din2 => ap_const_lv7_78,
        def => offset_fu_398_p7,
        sel => sel_tmp2_reg_528_pp0_iter3_reg,
        dout => offset_fu_398_p9);

    am_submul_14s_10s_17ns_28_4_1_U4 : component hls_rgb_2_hsv_am_submul_14s_10s_17ns_28_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 14,
        din1_WIDTH => 10,
        din2_WIDTH => 17,
        dout_WIDTH => 28)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => tmp_2_fu_333_p3,
        din1 => tmp_3_fu_344_p3,
        din2 => grp_fu_501_p2,
        ce => grp_fu_501_ce,
        dout => grp_fu_501_p3);

    regslice_both_in_stream_U : component hls_rgb_2_hsv_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TDATA,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_U_ack_in,
        data_out => in_stream_TDATA_int_regslice,
        vld_out => in_stream_TVALID_int_regslice,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_U_apdone_blk);

    regslice_both_out_stream_U : component hls_rgb_2_hsv_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_stream_TDATA_int_regslice,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => out_stream_TREADY_int_regslice,
        data_out => out_stream_TDATA,
        vld_out => regslice_both_out_stream_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp1_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_block_pp0_stage0_subdone_grp1_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp1_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1)) then 
                    ap_block_pp0_stage0_subdone_grp1_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp1_done_reg_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_block_pp0_stage0_subdone_grp1_done_reg_iter0 <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp1_done_reg_iter0 <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1)) then 
                    ap_block_pp0_stage0_subdone_grp1_done_reg_iter0 <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                Cmax_reg_510 <= Cmax_fu_216_p3;
                delta_reg_517 <= delta_fu_224_p2;
                diff_1_reg_533 <= diff_1_fu_298_p9;
                icmp_ln57_reg_523 <= icmp_ln57_fu_230_p2;
                sel_tmp2_reg_528 <= sel_tmp2_fu_290_p3;
                tmp_1_reg_544 <= in_stream_TDATA_int_regslice(25 downto 24);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                Cmax_reg_510_pp0_iter1_reg <= Cmax_reg_510;
                delta_reg_517_pp0_iter1_reg <= delta_reg_517;
                icmp_ln57_reg_523_pp0_iter1_reg <= icmp_ln57_reg_523;
                sel_tmp2_reg_528_pp0_iter1_reg <= sel_tmp2_reg_528;
                tmp_1_reg_544_pp0_iter1_reg <= tmp_1_reg_544;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg))) then
                Cmax_reg_510_pp0_iter2_reg <= Cmax_reg_510_pp0_iter1_reg;
                Cmax_reg_510_pp0_iter3_reg <= Cmax_reg_510_pp0_iter2_reg;
                delta_reg_517_pp0_iter2_reg <= delta_reg_517_pp0_iter1_reg;
                delta_reg_517_pp0_iter3_reg <= delta_reg_517_pp0_iter2_reg;
                icmp_ln52_reg_554 <= icmp_ln52_fu_359_p2;
                icmp_ln57_reg_523_pp0_iter2_reg <= icmp_ln57_reg_523_pp0_iter1_reg;
                icmp_ln57_reg_523_pp0_iter3_reg <= icmp_ln57_reg_523_pp0_iter2_reg;
                sel_tmp2_reg_528_pp0_iter2_reg <= sel_tmp2_reg_528_pp0_iter1_reg;
                sel_tmp2_reg_528_pp0_iter3_reg <= sel_tmp2_reg_528_pp0_iter2_reg;
                tmp_1_reg_544_pp0_iter2_reg <= tmp_1_reg_544_pp0_iter1_reg;
                tmp_1_reg_544_pp0_iter3_reg <= tmp_1_reg_544_pp0_iter2_reg;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_init_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    Cmax_fu_216_p3 <= 
        max_rg_fu_188_p3 when (icmp_ln46_fu_210_p2(0) = '1') else 
        in_packet_data_4_fu_158_p4;
    Cmin_fu_202_p3 <= 
        min_rg_fu_174_p3 when (icmp_ln45_fu_196_p2(0) = '1') else 
        in_packet_data_4_fu_158_p4;
    INV_TBL_address0 <= zext_ln53_1_fu_364_p1(8 - 1 downto 0);
    INV_TBL_address1 <= zext_ln71_fu_318_p1(8 - 1 downto 0);

    INV_TBL_ce0_local_assign_proc : process(ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage0_11001_grp1, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            INV_TBL_ce0_local <= ap_const_logic_1;
        else 
            INV_TBL_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    INV_TBL_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone_grp1_done_reg_iter0, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            INV_TBL_ce1_local <= ap_const_logic_1;
        else 
            INV_TBL_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln75_fu_448_p2 <= std_logic_vector(unsigned(trunc_ln76_fu_444_p1) + unsigned(ap_const_lv8_B4));
    and_ln63_fu_284_p2 <= (xor_ln60_fu_278_p2 and icmp_ln63_fu_256_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_block_pp0_stage0_subdone_grp1_done_reg_iter0, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_enable_reg_pp0_iter5, in_stream_TVALID_int_regslice, out_stream_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_01001_grp1 <= (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (out_stream_TREADY_int_regslice = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg)) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (out_stream_TREADY_int_regslice = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg)) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) and (ap_const_logic_1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_block_pp0_stage0_subdone_grp1_done_reg_iter0, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_enable_reg_pp0_iter5, regslice_both_out_stream_U_apdone_blk, in_stream_TVALID_int_regslice, out_stream_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and ((regslice_both_out_stream_U_apdone_blk = ap_const_logic_1) or ((out_stream_TREADY_int_regslice = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg)))) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (out_stream_TREADY_int_regslice = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg)) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) and (ap_const_logic_1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_block_pp0_stage0_subdone_grp1_done_reg_iter0, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_enable_reg_pp0_iter5, in_stream_TVALID_int_regslice, out_stream_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_11001_grp1 <= (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (out_stream_TREADY_int_regslice = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg)) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (out_stream_TREADY_int_regslice = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg)) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) and (ap_const_logic_1 = ap_const_logic_1)));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_block_pp0_stage0_subdone_grp1_done_reg_iter0, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_enable_reg_pp0_iter5, regslice_both_out_stream_U_apdone_blk, in_stream_TVALID_int_regslice, out_stream_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and ((regslice_both_out_stream_U_apdone_blk = ap_const_logic_1) or ((out_stream_TREADY_int_regslice = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg)))) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (out_stream_TREADY_int_regslice = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg)) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) and (ap_const_logic_1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_grp1_assign_proc : process(ap_block_pp0_stage0_subdone_grp1_done_reg_iter0, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_enable_reg_pp0_iter5, in_stream_TVALID_int_regslice, out_stream_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_subdone_grp1 <= (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (out_stream_TREADY_int_regslice = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg)) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (out_stream_TREADY_int_regslice = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg)) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) and (ap_const_logic_1 = ap_const_logic_1)));
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_idle_pp0 <= ap_const_logic_0;
    ap_idle_pp0_0to4 <= ap_const_logic_0;

    ap_reset_init_pp0_assign_proc : process(ap_idle_pp0_0to4)
    begin
        if ((ap_idle_pp0_0to4 = ap_const_logic_1)) then 
            ap_reset_init_pp0 <= ap_const_logic_1;
        else 
            ap_reset_init_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    delta_fu_224_p2 <= std_logic_vector(unsigned(Cmax_fu_216_p3) - unsigned(Cmin_fu_202_p3));
    diff_1_fu_298_p2 <= std_logic_vector(unsigned(zext_ln61_fu_242_p1) - unsigned(zext_ln61_1_fu_246_p1));
    diff_1_fu_298_p4 <= std_logic_vector(unsigned(zext_ln61_1_fu_246_p1) - unsigned(zext_ln64_fu_262_p1));
    diff_1_fu_298_p6 <= std_logic_vector(unsigned(zext_ln64_fu_262_p1) - unsigned(zext_ln61_fu_242_p1));
    diff_1_fu_298_p7 <= "XXXXXXXXX";
    diff_1_fu_298_p8 <= (icmp_ln60_fu_236_p2 & and_ln63_fu_284_p2);
    empty_fu_479_p3 <= 
        ap_const_lv8_0 when (icmp_ln52_reg_554(0) = '1') else 
        tmp_fu_469_p4;

    grp_fu_501_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_501_ce <= ap_const_logic_1;
        else 
            grp_fu_501_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_501_p2 <= grp_fu_501_p20(17 - 1 downto 0);
    grp_fu_501_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(INV_TBL_q1),28));
    hue_calc_fu_430_p2 <= std_logic_vector(unsigned(trunc_ln_fu_417_p4) + unsigned(zext_ln72_fu_426_p1));
    hue_out_0_fu_462_p3 <= 
        ap_const_lv8_0 when (icmp_ln57_reg_523_pp0_iter3_reg(0) = '1') else 
        select_ln75_fu_454_p3;
    icmp_ln43_fu_168_p2 <= "1" when (unsigned(in_packet_data_fu_144_p1) < unsigned(in_packet_data_3_fu_148_p4)) else "0";
    icmp_ln44_fu_182_p2 <= "1" when (unsigned(in_packet_data_fu_144_p1) > unsigned(in_packet_data_3_fu_148_p4)) else "0";
    icmp_ln45_fu_196_p2 <= "1" when (unsigned(min_rg_fu_174_p3) < unsigned(in_packet_data_4_fu_158_p4)) else "0";
    icmp_ln46_fu_210_p2 <= "1" when (unsigned(max_rg_fu_188_p3) > unsigned(in_packet_data_4_fu_158_p4)) else "0";
    icmp_ln52_fu_359_p2 <= "1" when (Cmax_reg_510_pp0_iter2_reg = ap_const_lv8_0) else "0";
    icmp_ln57_fu_230_p2 <= "1" when (Cmax_fu_216_p3 = Cmin_fu_202_p3) else "0";
    icmp_ln60_fu_236_p2 <= "1" when (Cmax_fu_216_p3 = in_packet_data_fu_144_p1) else "0";
    icmp_ln63_fu_256_p2 <= "1" when (Cmax_fu_216_p3 = in_packet_data_3_fu_148_p4) else "0";
    in_packet_data_3_fu_148_p4 <= in_stream_TDATA_int_regslice(15 downto 8);
    in_packet_data_4_fu_158_p4 <= in_stream_TDATA_int_regslice(23 downto 16);
    in_packet_data_fu_144_p1 <= in_stream_TDATA_int_regslice(8 - 1 downto 0);

    in_stream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_grp1, ap_block_pp0_stage0_subdone_grp1_done_reg_iter0, in_stream_TVALID_int_regslice)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream_TDATA_blk_n <= in_stream_TVALID_int_regslice;
        else 
            in_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    in_stream_TREADY <= regslice_both_in_stream_U_ack_in;

    in_stream_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone_grp1_done_reg_iter0, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream_TREADY_int_regslice <= ap_const_logic_1;
        else 
            in_stream_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    max_rg_fu_188_p3 <= 
        in_packet_data_fu_144_p1 when (icmp_ln44_fu_182_p2(0) = '1') else 
        in_packet_data_3_fu_148_p4;
    min_rg_fu_174_p3 <= 
        in_packet_data_fu_144_p1 when (icmp_ln43_fu_168_p2(0) = '1') else 
        in_packet_data_3_fu_148_p4;
    offset_fu_398_p7 <= "XXXXXXX";
    or_ln88_7_fu_486_p5 <= (((tmp_1_reg_544_pp0_iter3_reg & Cmax_reg_510_pp0_iter3_reg) & empty_fu_479_p3) & hue_out_0_fu_462_p3);

    out_stream_TDATA_blk_n_assign_proc : process(ap_block_pp0_stage0_grp1, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_enable_reg_pp0_iter5, out_stream_TREADY_int_regslice)
    begin
        if ((((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1)) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1)))) then 
            out_stream_TDATA_blk_n <= out_stream_TREADY_int_regslice;
        else 
            out_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_stream_TDATA_int_regslice <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln88_7_fu_486_p5),32));
    out_stream_TVALID <= regslice_both_out_stream_U_vld_out;

    out_stream_TVALID_int_regslice_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg))) then 
            out_stream_TVALID_int_regslice <= ap_const_logic_1;
        else 
            out_stream_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    p_shl5_fu_375_p3 <= (delta_reg_517_pp0_iter3_reg & ap_const_lv8_0);
    sat_tmp_fu_392_p0 <= sat_tmp_fu_392_p00(16 - 1 downto 0);
    sat_tmp_fu_392_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln53_fu_382_p2),24));
    sat_tmp_fu_392_p1 <= sat_tmp_fu_392_p10(17 - 1 downto 0);
    sat_tmp_fu_392_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(INV_TBL_q0),24));
    sel_tmp2_fu_290_p3 <= (icmp_ln60_fu_236_p2 & and_ln63_fu_284_p2);
    select_ln75_fu_454_p3 <= 
        add_ln75_fu_448_p2 when (tmp_4_fu_436_p3(0) = '1') else 
        trunc_ln76_fu_444_p1;
    sub_ln53_fu_382_p2 <= std_logic_vector(unsigned(p_shl5_fu_375_p3) - unsigned(zext_ln53_fu_368_p1));
    tmp_2_fu_333_p3 <= (diff_1_reg_533 & ap_const_lv5_0);
    tmp_3_fu_344_p3 <= (diff_1_reg_533 & ap_const_lv1_0);
    tmp_4_fu_436_p3 <= hue_calc_fu_430_p2(11 downto 11);
    tmp_fu_469_p4 <= sat_tmp_fu_392_p2(23 downto 16);
    trunc_ln76_fu_444_p1 <= hue_calc_fu_430_p2(8 - 1 downto 0);
    trunc_ln_fu_417_p4 <= grp_fu_501_p3(27 downto 16);
    xor_ln60_fu_278_p2 <= (icmp_ln60_fu_236_p2 xor ap_const_lv1_1);
    zext_ln53_1_fu_364_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Cmax_reg_510_pp0_iter2_reg),64));
    zext_ln53_fu_368_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(delta_reg_517_pp0_iter3_reg),16));
    zext_ln61_1_fu_246_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(in_packet_data_4_fu_158_p4),9));
    zext_ln61_fu_242_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(in_packet_data_3_fu_148_p4),9));
    zext_ln64_fu_262_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(in_packet_data_fu_144_p1),9));
    zext_ln71_fu_318_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(delta_fu_224_p2),64));
    zext_ln72_fu_426_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(offset_fu_398_p9),12));
end behav;
