-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hls_color_space_convert_top_hls_color_space_convert_template_3_8_3_8_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    s_axis_video_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    s_axis_video_TVALID : IN STD_LOGIC;
    s_axis_video_TREADY : OUT STD_LOGIC;
    m_axis_video_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axis_video_TVALID : OUT STD_LOGIC;
    m_axis_video_TREADY : IN STD_LOGIC;
    coeffs_0_0_0_0_0_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
    coeffs_0_1_0_0_0_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
    coeffs_0_2_0_0_0_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
    coeffs_1_0_0_0_0_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
    coeffs_1_1_0_0_0_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
    coeffs_1_2_0_0_0_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
    coeffs_2_0_0_0_0_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
    coeffs_2_1_0_0_0_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
    coeffs_2_2_0_0_0_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
    offsets_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
    offsets_1_val : IN STD_LOGIC_VECTOR (15 downto 0);
    offsets_2_val : IN STD_LOGIC_VECTOR (15 downto 0);
    width : IN STD_LOGIC_VECTOR (31 downto 0);
    height : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of hls_color_space_convert_top_hls_color_space_convert_template_3_8_3_8_s is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal total_pixels_fu_168_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal total_pixels_reg_185 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal add_ln43_fu_174_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln43_reg_250 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134_ap_start : STD_LOGIC;
    signal grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134_ap_done : STD_LOGIC;
    signal grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134_ap_idle : STD_LOGIC;
    signal grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134_ap_ready : STD_LOGIC;
    signal grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134_m_axis_video_TREADY : STD_LOGIC;
    signal grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134_s_axis_video_TREADY : STD_LOGIC;
    signal grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134_m_axis_video_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134_m_axis_video_TVALID : STD_LOGIC;
    signal grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal m_axis_video_TDATA_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln43_fu_174_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component hls_color_space_convert_top_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        s_axis_video_TVALID : IN STD_LOGIC;
        m_axis_video_TREADY : IN STD_LOGIC;
        total_pixels : IN STD_LOGIC_VECTOR (31 downto 0);
        s_axis_video_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        s_axis_video_TREADY : OUT STD_LOGIC;
        sext_ln29 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln29_1 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln29_2 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln29_9 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln29_3 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln29_4 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln29_5 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln29_10 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln29_6 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln29_7 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln29_8 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln19 : IN STD_LOGIC_VECTOR (15 downto 0);
        add_ln43 : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axis_video_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axis_video_TVALID : OUT STD_LOGIC );
    end component;


    component hls_color_space_convert_top_mul_32s_32s_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134 : component hls_color_space_convert_top_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134_ap_start,
        ap_done => grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134_ap_done,
        ap_idle => grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134_ap_idle,
        ap_ready => grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134_ap_ready,
        s_axis_video_TVALID => s_axis_video_TVALID,
        m_axis_video_TREADY => grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134_m_axis_video_TREADY,
        total_pixels => total_pixels_reg_185,
        s_axis_video_TDATA => s_axis_video_TDATA,
        s_axis_video_TREADY => grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134_s_axis_video_TREADY,
        sext_ln29 => coeffs_0_0_0_0_0_0_val,
        sext_ln29_1 => coeffs_0_1_0_0_0_0_val,
        sext_ln29_2 => coeffs_0_2_0_0_0_0_val,
        sext_ln29_9 => offsets_0_val,
        sext_ln29_3 => coeffs_1_0_0_0_0_0_val,
        sext_ln29_4 => coeffs_1_1_0_0_0_0_val,
        sext_ln29_5 => coeffs_1_2_0_0_0_0_val,
        sext_ln29_10 => offsets_1_val,
        sext_ln29_6 => coeffs_2_0_0_0_0_0_val,
        sext_ln29_7 => coeffs_2_1_0_0_0_0_val,
        sext_ln29_8 => coeffs_2_2_0_0_0_0_val,
        sext_ln19 => offsets_2_val,
        add_ln43 => add_ln43_reg_250,
        m_axis_video_TDATA => grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134_m_axis_video_TDATA,
        m_axis_video_TVALID => grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134_m_axis_video_TVALID);

    mul_32s_32s_32_1_1_U29 : component hls_color_space_convert_top_mul_32s_32s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => height,
        din1 => width,
        dout => total_pixels_fu_168_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134_ap_ready = ap_const_logic_1)) then 
                    grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln43_reg_250 <= add_ln43_fu_174_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134_m_axis_video_TVALID = ap_const_logic_1))) then
                m_axis_video_TDATA_reg <= grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134_m_axis_video_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                total_pixels_reg_185 <= total_pixels_fu_168_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134_ap_done, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    add_ln43_fu_174_p0 <= width;
    add_ln43_fu_174_p2 <= std_logic_vector(signed(add_ln43_fu_174_p0) + signed(ap_const_lv32_FFFFFFFF));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134_ap_done)
    begin
        if ((grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134_ap_done, ap_CS_fsm_state3)
    begin
        if ((((grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134_ap_done, ap_CS_fsm_state3)
    begin
        if (((grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134_ap_start <= grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134_ap_start_reg;
    grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134_m_axis_video_TREADY <= (m_axis_video_TREADY and ap_CS_fsm_state3);

    m_axis_video_TDATA_assign_proc : process(grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134_m_axis_video_TDATA, grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134_m_axis_video_TVALID, ap_CS_fsm_state3, m_axis_video_TDATA_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134_m_axis_video_TVALID = ap_const_logic_1))) then 
            m_axis_video_TDATA <= grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134_m_axis_video_TDATA;
        else 
            m_axis_video_TDATA <= m_axis_video_TDATA_reg;
        end if; 
    end process;

    m_axis_video_TVALID <= grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134_m_axis_video_TVALID;

    s_axis_video_TREADY_assign_proc : process(grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134_s_axis_video_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            s_axis_video_TREADY <= grp_hls_color_space_convert_template_3_8_3_8_Pipeline_VITIS_LOOP_19_1_fu_134_s_axis_video_TREADY;
        else 
            s_axis_video_TREADY <= ap_const_logic_0;
        end if; 
    end process;

end behav;
