// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module design_1_v_frmbuf_rd_0_0_Bytes2MultiPixStream (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        bytePlanes_dout,
        bytePlanes_empty_n,
        bytePlanes_read,
        bytePlanes_num_data_valid,
        bytePlanes_fifo_cap,
        img_din,
        img_full_n,
        img_write,
        img_num_data_valid,
        img_fifo_cap,
        Height_val,
        Width_val,
        WidthInBytes_val,
        VideoFormat_val
);

parameter    ap_ST_fsm_state1 = 17'd1;
parameter    ap_ST_fsm_state2 = 17'd2;
parameter    ap_ST_fsm_state3 = 17'd4;
parameter    ap_ST_fsm_state4 = 17'd8;
parameter    ap_ST_fsm_state5 = 17'd16;
parameter    ap_ST_fsm_state6 = 17'd32;
parameter    ap_ST_fsm_state7 = 17'd64;
parameter    ap_ST_fsm_state8 = 17'd128;
parameter    ap_ST_fsm_state9 = 17'd256;
parameter    ap_ST_fsm_state10 = 17'd512;
parameter    ap_ST_fsm_state11 = 17'd1024;
parameter    ap_ST_fsm_state12 = 17'd2048;
parameter    ap_ST_fsm_state13 = 17'd4096;
parameter    ap_ST_fsm_state14 = 17'd8192;
parameter    ap_ST_fsm_state15 = 17'd16384;
parameter    ap_ST_fsm_state16 = 17'd32768;
parameter    ap_ST_fsm_state17 = 17'd65536;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [63:0] bytePlanes_dout;
input   bytePlanes_empty_n;
output   bytePlanes_read;
input  [9:0] bytePlanes_num_data_valid;
input  [9:0] bytePlanes_fifo_cap;
output  [23:0] img_din;
input   img_full_n;
output   img_write;
input  [31:0] img_num_data_valid;
input  [31:0] img_fifo_cap;
input  [10:0] Height_val;
input  [10:0] Width_val;
input  [13:0] WidthInBytes_val;
input  [5:0] VideoFormat_val;

reg ap_done;
reg ap_idle;
reg start_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [16:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
wire   [5:0] VideoFormat_val_read_read_fu_148_p2;
reg   [5:0] VideoFormat_val_read_reg_406;
reg    ap_block_state1;
reg   [10:0] Height_val_read_reg_410;
reg   [10:0] trunc_ln_reg_422;
wire   [2:0] remainPix_fu_249_p1;
reg   [2:0] remainPix_reg_428;
reg   [8:0] trunc_ln2_cast_reg_434;
wire    ap_CS_fsm_state15;
wire   [0:0] icmp_ln1229_fu_300_p2;
reg   [0:0] icmp_ln1229_reg_439;
wire   [9:0] add_ln1247_fu_313_p2;
reg   [9:0] add_ln1247_reg_444;
wire   [0:0] icmp_ln1247_fu_319_p2;
reg   [0:0] icmp_ln1247_reg_449;
wire   [0:0] icmp_ln1250_fu_325_p2;
reg   [0:0] icmp_ln1250_reg_454;
wire   [0:0] icmp_ln1271_fu_341_p2;
reg   [0:0] icmp_ln1271_reg_459;
wire   [0:0] icmp_ln1271_1_fu_347_p2;
reg   [0:0] icmp_ln1271_1_reg_464;
wire   [0:0] icmp_ln1271_2_fu_363_p2;
reg   [0:0] icmp_ln1271_2_reg_469;
wire   [0:0] icmp_ln1271_3_fu_369_p2;
reg   [0:0] icmp_ln1271_3_reg_474;
wire   [0:0] icmp_ln1271_4_fu_375_p2;
reg   [0:0] icmp_ln1271_4_reg_479;
wire   [0:0] icmp_ln1271_5_fu_381_p2;
reg   [0:0] icmp_ln1271_5_reg_484;
wire    grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1240_1_fu_172_ap_start;
wire    grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1240_1_fu_172_ap_done;
wire    grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1240_1_fu_172_ap_idle;
wire    grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1240_1_fu_172_ap_ready;
wire   [23:0] grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1240_1_fu_172_img_din;
wire    grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1240_1_fu_172_img_write;
wire    grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1240_1_fu_172_bytePlanes_read;
reg    grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1240_1_fu_172_ap_start_reg;
wire    ap_CS_fsm_state16;
wire   [0:0] icmp_ln1232_fu_390_p2;
wire    ap_CS_fsm_state17;
reg   [10:0] y_fu_144;
wire   [10:0] y_2_fu_395_p2;
wire   [13:0] add_ln1224_fu_227_p2;
wire   [10:0] grp_fu_243_p0;
wire   [2:0] grp_fu_243_p1;
wire   [10:0] add_ln1225_fu_258_p2;
wire   [10:0] mul_ln1225_fu_267_p0;
wire   [12:0] mul_ln1225_fu_267_p1;
wire   [22:0] mul_ln1225_fu_267_p2;
wire   [1:0] grp_fu_243_p2;
wire   [3:0] zext_ln1228_fu_297_p1;
wire   [9:0] trunc_ln2_fu_273_p4;
wire   [1:0] trunc_ln1226_fu_293_p1;
wire   [3:0] remainPix_1_fu_305_p3;
wire   [2:0] tmp_8_fu_331_p4;
wire   [1:0] tmp_9_fu_353_p4;
reg    grp_fu_243_ap_start;
wire    grp_fu_243_ap_done;
reg    grp_fu_243_ce;
reg   [16:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
reg    ap_ST_fsm_state17_blk;
wire   [22:0] mul_ln1225_fu_267_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 17'd1;
#0 VideoFormat_val_read_reg_406 = 6'd0;
#0 Height_val_read_reg_410 = 11'd0;
#0 trunc_ln_reg_422 = 11'd0;
#0 remainPix_reg_428 = 3'd0;
#0 trunc_ln2_cast_reg_434 = 9'd0;
#0 icmp_ln1229_reg_439 = 1'd0;
#0 add_ln1247_reg_444 = 10'd0;
#0 icmp_ln1247_reg_449 = 1'd0;
#0 icmp_ln1250_reg_454 = 1'd0;
#0 icmp_ln1271_reg_459 = 1'd0;
#0 icmp_ln1271_1_reg_464 = 1'd0;
#0 icmp_ln1271_2_reg_469 = 1'd0;
#0 icmp_ln1271_3_reg_474 = 1'd0;
#0 icmp_ln1271_4_reg_479 = 1'd0;
#0 icmp_ln1271_5_reg_484 = 1'd0;
#0 grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1240_1_fu_172_ap_start_reg = 1'b0;
#0 y_fu_144 = 11'd0;
end

design_1_v_frmbuf_rd_0_0_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1240_1 grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1240_1_fu_172(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1240_1_fu_172_ap_start),
    .ap_done(grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1240_1_fu_172_ap_done),
    .ap_idle(grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1240_1_fu_172_ap_idle),
    .ap_ready(grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1240_1_fu_172_ap_ready),
    .img_din(grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1240_1_fu_172_img_din),
    .img_full_n(img_full_n),
    .img_write(grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1240_1_fu_172_img_write),
    .img_num_data_valid(img_num_data_valid),
    .img_fifo_cap(img_fifo_cap),
    .bytePlanes_dout(bytePlanes_dout),
    .bytePlanes_empty_n(bytePlanes_empty_n),
    .bytePlanes_read(grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1240_1_fu_172_bytePlanes_read),
    .bytePlanes_num_data_valid(10'd0),
    .bytePlanes_fifo_cap(10'd0),
    .trunc_ln2(trunc_ln2_cast_reg_434),
    .icmp_ln1229(icmp_ln1229_reg_439),
    .icmp_ln1271_5(icmp_ln1271_5_reg_484),
    .icmp_ln1271_4(icmp_ln1271_4_reg_479),
    .icmp_ln1271_3(icmp_ln1271_3_reg_474),
    .icmp9(icmp_ln1271_2_reg_469),
    .icmp_ln1271_1(icmp_ln1271_1_reg_464),
    .icmp6(icmp_ln1271_reg_459),
    .icmp_ln1250(icmp_ln1250_reg_454),
    .add_ln1247(add_ln1247_reg_444),
    .icmp_ln1247(icmp_ln1247_reg_449)
);

design_1_v_frmbuf_rd_0_0_urem_11ns_3ns_2_15_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 15 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 2 ))
urem_11ns_3ns_2_15_seq_1_U24(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_243_ap_start),
    .done(grp_fu_243_ap_done),
    .din0(grp_fu_243_p0),
    .din1(grp_fu_243_p1),
    .ce(grp_fu_243_ce),
    .dout(grp_fu_243_p2)
);

design_1_v_frmbuf_rd_0_0_mul_11ns_13ns_23_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 23 ))
mul_11ns_13ns_23_1_1_U25(
    .din0(mul_ln1225_fu_267_p0),
    .din1(mul_ln1225_fu_267_p1),
    .dout(mul_ln1225_fu_267_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        Height_val_read_reg_410 <= 11'd0;
    end else begin
        if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            Height_val_read_reg_410 <= Height_val;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        VideoFormat_val_read_reg_406 <= 6'd0;
    end else begin
        if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            VideoFormat_val_read_reg_406 <= VideoFormat_val;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        add_ln1247_reg_444 <= 10'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state15)) begin
            add_ln1247_reg_444 <= add_ln1247_fu_313_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state16) & ((6'd43 == VideoFormat_val_read_reg_406) | ((6'd42 == VideoFormat_val_read_reg_406) | ((6'd44 == VideoFormat_val_read_reg_406) | ((6'd41 == VideoFormat_val_read_reg_406) | ((6'd19 == VideoFormat_val_read_reg_406) | ((6'd18 == VideoFormat_val_read_reg_406) | ((6'd23 == VideoFormat_val_read_reg_406) | ((6'd22 == VideoFormat_val_read_reg_406) | ((6'd33 == VideoFormat_val_read_reg_406) | ((6'd32 == VideoFormat_val_read_reg_406) | ((6'd38 == VideoFormat_val_read_reg_406) | ((6'd37 == VideoFormat_val_read_reg_406) | ((6'd12 == VideoFormat_val_read_reg_406) | ((6'd28 == VideoFormat_val_read_reg_406) | ((icmp_ln1232_fu_390_p2 == 1'd1) | (~(6'd21 == VideoFormat_val_read_reg_406) & ~(6'd20 == VideoFormat_val_read_reg_406))))))))))))))))))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1240_1_fu_172_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state16) & (((6'd21 == VideoFormat_val_read_reg_406) & (icmp_ln1232_fu_390_p2 == 1'd0)) | ((icmp_ln1232_fu_390_p2 == 1'd0) & (6'd20 == VideoFormat_val_read_reg_406))))) begin
            grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1240_1_fu_172_ap_start_reg <= 1'b1;
        end else if ((grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1240_1_fu_172_ap_ready == 1'b1)) begin
            grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1240_1_fu_172_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        icmp_ln1229_reg_439 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state15)) begin
            icmp_ln1229_reg_439 <= icmp_ln1229_fu_300_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        icmp_ln1247_reg_449 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state15)) begin
            icmp_ln1247_reg_449 <= icmp_ln1247_fu_319_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        icmp_ln1250_reg_454 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state15)) begin
            icmp_ln1250_reg_454 <= icmp_ln1250_fu_325_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        icmp_ln1271_1_reg_464 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state15)) begin
            icmp_ln1271_1_reg_464 <= icmp_ln1271_1_fu_347_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        icmp_ln1271_2_reg_469 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state15)) begin
            icmp_ln1271_2_reg_469 <= icmp_ln1271_2_fu_363_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        icmp_ln1271_3_reg_474 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state15)) begin
            icmp_ln1271_3_reg_474 <= icmp_ln1271_3_fu_369_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        icmp_ln1271_4_reg_479 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state15)) begin
            icmp_ln1271_4_reg_479 <= icmp_ln1271_4_fu_375_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        icmp_ln1271_5_reg_484 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state15)) begin
            icmp_ln1271_5_reg_484 <= icmp_ln1271_5_fu_381_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        icmp_ln1271_reg_459 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state15)) begin
            icmp_ln1271_reg_459 <= icmp_ln1271_fu_341_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        remainPix_reg_428 <= 3'd0;
    end else begin
        if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            remainPix_reg_428 <= remainPix_fu_249_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        trunc_ln2_cast_reg_434 <= 9'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state15)) begin
            trunc_ln2_cast_reg_434 <= {{mul_ln1225_fu_267_p2[21:13]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        trunc_ln_reg_422 <= 11'd0;
    end else begin
        if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            trunc_ln_reg_422 <= {{add_ln1224_fu_227_p2[13:3]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        y_fu_144 <= 11'd0;
    end else begin
        if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1) & ((6'd21 == VideoFormat_val) | (6'd20 == VideoFormat_val)))) begin
            y_fu_144 <= 11'd0;
        end else if (((1'b1 == ap_CS_fsm_state16) & (((6'd21 == VideoFormat_val_read_reg_406) & (icmp_ln1232_fu_390_p2 == 1'd0)) | ((icmp_ln1232_fu_390_p2 == 1'd0) & (6'd20 == VideoFormat_val_read_reg_406))))) begin
            y_fu_144 <= y_2_fu_395_p2;
        end
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

always @ (*) begin
    if ((grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1240_1_fu_172_ap_done == 1'b0)) begin
        ap_ST_fsm_state17_blk = 1'b1;
    end else begin
        ap_ST_fsm_state17_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) & ((6'd43 == VideoFormat_val_read_reg_406) | ((6'd42 == VideoFormat_val_read_reg_406) | ((6'd44 == VideoFormat_val_read_reg_406) | ((6'd41 == VideoFormat_val_read_reg_406) | ((6'd19 == VideoFormat_val_read_reg_406) | ((6'd18 == VideoFormat_val_read_reg_406) | ((6'd23 == VideoFormat_val_read_reg_406) | ((6'd22 == VideoFormat_val_read_reg_406) | ((6'd33 == VideoFormat_val_read_reg_406) | ((6'd32 == VideoFormat_val_read_reg_406) | ((6'd38 == VideoFormat_val_read_reg_406) | ((6'd37 == VideoFormat_val_read_reg_406) | ((6'd12 == VideoFormat_val_read_reg_406) | ((6'd28 == VideoFormat_val_read_reg_406) | ((icmp_ln1232_fu_390_p2 == 1'd1) | (~(6'd21 == VideoFormat_val_read_reg_406) & ~(6'd20 == VideoFormat_val_read_reg_406))))))))))))))))))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1) & ((6'd21 == VideoFormat_val) | (6'd20 == VideoFormat_val)))) begin
        grp_fu_243_ap_start = 1'b1;
    end else begin
        grp_fu_243_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16))) begin
        grp_fu_243_ce = 1'b0;
    end else begin
        grp_fu_243_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) & ((6'd43 == VideoFormat_val_read_reg_406) | ((6'd42 == VideoFormat_val_read_reg_406) | ((6'd44 == VideoFormat_val_read_reg_406) | ((6'd41 == VideoFormat_val_read_reg_406) | ((6'd19 == VideoFormat_val_read_reg_406) | ((6'd18 == VideoFormat_val_read_reg_406) | ((6'd23 == VideoFormat_val_read_reg_406) | ((6'd22 == VideoFormat_val_read_reg_406) | ((6'd33 == VideoFormat_val_read_reg_406) | ((6'd32 == VideoFormat_val_read_reg_406) | ((6'd38 == VideoFormat_val_read_reg_406) | ((6'd37 == VideoFormat_val_read_reg_406) | ((6'd12 == VideoFormat_val_read_reg_406) | ((6'd28 == VideoFormat_val_read_reg_406) | ((icmp_ln1232_fu_390_p2 == 1'd1) | (~(6'd21 == VideoFormat_val_read_reg_406) & ~(6'd20 == VideoFormat_val_read_reg_406))))))))))))))))))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1) & ((6'd43 == VideoFormat_val_read_read_fu_148_p2) | ((6'd42 == VideoFormat_val_read_read_fu_148_p2) | ((6'd44 == VideoFormat_val_read_read_fu_148_p2) | ((6'd41 == VideoFormat_val_read_read_fu_148_p2) | ((6'd19 == VideoFormat_val_read_read_fu_148_p2) | ((6'd18 == VideoFormat_val_read_read_fu_148_p2) | ((6'd23 == VideoFormat_val_read_read_fu_148_p2) | ((6'd22 == VideoFormat_val_read_read_fu_148_p2) | ((6'd33 == VideoFormat_val_read_read_fu_148_p2) | ((6'd32 == VideoFormat_val_read_read_fu_148_p2) | ((6'd38 == VideoFormat_val_read_read_fu_148_p2) | ((6'd37 == VideoFormat_val_read_read_fu_148_p2) | ((6'd12 == VideoFormat_val_read_read_fu_148_p2) | ((6'd28 == VideoFormat_val_read_read_fu_148_p2) | (~(6'd21 == VideoFormat_val) & ~(6'd20 == VideoFormat_val)))))))))))))))))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1) & ((6'd21 == VideoFormat_val) | (6'd20 == VideoFormat_val)))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            if (((1'b1 == ap_CS_fsm_state16) & ((6'd43 == VideoFormat_val_read_reg_406) | ((6'd42 == VideoFormat_val_read_reg_406) | ((6'd44 == VideoFormat_val_read_reg_406) | ((6'd41 == VideoFormat_val_read_reg_406) | ((6'd19 == VideoFormat_val_read_reg_406) | ((6'd18 == VideoFormat_val_read_reg_406) | ((6'd23 == VideoFormat_val_read_reg_406) | ((6'd22 == VideoFormat_val_read_reg_406) | ((6'd33 == VideoFormat_val_read_reg_406) | ((6'd32 == VideoFormat_val_read_reg_406) | ((6'd38 == VideoFormat_val_read_reg_406) | ((6'd37 == VideoFormat_val_read_reg_406) | ((6'd12 == VideoFormat_val_read_reg_406) | ((6'd28 == VideoFormat_val_read_reg_406) | ((icmp_ln1232_fu_390_p2 == 1'd1) | (~(6'd21 == VideoFormat_val_read_reg_406) & ~(6'd20 == VideoFormat_val_read_reg_406))))))))))))))))))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state17 : begin
            if (((1'b1 == ap_CS_fsm_state17) & (grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1240_1_fu_172_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign VideoFormat_val_read_read_fu_148_p2 = VideoFormat_val;

assign add_ln1224_fu_227_p2 = (WidthInBytes_val + 14'd7);

assign add_ln1225_fu_258_p2 = (trunc_ln_reg_422 + 11'd2);

assign add_ln1247_fu_313_p2 = ($signed(trunc_ln2_fu_273_p4) + $signed(10'd1023));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign bytePlanes_read = grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1240_1_fu_172_bytePlanes_read;

assign grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1240_1_fu_172_ap_start = grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1240_1_fu_172_ap_start_reg;

assign grp_fu_243_p0 = {{add_ln1224_fu_227_p2[13:3]}};

assign grp_fu_243_p1 = 11'd3;

assign icmp_ln1229_fu_300_p2 = ((remainPix_reg_428 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln1232_fu_390_p2 = ((y_fu_144 == Height_val_read_reg_410) ? 1'b1 : 1'b0);

assign icmp_ln1247_fu_319_p2 = ((trunc_ln1226_fu_293_p1 != 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln1250_fu_325_p2 = ((trunc_ln1226_fu_293_p1 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln1271_1_fu_347_p2 = ((remainPix_1_fu_305_p3 > 4'd2) ? 1'b1 : 1'b0);

assign icmp_ln1271_2_fu_363_p2 = ((tmp_9_fu_353_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln1271_3_fu_369_p2 = ((remainPix_1_fu_305_p3 > 4'd4) ? 1'b1 : 1'b0);

assign icmp_ln1271_4_fu_375_p2 = ((remainPix_1_fu_305_p3 > 4'd5) ? 1'b1 : 1'b0);

assign icmp_ln1271_5_fu_381_p2 = ((remainPix_1_fu_305_p3 > 4'd6) ? 1'b1 : 1'b0);

assign icmp_ln1271_fu_341_p2 = ((tmp_8_fu_331_p4 != 3'd0) ? 1'b1 : 1'b0);

assign img_din = grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1240_1_fu_172_img_din;

assign img_write = grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1240_1_fu_172_img_write;

assign mul_ln1225_fu_267_p0 = mul_ln1225_fu_267_p00;

assign mul_ln1225_fu_267_p00 = add_ln1225_fu_258_p2;

assign mul_ln1225_fu_267_p1 = 23'd2731;

assign remainPix_1_fu_305_p3 = ((icmp_ln1229_fu_300_p2[0:0] == 1'b1) ? 4'd8 : zext_ln1228_fu_297_p1);

assign remainPix_fu_249_p1 = Width_val[2:0];

assign start_out = real_start;

assign tmp_8_fu_331_p4 = {{remainPix_1_fu_305_p3[3:1]}};

assign tmp_9_fu_353_p4 = {{remainPix_1_fu_305_p3[3:2]}};

assign trunc_ln1226_fu_293_p1 = grp_fu_243_p2[1:0];

assign trunc_ln2_fu_273_p4 = {{mul_ln1225_fu_267_p2[22:13]}};

assign y_2_fu_395_p2 = (y_fu_144 + 11'd1);

assign zext_ln1228_fu_297_p1 = remainPix_reg_428;

endmodule //design_1_v_frmbuf_rd_0_0_Bytes2MultiPixStream
