-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hls_hsv_2_rgb is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 4;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_stream_TVALID : IN STD_LOGIC;
    in_stream_TREADY : OUT STD_LOGIC;
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of hls_hsv_2_rgb is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "hls_hsv_2_rgb_hls_hsv_2_rgb,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=6.317000,HLS_SYN_LAT=2,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=70,HLS_SYN_LUT=629,HLS_VERSION=2025_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";

    signal ap_rst_n_inv : STD_LOGIC;
    signal in_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp1_done_reg_iter0 : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal out_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone_grp1_done_reg : BOOLEAN := false;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal s_reg_687 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal v_reg_694 : STD_LOGIC_VECTOR (7 downto 0);
    signal region_reg_702 : STD_LOGIC_VECTOR (2 downto 0);
    signal f_fu_187_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal f_reg_711 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_reg_717 : STD_LOGIC_VECTOR (1 downto 0);
    signal regslice_both_out_stream_U_apdone_blk : STD_LOGIC;
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal trunc_ln291_fu_127_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_fu_139_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_shl_fu_131_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln291_fu_147_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal h_mult_fu_151_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal lshr_ln_fu_157_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln292_fu_167_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal h_scaled_fu_171_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal xor_ln306_fu_206_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln306_fu_218_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln306_fu_218_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln306_fu_211_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln306_fu_218_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal lshr_ln1_fu_230_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln306_fu_224_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln306_2_fu_240_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln306_1_fu_244_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln308_fu_266_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln308_fu_266_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln308_fu_260_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln308_fu_266_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal lshr_ln2_fu_278_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln308_fu_272_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln308_2_fu_288_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln308_1_fu_292_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln_fu_298_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln309_fu_308_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln309_fu_318_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln309_fu_318_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln309_fu_318_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal lshr_ln3_fu_330_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln309_fu_324_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln309_1_fu_340_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln309_1_fu_344_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal xor_ln311_fu_360_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln311_fu_369_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln311_fu_369_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln311_fu_369_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal lshr_ln4_fu_381_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln311_fu_375_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln311_1_fu_391_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln311_1_fu_395_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln1_fu_401_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln312_fu_411_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln312_fu_421_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln312_fu_421_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln312_fu_421_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal lshr_ln5_fu_433_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln312_fu_427_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln312_1_fu_443_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln312_1_fu_447_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln289_fu_201_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln315_fu_463_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln289_fu_468_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln315_1_fu_480_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln315_2_fu_491_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln315_3_fu_496_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln315_fu_501_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln315_fu_474_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln315_1_fu_485_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln315_2_fu_507_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_1_0_0_s_fu_523_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_1_0_0_s_fu_523_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_1_0_0_s_fu_523_p6 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_1_0_0_s_fu_523_p9 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_1_0_0_s_fu_523_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln315_4_fu_552_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln315_1_fu_563_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln315_3_fu_546_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln315_4_fu_557_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln315_2_fu_569_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal g_1_0_0_s_fu_585_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal g_1_0_0_s_fu_585_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal g_1_0_0_s_fu_585_p8 : STD_LOGIC_VECTOR (7 downto 0);
    signal g_1_0_0_s_fu_585_p9 : STD_LOGIC_VECTOR (7 downto 0);
    signal g_1_0_0_s_fu_585_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal or_ln315_3_fu_614_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln315_5_fu_626_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln315_5_fu_608_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln315_4_fu_620_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln315_6_fu_632_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal b_1_0_0_s_fu_648_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal b_1_0_0_s_fu_648_p6 : STD_LOGIC_VECTOR (7 downto 0);
    signal b_1_0_0_s_fu_648_p8 : STD_LOGIC_VECTOR (7 downto 0);
    signal b_1_0_0_s_fu_648_p9 : STD_LOGIC_VECTOR (7 downto 0);
    signal b_1_0_0_s_fu_648_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal b_1_0_0_s_fu_648_p11 : STD_LOGIC_VECTOR (7 downto 0);
    signal g_1_0_0_s_fu_585_p11 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_1_0_0_s_fu_523_p11 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln361_7_fu_671_p5 : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to1 : STD_LOGIC;
    signal ap_reset_init_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal regslice_both_in_stream_U_apdone_blk : STD_LOGIC;
    signal in_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal in_stream_TVALID_int_regslice : STD_LOGIC;
    signal in_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_in_stream_U_ack_in : STD_LOGIC;
    signal out_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal out_stream_TVALID_int_regslice : STD_LOGIC;
    signal out_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_out_stream_U_vld_out : STD_LOGIC;
    signal mul_ln306_fu_218_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln308_fu_266_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln309_fu_318_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln311_fu_369_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln312_fu_421_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_1_0_0_s_fu_523_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal r_1_0_0_s_fu_523_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal r_1_0_0_s_fu_523_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal r_1_0_0_s_fu_523_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal g_1_0_0_s_fu_585_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal g_1_0_0_s_fu_585_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal g_1_0_0_s_fu_585_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal g_1_0_0_s_fu_585_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal b_1_0_0_s_fu_648_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal b_1_0_0_s_fu_648_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal b_1_0_0_s_fu_648_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal b_1_0_0_s_fu_648_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component hls_hsv_2_rgb_mul_8ns_8ns_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component hls_hsv_2_rgb_sparsemux_9_3_8_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (2 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (2 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (2 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (2 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (7 downto 0);
        def : IN STD_LOGIC_VECTOR (7 downto 0);
        sel : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component hls_hsv_2_rgb_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC );
    end component;


    component hls_hsv_2_rgb_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    control_s_axi_U : component hls_hsv_2_rgb_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1);

    mul_8ns_8ns_16_1_1_U1 : component hls_hsv_2_rgb_mul_8ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln306_fu_218_p0,
        din1 => mul_ln306_fu_218_p1,
        dout => mul_ln306_fu_218_p2);

    mul_8ns_8ns_16_1_1_U2 : component hls_hsv_2_rgb_mul_8ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln308_fu_266_p0,
        din1 => mul_ln308_fu_266_p1,
        dout => mul_ln308_fu_266_p2);

    mul_8ns_8ns_16_1_1_U3 : component hls_hsv_2_rgb_mul_8ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln309_fu_318_p0,
        din1 => mul_ln309_fu_318_p1,
        dout => mul_ln309_fu_318_p2);

    mul_8ns_8ns_16_1_1_U4 : component hls_hsv_2_rgb_mul_8ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln311_fu_369_p0,
        din1 => mul_ln311_fu_369_p1,
        dout => mul_ln311_fu_369_p2);

    mul_8ns_8ns_16_1_1_U5 : component hls_hsv_2_rgb_mul_8ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln312_fu_421_p0,
        din1 => mul_ln312_fu_421_p1,
        dout => mul_ln312_fu_421_p2);

    sparsemux_9_3_8_1_1_U6 : component hls_hsv_2_rgb_sparsemux_9_3_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "100",
        din0_WIDTH => 8,
        CASE1 => "010",
        din1_WIDTH => 8,
        CASE2 => "001",
        din2_WIDTH => 8,
        CASE3 => "000",
        din3_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 3,
        dout_WIDTH => 8)
    port map (
        din0 => r_1_0_0_s_fu_523_p2,
        din1 => r_1_0_0_s_fu_523_p4,
        din2 => r_1_0_0_s_fu_523_p6,
        din3 => v_reg_694,
        def => r_1_0_0_s_fu_523_p9,
        sel => r_1_0_0_s_fu_523_p10,
        dout => r_1_0_0_s_fu_523_p11);

    sparsemux_9_3_8_1_1_U7 : component hls_hsv_2_rgb_sparsemux_9_3_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "100",
        din0_WIDTH => 8,
        CASE1 => "010",
        din1_WIDTH => 8,
        CASE2 => "001",
        din2_WIDTH => 8,
        CASE3 => "000",
        din3_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 3,
        dout_WIDTH => 8)
    port map (
        din0 => g_1_0_0_s_fu_585_p2,
        din1 => g_1_0_0_s_fu_585_p4,
        din2 => v_reg_694,
        din3 => g_1_0_0_s_fu_585_p8,
        def => g_1_0_0_s_fu_585_p9,
        sel => g_1_0_0_s_fu_585_p10,
        dout => g_1_0_0_s_fu_585_p11);

    sparsemux_9_3_8_1_1_U8 : component hls_hsv_2_rgb_sparsemux_9_3_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "100",
        din0_WIDTH => 8,
        CASE1 => "010",
        din1_WIDTH => 8,
        CASE2 => "001",
        din2_WIDTH => 8,
        CASE3 => "000",
        din3_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 3,
        dout_WIDTH => 8)
    port map (
        din0 => b_1_0_0_s_fu_648_p2,
        din1 => v_reg_694,
        din2 => b_1_0_0_s_fu_648_p6,
        din3 => b_1_0_0_s_fu_648_p8,
        def => b_1_0_0_s_fu_648_p9,
        sel => b_1_0_0_s_fu_648_p10,
        dout => b_1_0_0_s_fu_648_p11);

    regslice_both_in_stream_U : component hls_hsv_2_rgb_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TDATA,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_U_ack_in,
        data_out => in_stream_TDATA_int_regslice,
        vld_out => in_stream_TVALID_int_regslice,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_U_apdone_blk);

    regslice_both_out_stream_U : component hls_hsv_2_rgb_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_stream_TDATA_int_regslice,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => out_stream_TREADY_int_regslice,
        data_out => out_stream_TDATA,
        vld_out => regslice_both_out_stream_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp1_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_block_pp0_stage0_subdone_grp1_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp1_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1)) then 
                    ap_block_pp0_stage0_subdone_grp1_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp1_done_reg_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_block_pp0_stage0_subdone_grp1_done_reg_iter0 <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp1_done_reg_iter0 <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1)) then 
                    ap_block_pp0_stage0_subdone_grp1_done_reg_iter0 <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                f_reg_711 <= f_fu_187_p1;
                region_reg_702 <= h_scaled_fu_171_p2(10 downto 8);
                s_reg_687 <= in_stream_TDATA_int_regslice(16 downto 9);
                tmp_reg_717 <= in_stream_TDATA_int_regslice(28 downto 27);
                v_reg_694 <= in_stream_TDATA_int_regslice(25 downto 18);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_init_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln306_1_fu_244_p2 <= std_logic_vector(unsigned(add_ln306_fu_224_p2) + unsigned(zext_ln306_2_fu_240_p1));
    add_ln306_fu_224_p2 <= std_logic_vector(unsigned(mul_ln306_fu_218_p2) + unsigned(ap_const_lv16_1));
    add_ln308_1_fu_292_p2 <= std_logic_vector(unsigned(add_ln308_fu_272_p2) + unsigned(zext_ln308_2_fu_288_p1));
    add_ln308_fu_272_p2 <= std_logic_vector(unsigned(mul_ln308_fu_266_p2) + unsigned(ap_const_lv16_1));
    add_ln309_1_fu_344_p2 <= std_logic_vector(unsigned(add_ln309_fu_324_p2) + unsigned(zext_ln309_1_fu_340_p1));
    add_ln309_fu_324_p2 <= std_logic_vector(unsigned(mul_ln309_fu_318_p2) + unsigned(ap_const_lv16_1));
    add_ln311_1_fu_395_p2 <= std_logic_vector(unsigned(add_ln311_fu_375_p2) + unsigned(zext_ln311_1_fu_391_p1));
    add_ln311_fu_375_p2 <= std_logic_vector(unsigned(mul_ln311_fu_369_p2) + unsigned(ap_const_lv16_1));
    add_ln312_1_fu_447_p2 <= std_logic_vector(unsigned(add_ln312_fu_427_p2) + unsigned(zext_ln312_1_fu_443_p1));
    add_ln312_fu_427_p2 <= std_logic_vector(unsigned(mul_ln312_fu_421_p2) + unsigned(ap_const_lv16_1));
    and_ln315_1_fu_485_p2 <= (xor_ln289_fu_468_p2 and icmp_ln315_1_fu_480_p2);
    and_ln315_2_fu_507_p2 <= (xor_ln289_fu_468_p2 and or_ln315_fu_501_p2);
    and_ln315_3_fu_546_p2 <= (xor_ln289_fu_468_p2 and icmp_ln315_3_fu_496_p2);
    and_ln315_4_fu_557_p2 <= (xor_ln289_fu_468_p2 and icmp_ln315_4_fu_552_p2);
    and_ln315_5_fu_608_p2 <= (xor_ln289_fu_468_p2 and icmp_ln315_2_fu_491_p2);
    and_ln315_6_fu_632_p2 <= (xor_ln289_fu_468_p2 and or_ln315_5_fu_626_p2);
    and_ln315_fu_474_p2 <= (xor_ln289_fu_468_p2 and icmp_ln315_fu_463_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_block_pp0_stage0_subdone_grp1_done_reg_iter0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_enable_reg_pp0_iter2, in_stream_TVALID_int_regslice, out_stream_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_01001_grp1 <= (((out_stream_TREADY_int_regslice = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg)) or ((out_stream_TREADY_int_regslice = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg)) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) and (ap_const_logic_1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_block_pp0_stage0_subdone_grp1_done_reg_iter0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_enable_reg_pp0_iter2, regslice_both_out_stream_U_apdone_blk, in_stream_TVALID_int_regslice, out_stream_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_11001 <= (((out_stream_TREADY_int_regslice = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg)) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) and (ap_const_logic_1 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((regslice_both_out_stream_U_apdone_blk = ap_const_logic_1) or ((out_stream_TREADY_int_regslice = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg)))));
    end process;


    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_block_pp0_stage0_subdone_grp1_done_reg_iter0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_enable_reg_pp0_iter2, in_stream_TVALID_int_regslice, out_stream_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_11001_grp1 <= (((out_stream_TREADY_int_regslice = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg)) or ((out_stream_TREADY_int_regslice = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg)) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) and (ap_const_logic_1 = ap_const_logic_1)));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_block_pp0_stage0_subdone_grp1_done_reg_iter0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_enable_reg_pp0_iter2, regslice_both_out_stream_U_apdone_blk, in_stream_TVALID_int_regslice, out_stream_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_subdone <= (((out_stream_TREADY_int_regslice = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg)) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) and (ap_const_logic_1 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((regslice_both_out_stream_U_apdone_blk = ap_const_logic_1) or ((out_stream_TREADY_int_regslice = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg)))));
    end process;


    ap_block_pp0_stage0_subdone_grp1_assign_proc : process(ap_block_pp0_stage0_subdone_grp1_done_reg_iter0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_enable_reg_pp0_iter2, in_stream_TVALID_int_regslice, out_stream_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_subdone_grp1 <= (((out_stream_TREADY_int_regslice = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg)) or ((out_stream_TREADY_int_regslice = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg)) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) and (ap_const_logic_1 = ap_const_logic_1)));
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_idle_pp0 <= ap_const_logic_0;
    ap_idle_pp0_0to1 <= ap_const_logic_0;

    ap_reset_init_pp0_assign_proc : process(ap_idle_pp0_0to1)
    begin
        if ((ap_idle_pp0_0to1 = ap_const_logic_1)) then 
            ap_reset_init_pp0 <= ap_const_logic_1;
        else 
            ap_reset_init_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    b_1_0_0_s_fu_648_p10 <= ((and_ln315_5_fu_608_p2 & or_ln315_4_fu_620_p2) & and_ln315_6_fu_632_p2);
    b_1_0_0_s_fu_648_p2 <= add_ln312_1_fu_447_p2(15 downto 8);
    b_1_0_0_s_fu_648_p6 <= add_ln306_1_fu_244_p2(15 downto 8);
    b_1_0_0_s_fu_648_p8 <= add_ln309_1_fu_344_p2(15 downto 8);
    b_1_0_0_s_fu_648_p9 <= "XXXXXXXX";
    f_fu_187_p1 <= h_scaled_fu_171_p2(8 - 1 downto 0);
    g_1_0_0_s_fu_585_p10 <= ((and_ln315_3_fu_546_p2 & and_ln315_4_fu_557_p2) & or_ln315_2_fu_569_p2);
    g_1_0_0_s_fu_585_p2 <= add_ln309_1_fu_344_p2(15 downto 8);
    g_1_0_0_s_fu_585_p4 <= add_ln312_1_fu_447_p2(15 downto 8);
    g_1_0_0_s_fu_585_p8 <= add_ln306_1_fu_244_p2(15 downto 8);
    g_1_0_0_s_fu_585_p9 <= "XXXXXXXX";
    h_mult_fu_151_p2 <= std_logic_vector(unsigned(p_shl_fu_131_p3) - unsigned(zext_ln291_fu_147_p1));
    h_scaled_fu_171_p2 <= std_logic_vector(unsigned(zext_ln292_fu_167_p1) + unsigned(h_mult_fu_151_p2));
    icmp_ln289_fu_201_p2 <= "1" when (s_reg_687 = ap_const_lv8_0) else "0";
    icmp_ln315_1_fu_480_p2 <= "1" when (region_reg_702 = ap_const_lv3_4) else "0";
    icmp_ln315_2_fu_491_p2 <= "1" when (region_reg_702 = ap_const_lv3_2) else "0";
    icmp_ln315_3_fu_496_p2 <= "1" when (region_reg_702 = ap_const_lv3_3) else "0";
    icmp_ln315_4_fu_552_p2 <= "1" when (region_reg_702 = ap_const_lv3_0) else "0";
    icmp_ln315_fu_463_p2 <= "1" when (region_reg_702 = ap_const_lv3_1) else "0";

    in_stream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_grp1, ap_block_pp0_stage0_subdone_grp1_done_reg_iter0, in_stream_TVALID_int_regslice)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream_TDATA_blk_n <= in_stream_TVALID_int_regslice;
        else 
            in_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    in_stream_TREADY <= regslice_both_in_stream_U_ack_in;

    in_stream_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone_grp1_done_reg_iter0, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream_TREADY_int_regslice <= ap_const_logic_1;
        else 
            in_stream_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    lshr_ln1_fu_230_p4 <= mul_ln306_fu_218_p2(15 downto 8);
    lshr_ln2_fu_278_p4 <= mul_ln308_fu_266_p2(15 downto 8);
    lshr_ln3_fu_330_p4 <= mul_ln309_fu_318_p2(15 downto 8);
    lshr_ln4_fu_381_p4 <= mul_ln311_fu_369_p2(15 downto 8);
    lshr_ln5_fu_433_p4 <= mul_ln312_fu_421_p2(15 downto 8);
    lshr_ln_fu_157_p4 <= h_mult_fu_151_p2(10 downto 8);
    mul_ln306_fu_218_p0 <= mul_ln306_fu_218_p00(8 - 1 downto 0);
    mul_ln306_fu_218_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xor_ln306_fu_206_p2),16));
    mul_ln306_fu_218_p1 <= zext_ln306_fu_211_p1(8 - 1 downto 0);
    mul_ln308_fu_266_p0 <= mul_ln308_fu_266_p00(8 - 1 downto 0);
    mul_ln308_fu_266_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(f_reg_711),16));
    mul_ln308_fu_266_p1 <= zext_ln308_fu_260_p1(8 - 1 downto 0);
    mul_ln309_fu_318_p0 <= mul_ln309_fu_318_p00(8 - 1 downto 0);
    mul_ln309_fu_318_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xor_ln309_fu_308_p2),16));
    mul_ln309_fu_318_p1 <= zext_ln306_fu_211_p1(8 - 1 downto 0);
    mul_ln311_fu_369_p0 <= mul_ln311_fu_369_p00(8 - 1 downto 0);
    mul_ln311_fu_369_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xor_ln311_fu_360_p2),16));
    mul_ln311_fu_369_p1 <= zext_ln308_fu_260_p1(8 - 1 downto 0);
    mul_ln312_fu_421_p0 <= mul_ln312_fu_421_p00(8 - 1 downto 0);
    mul_ln312_fu_421_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xor_ln312_fu_411_p2),16));
    mul_ln312_fu_421_p1 <= zext_ln306_fu_211_p1(8 - 1 downto 0);
    or_ln315_1_fu_563_p2 <= (icmp_ln315_fu_463_p2 or icmp_ln315_2_fu_491_p2);
    or_ln315_2_fu_569_p2 <= (or_ln315_1_fu_563_p2 or icmp_ln289_fu_201_p2);
    or_ln315_3_fu_614_p2 <= (icmp_ln315_3_fu_496_p2 or icmp_ln315_1_fu_480_p2);
    or_ln315_4_fu_620_p2 <= (or_ln315_3_fu_614_p2 or icmp_ln289_fu_201_p2);
    or_ln315_5_fu_626_p2 <= (icmp_ln315_fu_463_p2 or icmp_ln315_4_fu_552_p2);
    or_ln315_fu_501_p2 <= (icmp_ln315_3_fu_496_p2 or icmp_ln315_2_fu_491_p2);
    or_ln361_7_fu_671_p5 <= (((tmp_reg_717 & b_1_0_0_s_fu_648_p11) & g_1_0_0_s_fu_585_p11) & r_1_0_0_s_fu_523_p11);

    out_stream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_grp1, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_enable_reg_pp0_iter2, out_stream_TREADY_int_regslice)
    begin
        if ((((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            out_stream_TDATA_blk_n <= out_stream_TREADY_int_regslice;
        else 
            out_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_stream_TDATA_int_regslice <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln361_7_fu_671_p5),32));
    out_stream_TVALID <= regslice_both_out_stream_U_vld_out;

    out_stream_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            out_stream_TVALID_int_regslice <= ap_const_logic_1;
        else 
            out_stream_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    p_shl_fu_131_p3 <= (trunc_ln291_fu_127_p1 & ap_const_lv3_0);
    r_1_0_0_s_fu_523_p10 <= ((and_ln315_fu_474_p2 & and_ln315_1_fu_485_p2) & and_ln315_2_fu_507_p2);
    r_1_0_0_s_fu_523_p2 <= add_ln309_1_fu_344_p2(15 downto 8);
    r_1_0_0_s_fu_523_p4 <= add_ln312_1_fu_447_p2(15 downto 8);
    r_1_0_0_s_fu_523_p6 <= add_ln306_1_fu_244_p2(15 downto 8);
    r_1_0_0_s_fu_523_p9 <= "XXXXXXXX";
    tmp_1_fu_139_p3 <= (trunc_ln291_fu_127_p1 & ap_const_lv1_0);
    trunc_ln1_fu_401_p4 <= add_ln311_1_fu_395_p2(15 downto 8);
    trunc_ln291_fu_127_p1 <= in_stream_TDATA_int_regslice(8 - 1 downto 0);
    trunc_ln_fu_298_p4 <= add_ln308_1_fu_292_p2(15 downto 8);
    xor_ln289_fu_468_p2 <= (icmp_ln289_fu_201_p2 xor ap_const_lv1_1);
    xor_ln306_fu_206_p2 <= (s_reg_687 xor ap_const_lv8_FF);
    xor_ln309_fu_308_p2 <= (trunc_ln_fu_298_p4 xor ap_const_lv8_FF);
    xor_ln311_fu_360_p2 <= (f_reg_711 xor ap_const_lv8_FF);
    xor_ln312_fu_411_p2 <= (trunc_ln1_fu_401_p4 xor ap_const_lv8_FF);
    zext_ln291_fu_147_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_139_p3),11));
    zext_ln292_fu_167_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_fu_157_p4),11));
    zext_ln306_2_fu_240_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln1_fu_230_p4),16));
    zext_ln306_fu_211_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(v_reg_694),16));
    zext_ln308_2_fu_288_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln2_fu_278_p4),16));
    zext_ln308_fu_260_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(s_reg_687),16));
    zext_ln309_1_fu_340_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln3_fu_330_p4),16));
    zext_ln311_1_fu_391_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln4_fu_381_p4),16));
    zext_ln312_1_fu_443_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln5_fu_433_p4),16));
end behav;
