# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps8_0_99M_0/design_1_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_ps8_0_99M_0 || ORIG_REF_NAME==design_1_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_hls_passthrough_0_0/design_1_hls_passthrough_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_hls_passthrough_0_0 || ORIG_REF_NAME==design_1_hls_passthrough_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_frmbuf_rd_0_0/design_1_v_frmbuf_rd_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_v_frmbuf_rd_0_0 || ORIG_REF_NAME==design_1_v_frmbuf_rd_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_frmbuf_wr_0_0/design_1_v_frmbuf_wr_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_v_frmbuf_wr_0_0 || ORIG_REF_NAME==design_1_v_frmbuf_wr_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_1/design_1_xlconcat_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_1 || ORIG_REF_NAME==design_1_xlconcat_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_0_0/design_1_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_0_0 || ORIG_REF_NAME==design_1_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps8_0_axi_periph_upgraded_ipi_imp_xbar_0/design_1_ps8_0_axi_periph_upgraded_ipi_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps8_0_axi_periph_upgraded_ipi_imp_xbar_0 || ORIG_REF_NAME==design_1_ps8_0_axi_periph_upgraded_ipi_imp_xbar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps8_0_axi_periph_0/design_1_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps8_0_axi_periph_0 || ORIG_REF_NAME==design_1_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps8_0_axi_periph_imp_auto_ds_0/design_1_ps8_0_axi_periph_imp_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps8_0_axi_periph_imp_auto_ds_0 || ORIG_REF_NAME==design_1_ps8_0_axi_periph_imp_auto_ds_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps8_0_axi_periph_imp_auto_pc_0/design_1_ps8_0_axi_periph_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps8_0_axi_periph_imp_auto_pc_0 || ORIG_REF_NAME==design_1_ps8_0_axi_periph_imp_auto_pc_0} -quiet] -quiet

# XDC: d:/Repos/_DP/DP/Vivado/KriaTester/KriaTester.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: d:/Repos/_DP/DP/Vivado/KriaTester/KriaTester.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Repos/_DP/DP/Vivado/KriaTester/KriaTester.gen/sources_1/bd/design_1/ip/design_1_rst_ps8_0_99M_0/design_1_rst_ps8_0_99M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_ps8_0_99M_0 || ORIG_REF_NAME==design_1_rst_ps8_0_99M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Repos/_DP/DP/Vivado/KriaTester/KriaTester.gen/sources_1/bd/design_1/ip/design_1_hls_passthrough_0_0/constraints/hls_passthrough_ooc.xdc

# XDC: d:/Repos/_DP/DP/Vivado/KriaTester/KriaTester.gen/sources_1/bd/design_1/ip/design_1_v_frmbuf_rd_0_0/design_1_v_frmbuf_rd_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_v_frmbuf_rd_0_0 || ORIG_REF_NAME==design_1_v_frmbuf_rd_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Repos/_DP/DP/Vivado/KriaTester/KriaTester.gen/sources_1/bd/design_1/ip/design_1_v_frmbuf_wr_0_0/design_1_v_frmbuf_wr_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_v_frmbuf_wr_0_0 || ORIG_REF_NAME==design_1_v_frmbuf_wr_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Repos/_DP/DP/Vivado/KriaTester/KriaTester.gen/sources_1/bd/design_1/ip/design_1_ps8_0_axi_periph_imp_auto_ds_0/design_1_ps8_0_axi_periph_imp_auto_ds_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_ps8_0_axi_periph_imp_auto_ds_0 || ORIG_REF_NAME==design_1_ps8_0_axi_periph_imp_auto_ds_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Repos/_DP/DP/Vivado/KriaTester/KriaTester.gen/sources_1/bd/design_1/ip/design_1_ps8_0_axi_periph_imp_auto_ds_0/design_1_ps8_0_axi_periph_imp_auto_ds_0_ooc.xdc

# XDC: d:/Repos/_DP/DP/Vivado/KriaTester/KriaTester.gen/sources_1/bd/design_1/ip/design_1_ps8_0_axi_periph_imp_auto_pc_0/design_1_ps8_0_axi_periph_imp_auto_pc_0_ooc.xdc

# XDC: d:/Repos/_DP/DP/Vivado/KriaTester/KriaTester.gen/sources_1/bd/design_1/design_1_ooc.xdc
