// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module design_1_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_1333_13 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        img_dout,
        img_empty_n,
        img_read,
        img_num_data_valid,
        img_fifo_cap,
        bytePlanes_din,
        bytePlanes_full_n,
        bytePlanes_write,
        bytePlanes_num_data_valid,
        bytePlanes_fifo_cap,
        trunc_ln6,
        icmp_ln1353_1,
        empty,
        icmp_ln1319,
        icmp_ln1338_5,
        icmp_ln1338_4,
        icmp_ln1338_3,
        icmp23,
        icmp_ln1338_1,
        add_ln1338,
        icmp20
);

parameter    ap_ST_fsm_pp0_stage0 = 8'd1;
parameter    ap_ST_fsm_pp0_stage1 = 8'd2;
parameter    ap_ST_fsm_pp0_stage2 = 8'd4;
parameter    ap_ST_fsm_pp0_stage3 = 8'd8;
parameter    ap_ST_fsm_pp0_stage4 = 8'd16;
parameter    ap_ST_fsm_pp0_stage5 = 8'd32;
parameter    ap_ST_fsm_pp0_stage6 = 8'd64;
parameter    ap_ST_fsm_pp0_stage7 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [23:0] img_dout;
input   img_empty_n;
output   img_read;
input  [2:0] img_num_data_valid;
input  [2:0] img_fifo_cap;
output  [63:0] bytePlanes_din;
input   bytePlanes_full_n;
output   bytePlanes_write;
input  [31:0] bytePlanes_num_data_valid;
input  [31:0] bytePlanes_fifo_cap;
input  [8:0] trunc_ln6;
input  [0:0] icmp_ln1353_1;
input  [0:0] empty;
input  [0:0] icmp_ln1319;
input  [0:0] icmp_ln1338_5;
input  [0:0] icmp_ln1338_4;
input  [0:0] icmp_ln1338_3;
input  [0:0] icmp23;
input  [0:0] icmp_ln1338_1;
input  [9:0] add_ln1338;
input  [0:0] icmp20;

reg ap_idle;
reg img_read;
reg[63:0] bytePlanes_din;
reg bytePlanes_write;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln1333_reg_623;
reg   [0:0] or_ln1338_6_reg_651;
reg    ap_predicate_op116_read_state9;
reg   [0:0] or_ln1353_1_reg_659;
reg    ap_block_state9_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln1333_fu_440_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage7;
reg   [0:0] or_ln1338_5_reg_647;
reg    ap_predicate_op108_read_state8;
reg    ap_block_state8_pp0_stage7_iter0_grp7;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage7_subdone;
reg    bytePlanes_blk_n;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_grp3;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_pp0_stage6_grp6;
reg   [0:0] or_ln1353_reg_655;
wire    ap_block_pp0_stage0;
reg    img_blk_n;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_grp1;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_grp2;
reg   [0:0] or_ln1338_reg_627;
reg   [0:0] or_ln1338_1_reg_631;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4_grp4;
reg   [0:0] or_ln1338_2_reg_635;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_pp0_stage5_grp5;
reg   [0:0] or_ln1338_3_reg_639;
reg   [0:0] or_ln1338_4_reg_643;
wire    ap_block_pp0_stage7_grp7;
reg   [7:0] empty_164_reg_169;
reg   [7:0] empty_165_reg_179;
reg   [7:0] empty_166_reg_189;
reg   [7:0] empty_163_reg_221;
reg   [7:0] empty_158_reg_232;
reg   [7:0] empty_159_reg_243;
reg   [7:0] empty_160_reg_254;
reg   [7:0] empty_155_reg_265;
reg   [7:0] empty_156_reg_276;
reg   [7:0] empty_157_reg_287;
reg   [7:0] empty_153_reg_309;
reg   [7:0] empty_154_reg_320;
reg   [7:0] empty_149_reg_331;
reg   [7:0] empty_150_reg_342;
reg   [7:0] empty_151_reg_353;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] or_ln1338_fu_458_p2;
wire   [0:0] or_ln1338_1_fu_464_p2;
wire   [0:0] or_ln1338_2_fu_470_p2;
wire   [0:0] or_ln1338_3_fu_476_p2;
wire   [0:0] or_ln1338_4_fu_482_p2;
wire   [0:0] or_ln1338_5_fu_488_p2;
wire   [0:0] or_ln1338_6_fu_494_p2;
wire   [0:0] or_ln1353_fu_500_p2;
wire   [0:0] or_ln1353_1_fu_506_p2;
wire   [7:0] trunc_ln1339_fu_517_p1;
reg   [7:0] trunc_ln1339_reg_663;
reg    ap_block_state2_pp0_stage1_iter0_grp1;
reg    ap_block_pp0_stage1_11001_grp1;
reg   [7:0] trunc_ln1339_1_reg_669;
reg   [7:0] trunc_ln1339_2_reg_675;
reg   [7:0] ap_phi_mux_empty_164_phi_fu_172_p4;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_164_reg_169;
reg    ap_predicate_op63_read_state3;
reg    ap_block_state3_pp0_stage2_iter0_grp2;
reg    ap_block_pp0_stage2_11001_grp2;
reg   [7:0] ap_phi_mux_empty_165_phi_fu_182_p4;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_165_reg_179;
reg   [7:0] ap_phi_mux_empty_166_phi_fu_192_p4;
wire   [7:0] trunc_ln1339_3_fu_521_p1;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_166_reg_189;
reg   [7:0] ap_phi_mux_empty_161_phi_fu_202_p4;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_161_reg_199;
reg    ap_predicate_op71_read_state4;
reg    ap_block_state4_pp0_stage3_iter0_grp3;
reg    ap_block_pp0_stage3_11001_grp3;
reg   [7:0] ap_phi_mux_empty_162_phi_fu_213_p4;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_162_reg_210;
reg   [7:0] ap_phi_mux_empty_163_phi_fu_224_p4;
wire   [7:0] trunc_ln1339_6_fu_526_p1;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_163_reg_221;
reg   [7:0] ap_phi_mux_empty_158_phi_fu_235_p4;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_158_reg_232;
reg    ap_predicate_op81_read_state5;
reg    ap_block_state5_pp0_stage4_iter0_grp4;
reg    ap_block_pp0_stage4_11001_grp4;
reg   [7:0] ap_phi_mux_empty_159_phi_fu_246_p4;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_159_reg_243;
reg   [7:0] ap_phi_mux_empty_160_phi_fu_257_p4;
wire   [7:0] trunc_ln1339_9_fu_549_p1;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_160_reg_254;
reg   [7:0] ap_phi_mux_empty_155_phi_fu_268_p4;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_155_reg_265;
reg    ap_predicate_op89_read_state6;
reg    ap_block_state6_pp0_stage5_iter0_grp5;
reg    ap_block_pp0_stage5_11001_grp5;
reg   [7:0] ap_phi_mux_empty_156_phi_fu_279_p4;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_156_reg_276;
reg   [7:0] ap_phi_mux_empty_157_phi_fu_290_p4;
wire   [7:0] trunc_ln1339_11_fu_554_p1;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_157_reg_287;
reg   [7:0] ap_phi_mux_empty_152_phi_fu_301_p4;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_152_reg_298;
reg    ap_predicate_op97_read_state7;
reg    ap_predicate_op106_write_state7;
reg    ap_block_state7_pp0_stage6_iter0_grp6;
reg    ap_block_pp0_stage6_11001_grp6;
reg   [7:0] ap_phi_mux_empty_153_phi_fu_312_p4;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_153_reg_309;
reg   [7:0] ap_phi_mux_empty_154_phi_fu_323_p4;
wire   [7:0] trunc_ln1339_14_fu_559_p1;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_154_reg_320;
reg   [7:0] ap_phi_mux_empty_149_phi_fu_334_p4;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_149_reg_331;
reg    ap_block_pp0_stage7_11001_grp7;
reg   [7:0] ap_phi_mux_empty_150_phi_fu_345_p4;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_150_reg_342;
reg   [7:0] ap_phi_mux_empty_151_phi_fu_356_p4;
wire   [7:0] trunc_ln1339_17_fu_585_p1;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_151_reg_353;
reg   [7:0] ap_phi_mux_empty_146_phi_fu_367_p4;
reg   [7:0] ap_phi_reg_pp0_iter1_empty_146_reg_364;
wire   [7:0] ap_phi_reg_pp0_iter0_empty_146_reg_364;
wire    ap_block_pp0_stage7_11001_grp0;
reg    ap_block_pp0_stage7_subdone_grp0_done_reg;
wire    ap_block_pp0_stage7_subdone_grp0;
reg   [7:0] ap_phi_mux_empty_147_phi_fu_377_p4;
reg   [7:0] ap_phi_reg_pp0_iter1_empty_147_reg_374;
wire   [7:0] ap_phi_reg_pp0_iter0_empty_147_reg_374;
reg   [7:0] ap_phi_mux_empty_148_phi_fu_387_p4;
wire   [7:0] trunc_ln1339_20_fu_590_p1;
reg   [7:0] ap_phi_reg_pp0_iter1_empty_148_reg_384;
wire   [7:0] ap_phi_reg_pp0_iter0_empty_148_reg_384;
reg   [8:0] x_3_fu_86;
wire   [8:0] x_5_fu_446_p2;
wire    ap_loop_init;
reg   [8:0] ap_sig_allocacmp_x;
wire   [63:0] tmp_1_fu_531_p9;
reg    ap_block_pp0_stage3_01001_grp3;
wire   [63:0] tmp_3_fu_564_p9;
reg    ap_block_pp0_stage6_01001_grp6;
wire   [63:0] tmp_5_fu_595_p9;
reg    ap_block_pp0_stage0_01001;
wire   [9:0] zext_ln1333_fu_436_p1;
wire   [0:0] icmp_ln1338_fu_452_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [7:0] ap_NS_fsm;
reg    ap_block_pp0_stage1_subdone;
reg    ap_block_pp0_stage2_subdone;
reg    ap_block_pp0_stage3_subdone;
reg    ap_block_pp0_stage4_subdone;
reg    ap_block_pp0_stage5_subdone;
reg    ap_block_pp0_stage6_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_715;
reg    ap_condition_423;
reg    ap_condition_407;
reg    ap_condition_381;
reg    ap_condition_358;
reg    ap_condition_335;
reg    ap_condition_311;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_block_pp0_stage7_subdone_grp0_done_reg = 1'b0;
#0 x_3_fu_86 = 9'd0;
#0 ap_done_reg = 1'b0;
end

design_1_v_frmbuf_wr_0_0_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage7_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage7)) begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_block_pp0_stage7_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage7_subdone_grp0)) begin
                ap_block_pp0_stage7_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        if ((1'b1 == ap_condition_715)) begin
            ap_phi_reg_pp0_iter1_empty_146_reg_364 <= ap_phi_mux_empty_149_phi_fu_334_p4;
        end else if (((1'b0 == ap_block_pp0_stage7_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage7_11001_grp0))) begin
            ap_phi_reg_pp0_iter1_empty_146_reg_364 <= ap_phi_reg_pp0_iter0_empty_146_reg_364;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        if ((1'b1 == ap_condition_715)) begin
            ap_phi_reg_pp0_iter1_empty_147_reg_374 <= ap_phi_mux_empty_150_phi_fu_345_p4;
        end else if (((1'b0 == ap_block_pp0_stage7_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage7_11001_grp0))) begin
            ap_phi_reg_pp0_iter1_empty_147_reg_374 <= ap_phi_reg_pp0_iter0_empty_147_reg_374;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        if ((1'b1 == ap_condition_715)) begin
            ap_phi_reg_pp0_iter1_empty_148_reg_384 <= ap_phi_mux_empty_151_phi_fu_356_p4;
        end else if (((1'b0 == ap_block_pp0_stage7_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage7_11001_grp0))) begin
            ap_phi_reg_pp0_iter1_empty_148_reg_384 <= ap_phi_reg_pp0_iter0_empty_148_reg_384;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_423)) begin
        if (((or_ln1338_5_reg_647 == 1'd1) & (icmp_ln1333_reg_623 == 1'd1))) begin
            empty_149_reg_331 <= {{img_dout[23:16]}};
        end else if ((1'b1 == 1'b1)) begin
            empty_149_reg_331 <= ap_phi_reg_pp0_iter0_empty_149_reg_331;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_423)) begin
        if (((or_ln1338_5_reg_647 == 1'd1) & (icmp_ln1333_reg_623 == 1'd1))) begin
            empty_150_reg_342 <= {{img_dout[15:8]}};
        end else if ((1'b1 == 1'b1)) begin
            empty_150_reg_342 <= ap_phi_reg_pp0_iter0_empty_150_reg_342;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_423)) begin
        if (((or_ln1338_5_reg_647 == 1'd1) & (icmp_ln1333_reg_623 == 1'd1))) begin
            empty_151_reg_353 <= trunc_ln1339_17_fu_585_p1;
        end else if ((1'b1 == 1'b1)) begin
            empty_151_reg_353 <= ap_phi_reg_pp0_iter0_empty_151_reg_353;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_407)) begin
        if (((icmp_ln1333_reg_623 == 1'd1) & (or_ln1338_4_reg_643 == 1'd1))) begin
            empty_153_reg_309 <= {{img_dout[15:8]}};
        end else if ((1'b1 == 1'b1)) begin
            empty_153_reg_309 <= ap_phi_reg_pp0_iter0_empty_153_reg_309;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_407)) begin
        if (((icmp_ln1333_reg_623 == 1'd1) & (or_ln1338_4_reg_643 == 1'd1))) begin
            empty_154_reg_320 <= trunc_ln1339_14_fu_559_p1;
        end else if ((1'b1 == 1'b1)) begin
            empty_154_reg_320 <= ap_phi_reg_pp0_iter0_empty_154_reg_320;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_381)) begin
        if (((icmp_ln1333_reg_623 == 1'd1) & (or_ln1338_3_reg_639 == 1'd1))) begin
            empty_155_reg_265 <= {{img_dout[23:16]}};
        end else if ((1'b1 == 1'b1)) begin
            empty_155_reg_265 <= ap_phi_reg_pp0_iter0_empty_155_reg_265;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_381)) begin
        if (((icmp_ln1333_reg_623 == 1'd1) & (or_ln1338_3_reg_639 == 1'd1))) begin
            empty_156_reg_276 <= {{img_dout[15:8]}};
        end else if ((1'b1 == 1'b1)) begin
            empty_156_reg_276 <= ap_phi_reg_pp0_iter0_empty_156_reg_276;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_381)) begin
        if (((icmp_ln1333_reg_623 == 1'd1) & (or_ln1338_3_reg_639 == 1'd1))) begin
            empty_157_reg_287 <= trunc_ln1339_11_fu_554_p1;
        end else if ((1'b1 == 1'b1)) begin
            empty_157_reg_287 <= ap_phi_reg_pp0_iter0_empty_157_reg_287;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_358)) begin
        if (((icmp_ln1333_reg_623 == 1'd1) & (or_ln1338_2_reg_635 == 1'd1))) begin
            empty_158_reg_232 <= {{img_dout[23:16]}};
        end else if ((1'b1 == 1'b1)) begin
            empty_158_reg_232 <= ap_phi_reg_pp0_iter0_empty_158_reg_232;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_358)) begin
        if (((icmp_ln1333_reg_623 == 1'd1) & (or_ln1338_2_reg_635 == 1'd1))) begin
            empty_159_reg_243 <= {{img_dout[15:8]}};
        end else if ((1'b1 == 1'b1)) begin
            empty_159_reg_243 <= ap_phi_reg_pp0_iter0_empty_159_reg_243;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_358)) begin
        if (((icmp_ln1333_reg_623 == 1'd1) & (or_ln1338_2_reg_635 == 1'd1))) begin
            empty_160_reg_254 <= trunc_ln1339_9_fu_549_p1;
        end else if ((1'b1 == 1'b1)) begin
            empty_160_reg_254 <= ap_phi_reg_pp0_iter0_empty_160_reg_254;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_335)) begin
        if (((icmp_ln1333_reg_623 == 1'd1) & (or_ln1338_1_reg_631 == 1'd1))) begin
            empty_163_reg_221 <= trunc_ln1339_6_fu_526_p1;
        end else if ((1'b1 == 1'b1)) begin
            empty_163_reg_221 <= ap_phi_reg_pp0_iter0_empty_163_reg_221;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_311)) begin
        if (((icmp_ln1333_reg_623 == 1'd1) & (or_ln1338_reg_627 == 1'd1))) begin
            empty_164_reg_169 <= {{img_dout[23:16]}};
        end else if ((1'b1 == 1'b1)) begin
            empty_164_reg_169 <= ap_phi_reg_pp0_iter0_empty_164_reg_169;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_311)) begin
        if (((icmp_ln1333_reg_623 == 1'd1) & (or_ln1338_reg_627 == 1'd1))) begin
            empty_165_reg_179 <= {{img_dout[15:8]}};
        end else if ((1'b1 == 1'b1)) begin
            empty_165_reg_179 <= ap_phi_reg_pp0_iter0_empty_165_reg_179;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_311)) begin
        if (((icmp_ln1333_reg_623 == 1'd1) & (or_ln1338_reg_627 == 1'd1))) begin
            empty_166_reg_189 <= trunc_ln1339_3_fu_521_p1;
        end else if ((1'b1 == 1'b1)) begin
            empty_166_reg_189 <= ap_phi_reg_pp0_iter0_empty_166_reg_189;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln1333_fu_440_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            x_3_fu_86 <= x_5_fu_446_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_3_fu_86 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (or_ln1338_5_reg_647 == 1'd0) & (1'b0 == ap_block_pp0_stage6_11001_grp6) & (icmp_ln1333_reg_623 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        ap_phi_reg_pp0_iter0_empty_149_reg_331 <= ap_phi_mux_empty_152_phi_fu_301_p4;
        ap_phi_reg_pp0_iter0_empty_150_reg_342 <= ap_phi_mux_empty_153_phi_fu_312_p4;
        ap_phi_reg_pp0_iter0_empty_151_reg_353 <= ap_phi_mux_empty_154_phi_fu_323_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_11001_grp5) & (icmp_ln1333_reg_623 == 1'd1) & (or_ln1338_4_reg_643 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        ap_phi_reg_pp0_iter0_empty_152_reg_298 <= ap_phi_mux_empty_155_phi_fu_268_p4;
        ap_phi_reg_pp0_iter0_empty_153_reg_309 <= ap_phi_mux_empty_156_phi_fu_279_p4;
        ap_phi_reg_pp0_iter0_empty_154_reg_320 <= ap_phi_mux_empty_157_phi_fu_290_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001_grp4) & (icmp_ln1333_reg_623 == 1'd1) & (or_ln1338_3_reg_639 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_phi_reg_pp0_iter0_empty_155_reg_265 <= ap_phi_mux_empty_158_phi_fu_235_p4;
        ap_phi_reg_pp0_iter0_empty_156_reg_276 <= ap_phi_mux_empty_159_phi_fu_246_p4;
        ap_phi_reg_pp0_iter0_empty_157_reg_287 <= ap_phi_mux_empty_160_phi_fu_257_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001_grp3) & (icmp_ln1333_reg_623 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (or_ln1338_2_reg_635 == 1'd0))) begin
        ap_phi_reg_pp0_iter0_empty_158_reg_232 <= ap_phi_mux_empty_161_phi_fu_202_p4;
        ap_phi_reg_pp0_iter0_empty_159_reg_243 <= ap_phi_mux_empty_162_phi_fu_213_p4;
        ap_phi_reg_pp0_iter0_empty_160_reg_254 <= ap_phi_mux_empty_163_phi_fu_224_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001_grp2) & (icmp_ln1333_reg_623 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (or_ln1338_1_reg_631 == 1'd0))) begin
        ap_phi_reg_pp0_iter0_empty_161_reg_199 <= ap_phi_mux_empty_164_phi_fu_172_p4;
        ap_phi_reg_pp0_iter0_empty_162_reg_210 <= ap_phi_mux_empty_165_phi_fu_182_p4;
        ap_phi_reg_pp0_iter0_empty_163_reg_221 <= ap_phi_mux_empty_166_phi_fu_192_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (icmp_ln1333_reg_623 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (or_ln1338_reg_627 == 1'd0))) begin
        ap_phi_reg_pp0_iter0_empty_164_reg_169 <= {{img_dout[23:16]}};
        ap_phi_reg_pp0_iter0_empty_165_reg_179 <= {{img_dout[15:8]}};
        ap_phi_reg_pp0_iter0_empty_166_reg_189 <= trunc_ln1339_fu_517_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln1333_reg_623 <= icmp_ln1333_fu_440_p2;
        or_ln1338_1_reg_631 <= or_ln1338_1_fu_464_p2;
        or_ln1338_2_reg_635 <= or_ln1338_2_fu_470_p2;
        or_ln1338_3_reg_639 <= or_ln1338_3_fu_476_p2;
        or_ln1338_4_reg_643 <= or_ln1338_4_fu_482_p2;
        or_ln1338_5_reg_647 <= or_ln1338_5_fu_488_p2;
        or_ln1338_6_reg_651 <= or_ln1338_6_fu_494_p2;
        or_ln1338_reg_627 <= or_ln1338_fu_458_p2;
        or_ln1353_1_reg_659 <= or_ln1353_1_fu_506_p2;
        or_ln1353_reg_655 <= or_ln1353_fu_500_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        trunc_ln1339_1_reg_669 <= {{img_dout[15:8]}};
        trunc_ln1339_2_reg_675 <= {{img_dout[23:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        trunc_ln1339_reg_663 <= trunc_ln1339_fu_517_p1;
    end
end

always @ (*) begin
    if (((icmp_ln1333_fu_440_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln1338_6_reg_651 == 1'd1) & (icmp_ln1333_reg_623 == 1'd1))) begin
        ap_phi_mux_empty_146_phi_fu_367_p4 = {{img_dout[23:16]}};
    end else begin
        ap_phi_mux_empty_146_phi_fu_367_p4 = ap_phi_reg_pp0_iter1_empty_146_reg_364;
    end
end

always @ (*) begin
    if (((or_ln1338_6_reg_651 == 1'd1) & (icmp_ln1333_reg_623 == 1'd1))) begin
        ap_phi_mux_empty_147_phi_fu_377_p4 = {{img_dout[15:8]}};
    end else begin
        ap_phi_mux_empty_147_phi_fu_377_p4 = ap_phi_reg_pp0_iter1_empty_147_reg_374;
    end
end

always @ (*) begin
    if (((or_ln1338_6_reg_651 == 1'd1) & (icmp_ln1333_reg_623 == 1'd1))) begin
        ap_phi_mux_empty_148_phi_fu_387_p4 = trunc_ln1339_20_fu_590_p1;
    end else begin
        ap_phi_mux_empty_148_phi_fu_387_p4 = ap_phi_reg_pp0_iter1_empty_148_reg_384;
    end
end

always @ (*) begin
    if (((or_ln1338_5_reg_647 == 1'd1) & (icmp_ln1333_reg_623 == 1'd1))) begin
        ap_phi_mux_empty_149_phi_fu_334_p4 = {{img_dout[23:16]}};
    end else begin
        ap_phi_mux_empty_149_phi_fu_334_p4 = ap_phi_reg_pp0_iter0_empty_149_reg_331;
    end
end

always @ (*) begin
    if (((or_ln1338_5_reg_647 == 1'd1) & (icmp_ln1333_reg_623 == 1'd1))) begin
        ap_phi_mux_empty_150_phi_fu_345_p4 = {{img_dout[15:8]}};
    end else begin
        ap_phi_mux_empty_150_phi_fu_345_p4 = ap_phi_reg_pp0_iter0_empty_150_reg_342;
    end
end

always @ (*) begin
    if (((or_ln1338_5_reg_647 == 1'd1) & (icmp_ln1333_reg_623 == 1'd1))) begin
        ap_phi_mux_empty_151_phi_fu_356_p4 = trunc_ln1339_17_fu_585_p1;
    end else begin
        ap_phi_mux_empty_151_phi_fu_356_p4 = ap_phi_reg_pp0_iter0_empty_151_reg_353;
    end
end

always @ (*) begin
    if (((icmp_ln1333_reg_623 == 1'd1) & (or_ln1338_4_reg_643 == 1'd1))) begin
        ap_phi_mux_empty_152_phi_fu_301_p4 = {{img_dout[23:16]}};
    end else begin
        ap_phi_mux_empty_152_phi_fu_301_p4 = ap_phi_reg_pp0_iter0_empty_152_reg_298;
    end
end

always @ (*) begin
    if (((icmp_ln1333_reg_623 == 1'd1) & (or_ln1338_4_reg_643 == 1'd1))) begin
        ap_phi_mux_empty_153_phi_fu_312_p4 = {{img_dout[15:8]}};
    end else begin
        ap_phi_mux_empty_153_phi_fu_312_p4 = ap_phi_reg_pp0_iter0_empty_153_reg_309;
    end
end

always @ (*) begin
    if (((icmp_ln1333_reg_623 == 1'd1) & (or_ln1338_4_reg_643 == 1'd1))) begin
        ap_phi_mux_empty_154_phi_fu_323_p4 = trunc_ln1339_14_fu_559_p1;
    end else begin
        ap_phi_mux_empty_154_phi_fu_323_p4 = ap_phi_reg_pp0_iter0_empty_154_reg_320;
    end
end

always @ (*) begin
    if (((icmp_ln1333_reg_623 == 1'd1) & (or_ln1338_3_reg_639 == 1'd1))) begin
        ap_phi_mux_empty_155_phi_fu_268_p4 = {{img_dout[23:16]}};
    end else begin
        ap_phi_mux_empty_155_phi_fu_268_p4 = ap_phi_reg_pp0_iter0_empty_155_reg_265;
    end
end

always @ (*) begin
    if (((icmp_ln1333_reg_623 == 1'd1) & (or_ln1338_3_reg_639 == 1'd1))) begin
        ap_phi_mux_empty_156_phi_fu_279_p4 = {{img_dout[15:8]}};
    end else begin
        ap_phi_mux_empty_156_phi_fu_279_p4 = ap_phi_reg_pp0_iter0_empty_156_reg_276;
    end
end

always @ (*) begin
    if (((icmp_ln1333_reg_623 == 1'd1) & (or_ln1338_3_reg_639 == 1'd1))) begin
        ap_phi_mux_empty_157_phi_fu_290_p4 = trunc_ln1339_11_fu_554_p1;
    end else begin
        ap_phi_mux_empty_157_phi_fu_290_p4 = ap_phi_reg_pp0_iter0_empty_157_reg_287;
    end
end

always @ (*) begin
    if (((icmp_ln1333_reg_623 == 1'd1) & (or_ln1338_2_reg_635 == 1'd1))) begin
        ap_phi_mux_empty_158_phi_fu_235_p4 = {{img_dout[23:16]}};
    end else begin
        ap_phi_mux_empty_158_phi_fu_235_p4 = ap_phi_reg_pp0_iter0_empty_158_reg_232;
    end
end

always @ (*) begin
    if (((icmp_ln1333_reg_623 == 1'd1) & (or_ln1338_2_reg_635 == 1'd1))) begin
        ap_phi_mux_empty_159_phi_fu_246_p4 = {{img_dout[15:8]}};
    end else begin
        ap_phi_mux_empty_159_phi_fu_246_p4 = ap_phi_reg_pp0_iter0_empty_159_reg_243;
    end
end

always @ (*) begin
    if (((icmp_ln1333_reg_623 == 1'd1) & (or_ln1338_2_reg_635 == 1'd1))) begin
        ap_phi_mux_empty_160_phi_fu_257_p4 = trunc_ln1339_9_fu_549_p1;
    end else begin
        ap_phi_mux_empty_160_phi_fu_257_p4 = ap_phi_reg_pp0_iter0_empty_160_reg_254;
    end
end

always @ (*) begin
    if (((icmp_ln1333_reg_623 == 1'd1) & (or_ln1338_1_reg_631 == 1'd1))) begin
        ap_phi_mux_empty_161_phi_fu_202_p4 = {{img_dout[23:16]}};
    end else begin
        ap_phi_mux_empty_161_phi_fu_202_p4 = ap_phi_reg_pp0_iter0_empty_161_reg_199;
    end
end

always @ (*) begin
    if (((icmp_ln1333_reg_623 == 1'd1) & (or_ln1338_1_reg_631 == 1'd1))) begin
        ap_phi_mux_empty_162_phi_fu_213_p4 = {{img_dout[15:8]}};
    end else begin
        ap_phi_mux_empty_162_phi_fu_213_p4 = ap_phi_reg_pp0_iter0_empty_162_reg_210;
    end
end

always @ (*) begin
    if (((icmp_ln1333_reg_623 == 1'd1) & (or_ln1338_1_reg_631 == 1'd1))) begin
        ap_phi_mux_empty_163_phi_fu_224_p4 = trunc_ln1339_6_fu_526_p1;
    end else begin
        ap_phi_mux_empty_163_phi_fu_224_p4 = ap_phi_reg_pp0_iter0_empty_163_reg_221;
    end
end

always @ (*) begin
    if (((icmp_ln1333_reg_623 == 1'd1) & (or_ln1338_reg_627 == 1'd1))) begin
        ap_phi_mux_empty_164_phi_fu_172_p4 = {{img_dout[23:16]}};
    end else begin
        ap_phi_mux_empty_164_phi_fu_172_p4 = ap_phi_reg_pp0_iter0_empty_164_reg_169;
    end
end

always @ (*) begin
    if (((icmp_ln1333_reg_623 == 1'd1) & (or_ln1338_reg_627 == 1'd1))) begin
        ap_phi_mux_empty_165_phi_fu_182_p4 = {{img_dout[15:8]}};
    end else begin
        ap_phi_mux_empty_165_phi_fu_182_p4 = ap_phi_reg_pp0_iter0_empty_165_reg_179;
    end
end

always @ (*) begin
    if (((icmp_ln1333_reg_623 == 1'd1) & (or_ln1338_reg_627 == 1'd1))) begin
        ap_phi_mux_empty_166_phi_fu_192_p4 = trunc_ln1339_3_fu_521_p1;
    end else begin
        ap_phi_mux_empty_166_phi_fu_192_p4 = ap_phi_reg_pp0_iter0_empty_166_reg_189;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_x = 9'd0;
    end else begin
        ap_sig_allocacmp_x = x_3_fu_86;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_grp6) & (icmp_ln1333_reg_623 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (or_ln1353_reg_655 == 1'd1)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_grp3) & (icmp_ln1333_reg_623 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage0) & (or_ln1353_1_reg_659 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        bytePlanes_blk_n = bytePlanes_full_n;
    end else begin
        bytePlanes_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (or_ln1353_1_reg_659 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bytePlanes_din = tmp_5_fu_595_p9;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_01001_grp6) & (ap_predicate_op106_write_state7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        bytePlanes_din = tmp_3_fu_564_p9;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_01001_grp3) & (icmp_ln1333_reg_623 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        bytePlanes_din = tmp_1_fu_531_p9;
    end else begin
        bytePlanes_din = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_11001_grp6) & (ap_predicate_op106_write_state7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001_grp3) & (icmp_ln1333_reg_623 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage0_11001) & (or_ln1353_1_reg_659 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        bytePlanes_write = 1'b1;
    end else begin
        bytePlanes_write = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (ap_predicate_op108_read_state8 == 1'b1) & (1'b0 == ap_block_pp0_stage7_grp7) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_grp5) & (icmp_ln1333_reg_623 == 1'd1) & (or_ln1338_3_reg_639 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_grp4) & (icmp_ln1333_reg_623 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (or_ln1338_2_reg_635 == 1'd1)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_grp2) & (icmp_ln1333_reg_623 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (or_ln1338_reg_627 == 1'd1)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_grp1) & (icmp_ln1333_reg_623 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_grp6) & (icmp_ln1333_reg_623 == 1'd1) & (or_ln1338_4_reg_643 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((ap_enable_reg_pp0_iter0_reg 
    == 1'b1) & (1'b0 == ap_block_pp0_stage3_grp3) & (icmp_ln1333_reg_623 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (or_ln1338_1_reg_631 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op116_read_state9 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        img_blk_n = img_empty_n;
    end else begin
        img_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (ap_predicate_op108_read_state8 == 1'b1) & (1'b0 == ap_block_pp0_stage7_11001_grp7) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_11001_grp6) & (ap_predicate_op97_read_state7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_11001_grp5) & (ap_predicate_op89_read_state6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001_grp4) & (ap_predicate_op81_read_state5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001_grp3) & (ap_predicate_op71_read_state4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001_grp2) & (ap_predicate_op63_read_state3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001_grp1) 
    & (icmp_ln1333_reg_623 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op116_read_state9 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        img_read = 1'b1;
    end else begin
        img_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_idle_pp0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state9_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state9_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state9_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_grp1 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state2_pp0_stage1_iter0_grp1));
end

assign ap_block_pp0_stage1_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state2_pp0_stage1_iter0_grp1));
end

always @ (*) begin
    ap_block_pp0_stage2_11001_grp2 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state3_pp0_stage2_iter0_grp2));
end

assign ap_block_pp0_stage2_grp2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state3_pp0_stage2_iter0_grp2));
end

always @ (*) begin
    ap_block_pp0_stage3_01001_grp3 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state4_pp0_stage3_iter0_grp3));
end

always @ (*) begin
    ap_block_pp0_stage3_11001_grp3 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state4_pp0_stage3_iter0_grp3));
end

assign ap_block_pp0_stage3_grp3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state4_pp0_stage3_iter0_grp3));
end

always @ (*) begin
    ap_block_pp0_stage4_11001_grp4 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state5_pp0_stage4_iter0_grp4));
end

assign ap_block_pp0_stage4_grp4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage4_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state5_pp0_stage4_iter0_grp4));
end

always @ (*) begin
    ap_block_pp0_stage5_11001_grp5 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state6_pp0_stage5_iter0_grp5));
end

assign ap_block_pp0_stage5_grp5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage5_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state6_pp0_stage5_iter0_grp5));
end

always @ (*) begin
    ap_block_pp0_stage6_01001_grp6 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state7_pp0_stage6_iter0_grp6));
end

always @ (*) begin
    ap_block_pp0_stage6_11001_grp6 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state7_pp0_stage6_iter0_grp6));
end

assign ap_block_pp0_stage6_grp6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage6_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state7_pp0_stage6_iter0_grp6));
end

assign ap_block_pp0_stage7_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage7_11001_grp7 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state8_pp0_stage7_iter0_grp7));
end

assign ap_block_pp0_stage7_grp7 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage7_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state8_pp0_stage7_iter0_grp7));
end

assign ap_block_pp0_stage7_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0_grp1 = ((icmp_ln1333_reg_623 == 1'd1) & (img_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage2_iter0_grp2 = ((img_empty_n == 1'b0) & (ap_predicate_op63_read_state3 == 1'b1));
end

always @ (*) begin
    ap_block_state4_pp0_stage3_iter0_grp3 = (((icmp_ln1333_reg_623 == 1'd1) & (bytePlanes_full_n == 1'b0)) | ((img_empty_n == 1'b0) & (ap_predicate_op71_read_state4 == 1'b1)));
end

always @ (*) begin
    ap_block_state5_pp0_stage4_iter0_grp4 = ((img_empty_n == 1'b0) & (ap_predicate_op81_read_state5 == 1'b1));
end

always @ (*) begin
    ap_block_state6_pp0_stage5_iter0_grp5 = ((img_empty_n == 1'b0) & (ap_predicate_op89_read_state6 == 1'b1));
end

always @ (*) begin
    ap_block_state7_pp0_stage6_iter0_grp6 = (((bytePlanes_full_n == 1'b0) & (ap_predicate_op106_write_state7 == 1'b1)) | ((ap_predicate_op97_read_state7 == 1'b1) & (img_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state8_pp0_stage7_iter0_grp7 = ((ap_predicate_op108_read_state8 == 1'b1) & (img_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state9_pp0_stage0_iter1 = (((or_ln1353_1_reg_659 == 1'd1) & (bytePlanes_full_n == 1'b0)) | ((ap_predicate_op116_read_state9 == 1'b1) & (img_empty_n == 1'b0)));
end

always @ (*) begin
    ap_condition_311 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001_grp2) & (1'b1 == ap_CS_fsm_pp0_stage2));
end

always @ (*) begin
    ap_condition_335 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001_grp3) & (1'b1 == ap_CS_fsm_pp0_stage3));
end

always @ (*) begin
    ap_condition_358 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001_grp4) & (1'b1 == ap_CS_fsm_pp0_stage4));
end

always @ (*) begin
    ap_condition_381 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_11001_grp5) & (1'b1 == ap_CS_fsm_pp0_stage5));
end

always @ (*) begin
    ap_condition_407 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_11001_grp6) & (1'b1 == ap_CS_fsm_pp0_stage6));
end

always @ (*) begin
    ap_condition_423 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_11001_grp7) & (1'b1 == ap_CS_fsm_pp0_stage7));
end

always @ (*) begin
    ap_condition_715 = ((1'b0 == ap_block_pp0_stage7_11001_grp7) & (or_ln1338_6_reg_651 == 1'd0) & (icmp_ln1333_reg_623 == 1'd1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_empty_146_reg_364 = 'bx;

assign ap_phi_reg_pp0_iter0_empty_147_reg_374 = 'bx;

assign ap_phi_reg_pp0_iter0_empty_148_reg_384 = 'bx;

always @ (*) begin
    ap_predicate_op106_write_state7 = ((icmp_ln1333_reg_623 == 1'd1) & (or_ln1353_reg_655 == 1'd1));
end

always @ (*) begin
    ap_predicate_op108_read_state8 = ((or_ln1338_5_reg_647 == 1'd1) & (icmp_ln1333_reg_623 == 1'd1));
end

always @ (*) begin
    ap_predicate_op116_read_state9 = ((or_ln1338_6_reg_651 == 1'd1) & (icmp_ln1333_reg_623 == 1'd1));
end

always @ (*) begin
    ap_predicate_op63_read_state3 = ((icmp_ln1333_reg_623 == 1'd1) & (or_ln1338_reg_627 == 1'd1));
end

always @ (*) begin
    ap_predicate_op71_read_state4 = ((icmp_ln1333_reg_623 == 1'd1) & (or_ln1338_1_reg_631 == 1'd1));
end

always @ (*) begin
    ap_predicate_op81_read_state5 = ((icmp_ln1333_reg_623 == 1'd1) & (or_ln1338_2_reg_635 == 1'd1));
end

always @ (*) begin
    ap_predicate_op89_read_state6 = ((icmp_ln1333_reg_623 == 1'd1) & (or_ln1338_3_reg_639 == 1'd1));
end

always @ (*) begin
    ap_predicate_op97_read_state7 = ((icmp_ln1333_reg_623 == 1'd1) & (or_ln1338_4_reg_643 == 1'd1));
end

assign ap_ready = ap_ready_sig;

assign icmp_ln1333_fu_440_p2 = ((ap_sig_allocacmp_x < trunc_ln6) ? 1'b1 : 1'b0);

assign icmp_ln1338_fu_452_p2 = (($signed(zext_ln1333_fu_436_p1) < $signed(add_ln1338)) ? 1'b1 : 1'b0);

assign or_ln1338_1_fu_464_p2 = (icmp_ln1338_fu_452_p2 | icmp_ln1338_1);

assign or_ln1338_2_fu_470_p2 = (icmp_ln1338_fu_452_p2 | icmp23);

assign or_ln1338_3_fu_476_p2 = (icmp_ln1338_fu_452_p2 | icmp_ln1338_3);

assign or_ln1338_4_fu_482_p2 = (icmp_ln1338_fu_452_p2 | icmp_ln1338_4);

assign or_ln1338_5_fu_488_p2 = (icmp_ln1338_fu_452_p2 | icmp_ln1338_5);

assign or_ln1338_6_fu_494_p2 = (icmp_ln1338_fu_452_p2 | icmp_ln1319);

assign or_ln1338_fu_458_p2 = (icmp_ln1338_fu_452_p2 | icmp20);

assign or_ln1353_1_fu_506_p2 = (icmp_ln1353_1 | icmp_ln1338_fu_452_p2);

assign or_ln1353_fu_500_p2 = (icmp_ln1338_fu_452_p2 | empty);

assign tmp_1_fu_531_p9 = {{{{{{{{ap_phi_mux_empty_162_phi_fu_213_p4}, {ap_phi_mux_empty_161_phi_fu_202_p4}}, {empty_166_reg_189}}, {empty_165_reg_179}}, {empty_164_reg_169}}, {trunc_ln1339_reg_663}}, {trunc_ln1339_1_reg_669}}, {trunc_ln1339_2_reg_675}};

assign tmp_3_fu_564_p9 = {{{{{{{{ap_phi_mux_empty_152_phi_fu_301_p4}, {empty_157_reg_287}}, {empty_156_reg_276}}, {empty_155_reg_265}}, {empty_160_reg_254}}, {empty_159_reg_243}}, {empty_158_reg_232}}, {empty_163_reg_221}};

assign tmp_5_fu_595_p9 = {{{{{{{{ap_phi_mux_empty_148_phi_fu_387_p4}, {ap_phi_mux_empty_147_phi_fu_377_p4}}, {ap_phi_mux_empty_146_phi_fu_367_p4}}, {empty_151_reg_353}}, {empty_150_reg_342}}, {empty_149_reg_331}}, {empty_154_reg_320}}, {empty_153_reg_309}};

assign trunc_ln1339_11_fu_554_p1 = img_dout[7:0];

assign trunc_ln1339_14_fu_559_p1 = img_dout[7:0];

assign trunc_ln1339_17_fu_585_p1 = img_dout[7:0];

assign trunc_ln1339_20_fu_590_p1 = img_dout[7:0];

assign trunc_ln1339_3_fu_521_p1 = img_dout[7:0];

assign trunc_ln1339_6_fu_526_p1 = img_dout[7:0];

assign trunc_ln1339_9_fu_549_p1 = img_dout[7:0];

assign trunc_ln1339_fu_517_p1 = img_dout[7:0];

assign x_5_fu_446_p2 = (ap_sig_allocacmp_x + 9'd1);

assign zext_ln1333_fu_436_p1 = ap_sig_allocacmp_x;

endmodule //design_1_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_1333_13
