// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module design_1_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_739_5 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        img_dout,
        img_empty_n,
        img_read,
        img_num_data_valid,
        img_fifo_cap,
        bytePlanes_din,
        bytePlanes_full_n,
        bytePlanes_write,
        bytePlanes_num_data_valid,
        bytePlanes_fifo_cap,
        loopWidth_1,
        sext_ln735,
        rev9,
        out_pix_4_out_i,
        out_pix_4_out_o,
        out_pix_4_out_o_ap_vld
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [23:0] img_dout;
input   img_empty_n;
output   img_read;
input  [2:0] img_num_data_valid;
input  [2:0] img_fifo_cap;
output  [63:0] bytePlanes_din;
input   bytePlanes_full_n;
output   bytePlanes_write;
input  [9:0] bytePlanes_num_data_valid;
input  [9:0] bytePlanes_fifo_cap;
input  [10:0] loopWidth_1;
input  [11:0] sext_ln735;
input  [0:0] rev9;
input  [63:0] out_pix_4_out_i;
output  [63:0] out_pix_4_out_o;
output   out_pix_4_out_o_ap_vld;

reg ap_idle;
reg img_read;
reg bytePlanes_write;
reg[63:0] out_pix_4_out_o;
reg out_pix_4_out_o_ap_vld;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln739_fu_170_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_state3;
reg   [0:0] icmp_ln739_reg_268;
reg   [0:0] or_ln744_reg_277;
reg    ap_predicate_op33_read_state3;
reg    ap_block_state3_pp0_stage2_iter0;
reg    bytePlanes_blk_n;
reg    img_blk_n;
wire    ap_CS_fsm_state2;
wire   [10:0] x_2_fu_176_p2;
reg   [10:0] x_2_reg_272;
wire   [0:0] or_ln744_fu_192_p2;
wire   [7:0] trunc_ln745_fu_202_p1;
reg    ap_block_state2_pp0_stage1_iter0;
wire   [7:0] grp_fu_140_p4;
wire   [7:0] grp_fu_151_p4;
wire   [63:0] out_pix_fu_216_p4;
reg   [63:0] out_pix_reg_296;
reg   [7:0] ap_phi_mux_empty_phi_fu_116_p4;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_reg_113;
reg   [7:0] ap_phi_mux_empty_143_phi_fu_125_p4;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_143_reg_122;
reg   [7:0] ap_phi_mux_empty_144_phi_fu_134_p4;
wire   [7:0] trunc_ln745_3_fu_226_p1;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_144_reg_131;
wire   [63:0] out_pix_1_fu_241_p4;
reg   [10:0] x_fu_78;
wire    ap_loop_init;
reg   [10:0] ap_sig_allocacmp_x_1;
wire   [11:0] zext_ln741_fu_182_p1;
wire   [0:0] icmp_ln744_fu_186_p2;
wire   [23:0] in_pix_fu_206_p4;
wire   [23:0] in_pix_1_fu_231_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 x_fu_78 = 11'd0;
#0 ap_done_reg = 1'b0;
end

design_1_v_frmbuf_wr_0_0_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        x_fu_78 <= 11'd0;
    end else if (((icmp_ln739_reg_268 == 1'd0) & (1'b0 == ap_block_state3_pp0_stage2_iter0) & (1'b1 == ap_CS_fsm_state3))) begin
        x_fu_78 <= x_2_reg_272;
    end
end

always @ (posedge ap_clk) begin
    if (((or_ln744_reg_277 == 1'd0) & (1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_phi_reg_pp0_iter0_empty_143_reg_122 <= {{img_dout[15:8]}};
        ap_phi_reg_pp0_iter0_empty_144_reg_131 <= trunc_ln745_fu_202_p1;
        ap_phi_reg_pp0_iter0_empty_reg_113 <= {{img_dout[23:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        icmp_ln739_reg_268 <= icmp_ln739_fu_170_p2;
        or_ln744_reg_277 <= or_ln744_fu_192_p2;
        x_2_reg_272 <= x_2_fu_176_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2))) begin
        out_pix_reg_296 <= out_pix_fu_216_p4;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_pp0_stage1_iter0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state3_pp0_stage2_iter0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln739_fu_170_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln744_reg_277 == 1'd1) & (icmp_ln739_reg_268 == 1'd0))) begin
        ap_phi_mux_empty_143_phi_fu_125_p4 = {{img_dout[15:8]}};
    end else begin
        ap_phi_mux_empty_143_phi_fu_125_p4 = ap_phi_reg_pp0_iter0_empty_143_reg_122;
    end
end

always @ (*) begin
    if (((or_ln744_reg_277 == 1'd1) & (icmp_ln739_reg_268 == 1'd0))) begin
        ap_phi_mux_empty_144_phi_fu_134_p4 = trunc_ln745_3_fu_226_p1;
    end else begin
        ap_phi_mux_empty_144_phi_fu_134_p4 = ap_phi_reg_pp0_iter0_empty_144_reg_131;
    end
end

always @ (*) begin
    if (((or_ln744_reg_277 == 1'd1) & (icmp_ln739_reg_268 == 1'd0))) begin
        ap_phi_mux_empty_phi_fu_116_p4 = {{img_dout[23:16]}};
    end else begin
        ap_phi_mux_empty_phi_fu_116_p4 = ap_phi_reg_pp0_iter0_empty_reg_113;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3_pp0_stage2_iter0) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_x_1 = 11'd0;
    end else begin
        ap_sig_allocacmp_x_1 = x_fu_78;
    end
end

always @ (*) begin
    if (((icmp_ln739_reg_268 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        bytePlanes_blk_n = bytePlanes_full_n;
    end else begin
        bytePlanes_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln739_reg_268 == 1'd0) & (1'b0 == ap_block_state3_pp0_stage2_iter0) & (1'b1 == ap_CS_fsm_state3))) begin
        bytePlanes_write = 1'b1;
    end else begin
        bytePlanes_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((ap_predicate_op33_read_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3)))) begin
        img_blk_n = img_empty_n;
    end else begin
        img_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2)) | ((ap_predicate_op33_read_state3 == 1'b1) & (1'b0 == ap_block_state3_pp0_stage2_iter0) & (1'b1 == ap_CS_fsm_state3)))) begin
        img_read = 1'b1;
    end else begin
        img_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln739_reg_268 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        out_pix_4_out_o = out_pix_1_fu_241_p4;
    end else begin
        out_pix_4_out_o = out_pix_4_out_i;
    end
end

always @ (*) begin
    if (((icmp_ln739_reg_268 == 1'd0) & (1'b0 == ap_block_state3_pp0_stage2_iter0) & (1'b1 == ap_CS_fsm_state3))) begin
        out_pix_4_out_o_ap_vld = 1'b1;
    end else begin
        out_pix_4_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((icmp_ln739_fu_170_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b0 == ap_block_state3_pp0_stage2_iter0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0 = (img_empty_n == 1'b0);
end

always @ (*) begin
    ap_block_state3_pp0_stage2_iter0 = (((bytePlanes_full_n == 1'b0) & (icmp_ln739_reg_268 == 1'd0)) | ((ap_predicate_op33_read_state3 == 1'b1) & (img_empty_n == 1'b0)));
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

always @ (*) begin
    ap_predicate_op33_read_state3 = ((or_ln744_reg_277 == 1'd1) & (icmp_ln739_reg_268 == 1'd0));
end

assign ap_ready = ap_ready_sig;

assign bytePlanes_din = {{out_pix_reg_296[63:56]}, {in_pix_1_fu_231_p4}, {out_pix_reg_296[31:0]}};

assign grp_fu_140_p4 = {{img_dout[15:8]}};

assign grp_fu_151_p4 = {{img_dout[23:16]}};

assign icmp_ln739_fu_170_p2 = ((ap_sig_allocacmp_x_1 == loopWidth_1) ? 1'b1 : 1'b0);

assign icmp_ln744_fu_186_p2 = (($signed(zext_ln741_fu_182_p1) < $signed(sext_ln735)) ? 1'b1 : 1'b0);

assign in_pix_1_fu_231_p4 = {{{ap_phi_mux_empty_144_phi_fu_134_p4}, {ap_phi_mux_empty_143_phi_fu_125_p4}}, {ap_phi_mux_empty_phi_fu_116_p4}};

assign in_pix_fu_206_p4 = {{{trunc_ln745_fu_202_p1}, {grp_fu_140_p4}}, {grp_fu_151_p4}};

assign or_ln744_fu_192_p2 = (rev9 | icmp_ln744_fu_186_p2);

assign out_pix_1_fu_241_p4 = {{out_pix_reg_296[63:56]}, {in_pix_1_fu_231_p4}, {out_pix_reg_296[31:0]}};

assign out_pix_fu_216_p4 = {{out_pix_4_out_i[63:24]}, {in_pix_fu_206_p4}};

assign trunc_ln745_3_fu_226_p1 = img_dout[7:0];

assign trunc_ln745_fu_202_p1 = img_dout[7:0];

assign x_2_fu_176_p2 = (ap_sig_allocacmp_x_1 + 11'd1);

assign zext_ln741_fu_182_p1 = ap_sig_allocacmp_x_1;

endmodule //design_1_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_739_5
