-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity design_1_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_1090_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    img_dout : IN STD_LOGIC_VECTOR (23 downto 0);
    img_empty_n : IN STD_LOGIC;
    img_read : OUT STD_LOGIC;
    img_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    img_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    bytePlanes_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    bytePlanes_full_n : IN STD_LOGIC;
    bytePlanes_write : OUT STD_LOGIC;
    bytePlanes_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    bytePlanes_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    trunc_ln1 : IN STD_LOGIC_VECTOR (8 downto 0);
    icmp_ln1110_1 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty : IN STD_LOGIC_VECTOR (0 downto 0);
    icmp_ln1077 : IN STD_LOGIC_VECTOR (0 downto 0);
    icmp_ln1095_5 : IN STD_LOGIC_VECTOR (0 downto 0);
    icmp_ln1095_4 : IN STD_LOGIC_VECTOR (0 downto 0);
    icmp_ln1095_3 : IN STD_LOGIC_VECTOR (0 downto 0);
    icmp9 : IN STD_LOGIC_VECTOR (0 downto 0);
    icmp_ln1095_1 : IN STD_LOGIC_VECTOR (0 downto 0);
    add_ln1095 : IN STD_LOGIC_VECTOR (9 downto 0);
    icmp6 : IN STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of design_1_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_1090_1 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_pp0_stage4 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_pp0_stage5 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_pp0_stage6 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_pp0_stage7 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln1090_reg_617 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1095_6_reg_645 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op115_read_state9 : BOOLEAN;
    signal or_ln1110_1_reg_653 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state9_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln1090_fu_440_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage7 : signal is "none";
    signal or_ln1095_5_reg_641 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op107_read_state8 : BOOLEAN;
    signal ap_block_state8_pp0_stage7_iter0_grp7 : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage7_subdone : BOOLEAN;
    signal bytePlanes_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal ap_block_pp0_stage3_grp3 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage6 : signal is "none";
    signal ap_block_pp0_stage6_grp6 : BOOLEAN;
    signal or_ln1110_reg_649 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal img_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_grp1 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_grp2 : BOOLEAN;
    signal or_ln1095_reg_621 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1095_1_reg_625 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage4 : signal is "none";
    signal ap_block_pp0_stage4_grp4 : BOOLEAN;
    signal or_ln1095_2_reg_629 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage5 : signal is "none";
    signal ap_block_pp0_stage5_grp5 : BOOLEAN;
    signal or_ln1095_3_reg_633 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1095_4_reg_637 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage7_grp7 : BOOLEAN;
    signal empty_149_reg_171 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_150_reg_181 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_146_reg_200 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_143_reg_232 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_144_reg_243 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_145_reg_254 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_140_reg_265 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_141_reg_276 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_142_reg_287 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_137_reg_298 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_138_reg_309 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_134_reg_331 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_135_reg_342 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_136_reg_353 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal or_ln1095_fu_458_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1095_1_fu_464_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1095_2_fu_470_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1095_3_fu_476_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1095_4_fu_482_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1095_5_fu_488_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1095_6_fu_494_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1110_fu_500_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1110_1_fu_506_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal img_read_reg_657 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_block_state2_pp0_stage1_iter0_grp1 : BOOLEAN;
    signal ap_block_pp0_stage1_11001_grp1 : BOOLEAN;
    signal ap_predicate_op62_read_state3 : BOOLEAN;
    signal ap_block_state3_pp0_stage2_iter0_grp2 : BOOLEAN;
    signal ap_block_pp0_stage2_11001_grp2 : BOOLEAN;
    signal ap_phi_mux_empty_149_phi_fu_174_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_empty_149_reg_171 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_empty_150_phi_fu_184_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_empty_150_reg_181 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_phi_ln1096_reg_191 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_predicate_op70_read_state4 : BOOLEAN;
    signal ap_block_state4_pp0_stage3_iter0_grp3 : BOOLEAN;
    signal ap_block_pp0_stage3_11001_grp3 : BOOLEAN;
    signal ap_phi_mux_empty_146_phi_fu_203_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_empty_146_reg_200 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_empty_147_phi_fu_214_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_empty_147_reg_211 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_empty_148_phi_fu_225_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln1096_3_fu_522_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_empty_148_reg_222 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln1096_fu_517_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_empty_143_phi_fu_235_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_empty_143_reg_232 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_predicate_op80_read_state5 : BOOLEAN;
    signal ap_block_state5_pp0_stage4_iter0_grp4 : BOOLEAN;
    signal ap_block_pp0_stage4_11001_grp4 : BOOLEAN;
    signal ap_phi_mux_empty_144_phi_fu_246_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_empty_144_reg_243 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_empty_145_phi_fu_257_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln1096_6_fu_543_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_empty_145_reg_254 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_empty_140_phi_fu_268_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_empty_140_reg_265 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_predicate_op88_read_state6 : BOOLEAN;
    signal ap_block_state6_pp0_stage5_iter0_grp5 : BOOLEAN;
    signal ap_block_pp0_stage5_11001_grp5 : BOOLEAN;
    signal ap_phi_mux_empty_141_phi_fu_279_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_empty_141_reg_276 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_empty_142_phi_fu_290_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln1096_10_fu_548_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_empty_142_reg_287 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_empty_137_phi_fu_301_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_empty_137_reg_298 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_predicate_op96_read_state7 : BOOLEAN;
    signal ap_predicate_op105_write_state7 : BOOLEAN;
    signal ap_block_state7_pp0_stage6_iter0_grp6 : BOOLEAN;
    signal ap_block_pp0_stage6_11001_grp6 : BOOLEAN;
    signal ap_phi_mux_empty_138_phi_fu_312_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_empty_138_reg_309 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_empty_139_phi_fu_323_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln1096_13_fu_553_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_empty_139_reg_320 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_empty_134_phi_fu_334_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_empty_134_reg_331 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage7_11001_grp7 : BOOLEAN;
    signal ap_phi_mux_empty_135_phi_fu_345_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_empty_135_reg_342 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_empty_136_phi_fu_356_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln1096_16_fu_579_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_empty_136_reg_353 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_empty_131_phi_fu_367_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_empty_131_reg_364 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_empty_131_reg_364 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage7_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage7_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage7_subdone_grp0 : BOOLEAN;
    signal ap_phi_mux_empty_132_phi_fu_377_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_empty_132_reg_374 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_empty_132_reg_374 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_empty_133_phi_fu_387_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln1096_19_fu_584_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_empty_133_reg_384 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_empty_133_reg_384 : STD_LOGIC_VECTOR (7 downto 0);
    signal x_fu_88 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal x_2_fu_446_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_x_1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_s_fu_527_p7 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage3_01001_grp3 : BOOLEAN;
    signal tmp_1_fu_558_p9 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage6_01001_grp6 : BOOLEAN;
    signal tmp_2_fu_589_p9 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal zext_ln1090_fu_436_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln1095_fu_452_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal ap_block_pp0_stage4_subdone : BOOLEAN;
    signal ap_block_pp0_stage5_subdone : BOOLEAN;
    signal ap_block_pp0_stage6_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_710 : BOOLEAN;
    signal ap_condition_425 : BOOLEAN;
    signal ap_condition_409 : BOOLEAN;
    signal ap_condition_383 : BOOLEAN;
    signal ap_condition_360 : BOOLEAN;
    signal ap_condition_332 : BOOLEAN;
    signal ap_condition_306 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component design_1_v_frmbuf_wr_0_0_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component design_1_v_frmbuf_wr_0_0_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage7_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage7_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage7)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage7_subdone)) then 
                        ap_block_pp0_stage7_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage7_subdone_grp0)) then 
                        ap_block_pp0_stage7_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage7_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter1_empty_131_reg_364_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then
                if ((ap_const_boolean_1 = ap_condition_710)) then 
                    ap_phi_reg_pp0_iter1_empty_131_reg_364 <= ap_phi_mux_empty_134_phi_fu_334_p4;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage7_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage7_11001_grp0))) then 
                    ap_phi_reg_pp0_iter1_empty_131_reg_364 <= ap_phi_reg_pp0_iter0_empty_131_reg_364;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_empty_132_reg_374_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then
                if ((ap_const_boolean_1 = ap_condition_710)) then 
                    ap_phi_reg_pp0_iter1_empty_132_reg_374 <= ap_phi_mux_empty_135_phi_fu_345_p4;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage7_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage7_11001_grp0))) then 
                    ap_phi_reg_pp0_iter1_empty_132_reg_374 <= ap_phi_reg_pp0_iter0_empty_132_reg_374;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_empty_133_reg_384_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then
                if ((ap_const_boolean_1 = ap_condition_710)) then 
                    ap_phi_reg_pp0_iter1_empty_133_reg_384 <= ap_phi_mux_empty_136_phi_fu_356_p4;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage7_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage7_11001_grp0))) then 
                    ap_phi_reg_pp0_iter1_empty_133_reg_384 <= ap_phi_reg_pp0_iter0_empty_133_reg_384;
                end if;
            end if; 
        end if;
    end process;

    empty_134_reg_331_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_425)) then
                if (((or_ln1095_5_reg_641 = ap_const_lv1_1) and (icmp_ln1090_reg_617 = ap_const_lv1_1))) then 
                    empty_134_reg_331 <= img_dout(23 downto 16);
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    empty_134_reg_331 <= ap_phi_reg_pp0_iter0_empty_134_reg_331;
                end if;
            end if; 
        end if;
    end process;

    empty_135_reg_342_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_425)) then
                if (((or_ln1095_5_reg_641 = ap_const_lv1_1) and (icmp_ln1090_reg_617 = ap_const_lv1_1))) then 
                    empty_135_reg_342 <= img_dout(15 downto 8);
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    empty_135_reg_342 <= ap_phi_reg_pp0_iter0_empty_135_reg_342;
                end if;
            end if; 
        end if;
    end process;

    empty_136_reg_353_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_425)) then
                if (((or_ln1095_5_reg_641 = ap_const_lv1_1) and (icmp_ln1090_reg_617 = ap_const_lv1_1))) then 
                    empty_136_reg_353 <= trunc_ln1096_16_fu_579_p1;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    empty_136_reg_353 <= ap_phi_reg_pp0_iter0_empty_136_reg_353;
                end if;
            end if; 
        end if;
    end process;

    empty_137_reg_298_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_409)) then
                if (((icmp_ln1090_reg_617 = ap_const_lv1_1) and (or_ln1095_4_reg_637 = ap_const_lv1_1))) then 
                    empty_137_reg_298 <= img_dout(23 downto 16);
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    empty_137_reg_298 <= ap_phi_reg_pp0_iter0_empty_137_reg_298;
                end if;
            end if; 
        end if;
    end process;

    empty_138_reg_309_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_409)) then
                if (((icmp_ln1090_reg_617 = ap_const_lv1_1) and (or_ln1095_4_reg_637 = ap_const_lv1_1))) then 
                    empty_138_reg_309 <= img_dout(15 downto 8);
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    empty_138_reg_309 <= ap_phi_reg_pp0_iter0_empty_138_reg_309;
                end if;
            end if; 
        end if;
    end process;

    empty_140_reg_265_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_383)) then
                if (((icmp_ln1090_reg_617 = ap_const_lv1_1) and (or_ln1095_3_reg_633 = ap_const_lv1_1))) then 
                    empty_140_reg_265 <= img_dout(23 downto 16);
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    empty_140_reg_265 <= ap_phi_reg_pp0_iter0_empty_140_reg_265;
                end if;
            end if; 
        end if;
    end process;

    empty_141_reg_276_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_383)) then
                if (((icmp_ln1090_reg_617 = ap_const_lv1_1) and (or_ln1095_3_reg_633 = ap_const_lv1_1))) then 
                    empty_141_reg_276 <= img_dout(15 downto 8);
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    empty_141_reg_276 <= ap_phi_reg_pp0_iter0_empty_141_reg_276;
                end if;
            end if; 
        end if;
    end process;

    empty_142_reg_287_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_383)) then
                if (((icmp_ln1090_reg_617 = ap_const_lv1_1) and (or_ln1095_3_reg_633 = ap_const_lv1_1))) then 
                    empty_142_reg_287 <= trunc_ln1096_10_fu_548_p1;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    empty_142_reg_287 <= ap_phi_reg_pp0_iter0_empty_142_reg_287;
                end if;
            end if; 
        end if;
    end process;

    empty_143_reg_232_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_360)) then
                if (((icmp_ln1090_reg_617 = ap_const_lv1_1) and (or_ln1095_2_reg_629 = ap_const_lv1_1))) then 
                    empty_143_reg_232 <= img_dout(23 downto 16);
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    empty_143_reg_232 <= ap_phi_reg_pp0_iter0_empty_143_reg_232;
                end if;
            end if; 
        end if;
    end process;

    empty_144_reg_243_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_360)) then
                if (((icmp_ln1090_reg_617 = ap_const_lv1_1) and (or_ln1095_2_reg_629 = ap_const_lv1_1))) then 
                    empty_144_reg_243 <= img_dout(15 downto 8);
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    empty_144_reg_243 <= ap_phi_reg_pp0_iter0_empty_144_reg_243;
                end if;
            end if; 
        end if;
    end process;

    empty_145_reg_254_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_360)) then
                if (((icmp_ln1090_reg_617 = ap_const_lv1_1) and (or_ln1095_2_reg_629 = ap_const_lv1_1))) then 
                    empty_145_reg_254 <= trunc_ln1096_6_fu_543_p1;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    empty_145_reg_254 <= ap_phi_reg_pp0_iter0_empty_145_reg_254;
                end if;
            end if; 
        end if;
    end process;

    empty_146_reg_200_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_332)) then
                if (((icmp_ln1090_reg_617 = ap_const_lv1_1) and (or_ln1095_1_reg_625 = ap_const_lv1_1))) then 
                    empty_146_reg_200 <= img_dout(23 downto 16);
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    empty_146_reg_200 <= ap_phi_reg_pp0_iter0_empty_146_reg_200;
                end if;
            end if; 
        end if;
    end process;

    empty_149_reg_171_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_306)) then
                if (((icmp_ln1090_reg_617 = ap_const_lv1_1) and (or_ln1095_reg_621 = ap_const_lv1_1))) then 
                    empty_149_reg_171 <= img_dout(23 downto 16);
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    empty_149_reg_171 <= ap_phi_reg_pp0_iter0_empty_149_reg_171;
                end if;
            end if; 
        end if;
    end process;

    empty_150_reg_181_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_306)) then
                if (((icmp_ln1090_reg_617 = ap_const_lv1_1) and (or_ln1095_reg_621 = ap_const_lv1_1))) then 
                    empty_150_reg_181 <= img_dout(15 downto 8);
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    empty_150_reg_181 <= ap_phi_reg_pp0_iter0_empty_150_reg_181;
                end if;
            end if; 
        end if;
    end process;

    x_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln1090_fu_440_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    x_fu_88 <= x_2_fu_446_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    x_fu_88 <= ap_const_lv9_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (or_ln1095_5_reg_641 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage6_11001_grp6) and (icmp_ln1090_reg_617 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6))) then
                ap_phi_reg_pp0_iter0_empty_134_reg_331 <= ap_phi_mux_empty_137_phi_fu_301_p4;
                ap_phi_reg_pp0_iter0_empty_135_reg_342 <= ap_phi_mux_empty_138_phi_fu_312_p4;
                ap_phi_reg_pp0_iter0_empty_136_reg_353 <= ap_phi_mux_empty_139_phi_fu_323_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage5_11001_grp5) and (icmp_ln1090_reg_617 = ap_const_lv1_1) and (or_ln1095_4_reg_637 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then
                ap_phi_reg_pp0_iter0_empty_137_reg_298 <= ap_phi_mux_empty_140_phi_fu_268_p4;
                ap_phi_reg_pp0_iter0_empty_138_reg_309 <= ap_phi_mux_empty_141_phi_fu_279_p4;
                ap_phi_reg_pp0_iter0_empty_139_reg_320 <= ap_phi_mux_empty_142_phi_fu_290_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001_grp4) and (icmp_ln1090_reg_617 = ap_const_lv1_1) and (or_ln1095_3_reg_633 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then
                ap_phi_reg_pp0_iter0_empty_140_reg_265 <= ap_phi_mux_empty_143_phi_fu_235_p4;
                ap_phi_reg_pp0_iter0_empty_141_reg_276 <= ap_phi_mux_empty_144_phi_fu_246_p4;
                ap_phi_reg_pp0_iter0_empty_142_reg_287 <= ap_phi_mux_empty_145_phi_fu_257_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001_grp3) and (icmp_ln1090_reg_617 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (or_ln1095_2_reg_629 = ap_const_lv1_0))) then
                ap_phi_reg_pp0_iter0_empty_143_reg_232 <= ap_phi_mux_empty_146_phi_fu_203_p4;
                ap_phi_reg_pp0_iter0_empty_144_reg_243 <= ap_phi_mux_empty_147_phi_fu_214_p4;
                ap_phi_reg_pp0_iter0_empty_145_reg_254 <= ap_phi_mux_empty_148_phi_fu_225_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp2) and (icmp_ln1090_reg_617 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (or_ln1095_1_reg_625 = ap_const_lv1_0))) then
                ap_phi_reg_pp0_iter0_empty_146_reg_200 <= ap_phi_mux_empty_149_phi_fu_174_p4;
                ap_phi_reg_pp0_iter0_empty_147_reg_211 <= ap_phi_mux_empty_150_phi_fu_184_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp1) and (icmp_ln1090_reg_617 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (or_ln1095_reg_621 = ap_const_lv1_0))) then
                ap_phi_reg_pp0_iter0_empty_149_reg_171 <= img_dout(23 downto 16);
                ap_phi_reg_pp0_iter0_empty_150_reg_181 <= img_dout(15 downto 8);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp2) and (icmp_ln1090_reg_617 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (or_ln1095_reg_621 = ap_const_lv1_1)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp1) and (icmp_ln1090_reg_617 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (or_ln1095_reg_621 = ap_const_lv1_0)))) then
                ap_phi_reg_pp0_iter0_phi_ln1096_reg_191 <= img_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln1090_reg_617 <= icmp_ln1090_fu_440_p2;
                or_ln1095_1_reg_625 <= or_ln1095_1_fu_464_p2;
                or_ln1095_2_reg_629 <= or_ln1095_2_fu_470_p2;
                or_ln1095_3_reg_633 <= or_ln1095_3_fu_476_p2;
                or_ln1095_4_reg_637 <= or_ln1095_4_fu_482_p2;
                or_ln1095_5_reg_641 <= or_ln1095_5_fu_488_p2;
                or_ln1095_6_reg_645 <= or_ln1095_6_fu_494_p2;
                or_ln1095_reg_621 <= or_ln1095_fu_458_p2;
                or_ln1110_1_reg_653 <= or_ln1110_1_fu_506_p2;
                or_ln1110_reg_649 <= or_ln1110_fu_500_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                img_read_reg_657 <= img_dout;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_idle_pp0, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter0_stage0, ap_block_pp0_stage7_subdone, ap_block_pp0_stage1_subdone, ap_block_pp0_stage2_subdone, ap_block_pp0_stage3_subdone, ap_block_pp0_stage4_subdone, ap_block_pp0_stage5_subdone, ap_block_pp0_stage6_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_idle_pp0 = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when ap_ST_fsm_pp0_stage4 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage4_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                end if;
            when ap_ST_fsm_pp0_stage5 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage5_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                end if;
            when ap_ST_fsm_pp0_stage6 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage6_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage7;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage6;
                end if;
            when ap_ST_fsm_pp0_stage7 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage7_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage7;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
    ap_CS_fsm_pp0_stage4 <= ap_CS_fsm(4);
    ap_CS_fsm_pp0_stage5 <= ap_CS_fsm(5);
    ap_CS_fsm_pp0_stage6 <= ap_CS_fsm(6);
    ap_CS_fsm_pp0_stage7 <= ap_CS_fsm(7);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state9_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state9_pp0_stage0_iter1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state9_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state9_pp0_stage0_iter1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state9_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state9_pp0_stage0_iter1));
    end process;


    ap_block_pp0_stage1_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state2_pp0_stage1_iter0_grp1)
    begin
                ap_block_pp0_stage1_11001_grp1 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0_grp1));
    end process;

        ap_block_pp0_stage1_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state2_pp0_stage1_iter0_grp1)
    begin
                ap_block_pp0_stage1_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0_grp1));
    end process;


    ap_block_pp0_stage2_11001_grp2_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state3_pp0_stage2_iter0_grp2)
    begin
                ap_block_pp0_stage2_11001_grp2 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage2_iter0_grp2));
    end process;

        ap_block_pp0_stage2_grp2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state3_pp0_stage2_iter0_grp2)
    begin
                ap_block_pp0_stage2_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage2_iter0_grp2));
    end process;


    ap_block_pp0_stage3_01001_grp3_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state4_pp0_stage3_iter0_grp3)
    begin
                ap_block_pp0_stage3_01001_grp3 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage3_iter0_grp3));
    end process;


    ap_block_pp0_stage3_11001_grp3_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state4_pp0_stage3_iter0_grp3)
    begin
                ap_block_pp0_stage3_11001_grp3 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage3_iter0_grp3));
    end process;

        ap_block_pp0_stage3_grp3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage3_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state4_pp0_stage3_iter0_grp3)
    begin
                ap_block_pp0_stage3_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage3_iter0_grp3));
    end process;


    ap_block_pp0_stage4_11001_grp4_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state5_pp0_stage4_iter0_grp4)
    begin
                ap_block_pp0_stage4_11001_grp4 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_pp0_stage4_iter0_grp4));
    end process;

        ap_block_pp0_stage4_grp4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage4_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state5_pp0_stage4_iter0_grp4)
    begin
                ap_block_pp0_stage4_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_pp0_stage4_iter0_grp4));
    end process;


    ap_block_pp0_stage5_11001_grp5_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state6_pp0_stage5_iter0_grp5)
    begin
                ap_block_pp0_stage5_11001_grp5 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state6_pp0_stage5_iter0_grp5));
    end process;

        ap_block_pp0_stage5_grp5 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage5_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state6_pp0_stage5_iter0_grp5)
    begin
                ap_block_pp0_stage5_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state6_pp0_stage5_iter0_grp5));
    end process;


    ap_block_pp0_stage6_01001_grp6_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state7_pp0_stage6_iter0_grp6)
    begin
                ap_block_pp0_stage6_01001_grp6 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_pp0_stage6_iter0_grp6));
    end process;


    ap_block_pp0_stage6_11001_grp6_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state7_pp0_stage6_iter0_grp6)
    begin
                ap_block_pp0_stage6_11001_grp6 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_pp0_stage6_iter0_grp6));
    end process;

        ap_block_pp0_stage6_grp6 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage6_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state7_pp0_stage6_iter0_grp6)
    begin
                ap_block_pp0_stage6_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_pp0_stage6_iter0_grp6));
    end process;

        ap_block_pp0_stage7_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage7_11001_grp7_assign_proc : process(ap_block_state8_pp0_stage7_iter0_grp7, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage7_11001_grp7 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state8_pp0_stage7_iter0_grp7));
    end process;

        ap_block_pp0_stage7_grp7 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage7_subdone_assign_proc : process(ap_block_state8_pp0_stage7_iter0_grp7, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage7_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state8_pp0_stage7_iter0_grp7));
    end process;

        ap_block_pp0_stage7_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage1_iter0_grp1_assign_proc : process(img_empty_n, icmp_ln1090_reg_617)
    begin
                ap_block_state2_pp0_stage1_iter0_grp1 <= ((icmp_ln1090_reg_617 = ap_const_lv1_1) and (img_empty_n = ap_const_logic_0));
    end process;


    ap_block_state3_pp0_stage2_iter0_grp2_assign_proc : process(img_empty_n, ap_predicate_op62_read_state3)
    begin
                ap_block_state3_pp0_stage2_iter0_grp2 <= ((img_empty_n = ap_const_logic_0) and (ap_predicate_op62_read_state3 = ap_const_boolean_1));
    end process;


    ap_block_state4_pp0_stage3_iter0_grp3_assign_proc : process(img_empty_n, bytePlanes_full_n, icmp_ln1090_reg_617, ap_predicate_op70_read_state4)
    begin
                ap_block_state4_pp0_stage3_iter0_grp3 <= (((icmp_ln1090_reg_617 = ap_const_lv1_1) and (bytePlanes_full_n = ap_const_logic_0)) or ((img_empty_n = ap_const_logic_0) and (ap_predicate_op70_read_state4 = ap_const_boolean_1)));
    end process;


    ap_block_state5_pp0_stage4_iter0_grp4_assign_proc : process(img_empty_n, ap_predicate_op80_read_state5)
    begin
                ap_block_state5_pp0_stage4_iter0_grp4 <= ((img_empty_n = ap_const_logic_0) and (ap_predicate_op80_read_state5 = ap_const_boolean_1));
    end process;


    ap_block_state6_pp0_stage5_iter0_grp5_assign_proc : process(img_empty_n, ap_predicate_op88_read_state6)
    begin
                ap_block_state6_pp0_stage5_iter0_grp5 <= ((img_empty_n = ap_const_logic_0) and (ap_predicate_op88_read_state6 = ap_const_boolean_1));
    end process;


    ap_block_state7_pp0_stage6_iter0_grp6_assign_proc : process(img_empty_n, bytePlanes_full_n, ap_predicate_op96_read_state7, ap_predicate_op105_write_state7)
    begin
                ap_block_state7_pp0_stage6_iter0_grp6 <= (((bytePlanes_full_n = ap_const_logic_0) and (ap_predicate_op105_write_state7 = ap_const_boolean_1)) or ((ap_predicate_op96_read_state7 = ap_const_boolean_1) and (img_empty_n = ap_const_logic_0)));
    end process;


    ap_block_state8_pp0_stage7_iter0_grp7_assign_proc : process(img_empty_n, ap_predicate_op107_read_state8)
    begin
                ap_block_state8_pp0_stage7_iter0_grp7 <= ((ap_predicate_op107_read_state8 = ap_const_boolean_1) and (img_empty_n = ap_const_logic_0));
    end process;


    ap_block_state9_pp0_stage0_iter1_assign_proc : process(img_empty_n, bytePlanes_full_n, ap_predicate_op115_read_state9, or_ln1110_1_reg_653)
    begin
                ap_block_state9_pp0_stage0_iter1 <= (((or_ln1110_1_reg_653 = ap_const_lv1_1) and (bytePlanes_full_n = ap_const_logic_0)) or ((ap_predicate_op115_read_state9 = ap_const_boolean_1) and (img_empty_n = ap_const_logic_0)));
    end process;


    ap_condition_306_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001_grp2)
    begin
                ap_condition_306 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2));
    end process;


    ap_condition_332_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001_grp3)
    begin
                ap_condition_332 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001_grp3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3));
    end process;


    ap_condition_360_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4_11001_grp4)
    begin
                ap_condition_360 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001_grp4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4));
    end process;


    ap_condition_383_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage5, ap_block_pp0_stage5_11001_grp5)
    begin
                ap_condition_383 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage5_11001_grp5) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5));
    end process;


    ap_condition_409_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage6, ap_block_pp0_stage6_11001_grp6)
    begin
                ap_condition_409 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage6_11001_grp6) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6));
    end process;


    ap_condition_425_assign_proc : process(ap_CS_fsm_pp0_stage7, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage7_11001_grp7)
    begin
                ap_condition_425 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_11001_grp7) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7));
    end process;


    ap_condition_710_assign_proc : process(icmp_ln1090_reg_617, or_ln1095_6_reg_645, ap_block_pp0_stage7_11001_grp7)
    begin
                ap_condition_710 <= ((ap_const_boolean_0 = ap_block_pp0_stage7_11001_grp7) and (or_ln1095_6_reg_645 = ap_const_lv1_0) and (icmp_ln1090_reg_617 = ap_const_lv1_1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln1090_fu_440_p2)
    begin
        if (((icmp_ln1090_fu_440_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_phi_mux_empty_131_phi_fu_367_p4_assign_proc : process(img_dout, icmp_ln1090_reg_617, or_ln1095_6_reg_645, ap_phi_reg_pp0_iter1_empty_131_reg_364)
    begin
        if (((or_ln1095_6_reg_645 = ap_const_lv1_1) and (icmp_ln1090_reg_617 = ap_const_lv1_1))) then 
            ap_phi_mux_empty_131_phi_fu_367_p4 <= img_dout(23 downto 16);
        else 
            ap_phi_mux_empty_131_phi_fu_367_p4 <= ap_phi_reg_pp0_iter1_empty_131_reg_364;
        end if; 
    end process;


    ap_phi_mux_empty_132_phi_fu_377_p4_assign_proc : process(img_dout, icmp_ln1090_reg_617, or_ln1095_6_reg_645, ap_phi_reg_pp0_iter1_empty_132_reg_374)
    begin
        if (((or_ln1095_6_reg_645 = ap_const_lv1_1) and (icmp_ln1090_reg_617 = ap_const_lv1_1))) then 
            ap_phi_mux_empty_132_phi_fu_377_p4 <= img_dout(15 downto 8);
        else 
            ap_phi_mux_empty_132_phi_fu_377_p4 <= ap_phi_reg_pp0_iter1_empty_132_reg_374;
        end if; 
    end process;


    ap_phi_mux_empty_133_phi_fu_387_p4_assign_proc : process(icmp_ln1090_reg_617, or_ln1095_6_reg_645, trunc_ln1096_19_fu_584_p1, ap_phi_reg_pp0_iter1_empty_133_reg_384)
    begin
        if (((or_ln1095_6_reg_645 = ap_const_lv1_1) and (icmp_ln1090_reg_617 = ap_const_lv1_1))) then 
            ap_phi_mux_empty_133_phi_fu_387_p4 <= trunc_ln1096_19_fu_584_p1;
        else 
            ap_phi_mux_empty_133_phi_fu_387_p4 <= ap_phi_reg_pp0_iter1_empty_133_reg_384;
        end if; 
    end process;


    ap_phi_mux_empty_134_phi_fu_334_p4_assign_proc : process(img_dout, icmp_ln1090_reg_617, or_ln1095_5_reg_641, ap_phi_reg_pp0_iter0_empty_134_reg_331)
    begin
        if (((or_ln1095_5_reg_641 = ap_const_lv1_1) and (icmp_ln1090_reg_617 = ap_const_lv1_1))) then 
            ap_phi_mux_empty_134_phi_fu_334_p4 <= img_dout(23 downto 16);
        else 
            ap_phi_mux_empty_134_phi_fu_334_p4 <= ap_phi_reg_pp0_iter0_empty_134_reg_331;
        end if; 
    end process;


    ap_phi_mux_empty_135_phi_fu_345_p4_assign_proc : process(img_dout, icmp_ln1090_reg_617, or_ln1095_5_reg_641, ap_phi_reg_pp0_iter0_empty_135_reg_342)
    begin
        if (((or_ln1095_5_reg_641 = ap_const_lv1_1) and (icmp_ln1090_reg_617 = ap_const_lv1_1))) then 
            ap_phi_mux_empty_135_phi_fu_345_p4 <= img_dout(15 downto 8);
        else 
            ap_phi_mux_empty_135_phi_fu_345_p4 <= ap_phi_reg_pp0_iter0_empty_135_reg_342;
        end if; 
    end process;


    ap_phi_mux_empty_136_phi_fu_356_p4_assign_proc : process(icmp_ln1090_reg_617, or_ln1095_5_reg_641, trunc_ln1096_16_fu_579_p1, ap_phi_reg_pp0_iter0_empty_136_reg_353)
    begin
        if (((or_ln1095_5_reg_641 = ap_const_lv1_1) and (icmp_ln1090_reg_617 = ap_const_lv1_1))) then 
            ap_phi_mux_empty_136_phi_fu_356_p4 <= trunc_ln1096_16_fu_579_p1;
        else 
            ap_phi_mux_empty_136_phi_fu_356_p4 <= ap_phi_reg_pp0_iter0_empty_136_reg_353;
        end if; 
    end process;


    ap_phi_mux_empty_137_phi_fu_301_p4_assign_proc : process(img_dout, icmp_ln1090_reg_617, or_ln1095_4_reg_637, ap_phi_reg_pp0_iter0_empty_137_reg_298)
    begin
        if (((icmp_ln1090_reg_617 = ap_const_lv1_1) and (or_ln1095_4_reg_637 = ap_const_lv1_1))) then 
            ap_phi_mux_empty_137_phi_fu_301_p4 <= img_dout(23 downto 16);
        else 
            ap_phi_mux_empty_137_phi_fu_301_p4 <= ap_phi_reg_pp0_iter0_empty_137_reg_298;
        end if; 
    end process;


    ap_phi_mux_empty_138_phi_fu_312_p4_assign_proc : process(img_dout, icmp_ln1090_reg_617, or_ln1095_4_reg_637, ap_phi_reg_pp0_iter0_empty_138_reg_309)
    begin
        if (((icmp_ln1090_reg_617 = ap_const_lv1_1) and (or_ln1095_4_reg_637 = ap_const_lv1_1))) then 
            ap_phi_mux_empty_138_phi_fu_312_p4 <= img_dout(15 downto 8);
        else 
            ap_phi_mux_empty_138_phi_fu_312_p4 <= ap_phi_reg_pp0_iter0_empty_138_reg_309;
        end if; 
    end process;


    ap_phi_mux_empty_139_phi_fu_323_p4_assign_proc : process(icmp_ln1090_reg_617, or_ln1095_4_reg_637, trunc_ln1096_13_fu_553_p1, ap_phi_reg_pp0_iter0_empty_139_reg_320)
    begin
        if (((icmp_ln1090_reg_617 = ap_const_lv1_1) and (or_ln1095_4_reg_637 = ap_const_lv1_1))) then 
            ap_phi_mux_empty_139_phi_fu_323_p4 <= trunc_ln1096_13_fu_553_p1;
        else 
            ap_phi_mux_empty_139_phi_fu_323_p4 <= ap_phi_reg_pp0_iter0_empty_139_reg_320;
        end if; 
    end process;


    ap_phi_mux_empty_140_phi_fu_268_p4_assign_proc : process(img_dout, icmp_ln1090_reg_617, or_ln1095_3_reg_633, ap_phi_reg_pp0_iter0_empty_140_reg_265)
    begin
        if (((icmp_ln1090_reg_617 = ap_const_lv1_1) and (or_ln1095_3_reg_633 = ap_const_lv1_1))) then 
            ap_phi_mux_empty_140_phi_fu_268_p4 <= img_dout(23 downto 16);
        else 
            ap_phi_mux_empty_140_phi_fu_268_p4 <= ap_phi_reg_pp0_iter0_empty_140_reg_265;
        end if; 
    end process;


    ap_phi_mux_empty_141_phi_fu_279_p4_assign_proc : process(img_dout, icmp_ln1090_reg_617, or_ln1095_3_reg_633, ap_phi_reg_pp0_iter0_empty_141_reg_276)
    begin
        if (((icmp_ln1090_reg_617 = ap_const_lv1_1) and (or_ln1095_3_reg_633 = ap_const_lv1_1))) then 
            ap_phi_mux_empty_141_phi_fu_279_p4 <= img_dout(15 downto 8);
        else 
            ap_phi_mux_empty_141_phi_fu_279_p4 <= ap_phi_reg_pp0_iter0_empty_141_reg_276;
        end if; 
    end process;


    ap_phi_mux_empty_142_phi_fu_290_p4_assign_proc : process(icmp_ln1090_reg_617, or_ln1095_3_reg_633, trunc_ln1096_10_fu_548_p1, ap_phi_reg_pp0_iter0_empty_142_reg_287)
    begin
        if (((icmp_ln1090_reg_617 = ap_const_lv1_1) and (or_ln1095_3_reg_633 = ap_const_lv1_1))) then 
            ap_phi_mux_empty_142_phi_fu_290_p4 <= trunc_ln1096_10_fu_548_p1;
        else 
            ap_phi_mux_empty_142_phi_fu_290_p4 <= ap_phi_reg_pp0_iter0_empty_142_reg_287;
        end if; 
    end process;


    ap_phi_mux_empty_143_phi_fu_235_p4_assign_proc : process(img_dout, icmp_ln1090_reg_617, or_ln1095_2_reg_629, ap_phi_reg_pp0_iter0_empty_143_reg_232)
    begin
        if (((icmp_ln1090_reg_617 = ap_const_lv1_1) and (or_ln1095_2_reg_629 = ap_const_lv1_1))) then 
            ap_phi_mux_empty_143_phi_fu_235_p4 <= img_dout(23 downto 16);
        else 
            ap_phi_mux_empty_143_phi_fu_235_p4 <= ap_phi_reg_pp0_iter0_empty_143_reg_232;
        end if; 
    end process;


    ap_phi_mux_empty_144_phi_fu_246_p4_assign_proc : process(img_dout, icmp_ln1090_reg_617, or_ln1095_2_reg_629, ap_phi_reg_pp0_iter0_empty_144_reg_243)
    begin
        if (((icmp_ln1090_reg_617 = ap_const_lv1_1) and (or_ln1095_2_reg_629 = ap_const_lv1_1))) then 
            ap_phi_mux_empty_144_phi_fu_246_p4 <= img_dout(15 downto 8);
        else 
            ap_phi_mux_empty_144_phi_fu_246_p4 <= ap_phi_reg_pp0_iter0_empty_144_reg_243;
        end if; 
    end process;


    ap_phi_mux_empty_145_phi_fu_257_p4_assign_proc : process(icmp_ln1090_reg_617, or_ln1095_2_reg_629, trunc_ln1096_6_fu_543_p1, ap_phi_reg_pp0_iter0_empty_145_reg_254)
    begin
        if (((icmp_ln1090_reg_617 = ap_const_lv1_1) and (or_ln1095_2_reg_629 = ap_const_lv1_1))) then 
            ap_phi_mux_empty_145_phi_fu_257_p4 <= trunc_ln1096_6_fu_543_p1;
        else 
            ap_phi_mux_empty_145_phi_fu_257_p4 <= ap_phi_reg_pp0_iter0_empty_145_reg_254;
        end if; 
    end process;


    ap_phi_mux_empty_146_phi_fu_203_p4_assign_proc : process(img_dout, icmp_ln1090_reg_617, or_ln1095_1_reg_625, ap_phi_reg_pp0_iter0_empty_146_reg_200)
    begin
        if (((icmp_ln1090_reg_617 = ap_const_lv1_1) and (or_ln1095_1_reg_625 = ap_const_lv1_1))) then 
            ap_phi_mux_empty_146_phi_fu_203_p4 <= img_dout(23 downto 16);
        else 
            ap_phi_mux_empty_146_phi_fu_203_p4 <= ap_phi_reg_pp0_iter0_empty_146_reg_200;
        end if; 
    end process;


    ap_phi_mux_empty_147_phi_fu_214_p4_assign_proc : process(img_dout, icmp_ln1090_reg_617, or_ln1095_1_reg_625, ap_phi_reg_pp0_iter0_empty_147_reg_211)
    begin
        if (((icmp_ln1090_reg_617 = ap_const_lv1_1) and (or_ln1095_1_reg_625 = ap_const_lv1_1))) then 
            ap_phi_mux_empty_147_phi_fu_214_p4 <= img_dout(15 downto 8);
        else 
            ap_phi_mux_empty_147_phi_fu_214_p4 <= ap_phi_reg_pp0_iter0_empty_147_reg_211;
        end if; 
    end process;


    ap_phi_mux_empty_148_phi_fu_225_p4_assign_proc : process(icmp_ln1090_reg_617, or_ln1095_1_reg_625, trunc_ln1096_3_fu_522_p1, ap_phi_reg_pp0_iter0_empty_148_reg_222, trunc_ln1096_fu_517_p1)
    begin
        if ((icmp_ln1090_reg_617 = ap_const_lv1_1)) then
            if ((or_ln1095_1_reg_625 = ap_const_lv1_0)) then 
                ap_phi_mux_empty_148_phi_fu_225_p4 <= trunc_ln1096_fu_517_p1;
            elsif ((or_ln1095_1_reg_625 = ap_const_lv1_1)) then 
                ap_phi_mux_empty_148_phi_fu_225_p4 <= trunc_ln1096_3_fu_522_p1;
            else 
                ap_phi_mux_empty_148_phi_fu_225_p4 <= ap_phi_reg_pp0_iter0_empty_148_reg_222;
            end if;
        else 
            ap_phi_mux_empty_148_phi_fu_225_p4 <= ap_phi_reg_pp0_iter0_empty_148_reg_222;
        end if; 
    end process;


    ap_phi_mux_empty_149_phi_fu_174_p4_assign_proc : process(img_dout, icmp_ln1090_reg_617, or_ln1095_reg_621, ap_phi_reg_pp0_iter0_empty_149_reg_171)
    begin
        if (((icmp_ln1090_reg_617 = ap_const_lv1_1) and (or_ln1095_reg_621 = ap_const_lv1_1))) then 
            ap_phi_mux_empty_149_phi_fu_174_p4 <= img_dout(23 downto 16);
        else 
            ap_phi_mux_empty_149_phi_fu_174_p4 <= ap_phi_reg_pp0_iter0_empty_149_reg_171;
        end if; 
    end process;


    ap_phi_mux_empty_150_phi_fu_184_p4_assign_proc : process(img_dout, icmp_ln1090_reg_617, or_ln1095_reg_621, ap_phi_reg_pp0_iter0_empty_150_reg_181)
    begin
        if (((icmp_ln1090_reg_617 = ap_const_lv1_1) and (or_ln1095_reg_621 = ap_const_lv1_1))) then 
            ap_phi_mux_empty_150_phi_fu_184_p4 <= img_dout(15 downto 8);
        else 
            ap_phi_mux_empty_150_phi_fu_184_p4 <= ap_phi_reg_pp0_iter0_empty_150_reg_181;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_empty_131_reg_364 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_empty_132_reg_374 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_empty_133_reg_384 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_empty_148_reg_222 <= "XXXXXXXX";

    ap_predicate_op105_write_state7_assign_proc : process(icmp_ln1090_reg_617, or_ln1110_reg_649)
    begin
                ap_predicate_op105_write_state7 <= ((icmp_ln1090_reg_617 = ap_const_lv1_1) and (or_ln1110_reg_649 = ap_const_lv1_1));
    end process;


    ap_predicate_op107_read_state8_assign_proc : process(icmp_ln1090_reg_617, or_ln1095_5_reg_641)
    begin
                ap_predicate_op107_read_state8 <= ((or_ln1095_5_reg_641 = ap_const_lv1_1) and (icmp_ln1090_reg_617 = ap_const_lv1_1));
    end process;


    ap_predicate_op115_read_state9_assign_proc : process(icmp_ln1090_reg_617, or_ln1095_6_reg_645)
    begin
                ap_predicate_op115_read_state9 <= ((or_ln1095_6_reg_645 = ap_const_lv1_1) and (icmp_ln1090_reg_617 = ap_const_lv1_1));
    end process;


    ap_predicate_op62_read_state3_assign_proc : process(icmp_ln1090_reg_617, or_ln1095_reg_621)
    begin
                ap_predicate_op62_read_state3 <= ((icmp_ln1090_reg_617 = ap_const_lv1_1) and (or_ln1095_reg_621 = ap_const_lv1_1));
    end process;


    ap_predicate_op70_read_state4_assign_proc : process(icmp_ln1090_reg_617, or_ln1095_1_reg_625)
    begin
                ap_predicate_op70_read_state4 <= ((icmp_ln1090_reg_617 = ap_const_lv1_1) and (or_ln1095_1_reg_625 = ap_const_lv1_1));
    end process;


    ap_predicate_op80_read_state5_assign_proc : process(icmp_ln1090_reg_617, or_ln1095_2_reg_629)
    begin
                ap_predicate_op80_read_state5 <= ((icmp_ln1090_reg_617 = ap_const_lv1_1) and (or_ln1095_2_reg_629 = ap_const_lv1_1));
    end process;


    ap_predicate_op88_read_state6_assign_proc : process(icmp_ln1090_reg_617, or_ln1095_3_reg_633)
    begin
                ap_predicate_op88_read_state6 <= ((icmp_ln1090_reg_617 = ap_const_lv1_1) and (or_ln1095_3_reg_633 = ap_const_lv1_1));
    end process;


    ap_predicate_op96_read_state7_assign_proc : process(icmp_ln1090_reg_617, or_ln1095_4_reg_637)
    begin
                ap_predicate_op96_read_state7 <= ((icmp_ln1090_reg_617 = ap_const_lv1_1) and (or_ln1095_4_reg_637 = ap_const_lv1_1));
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage7, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage7_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_x_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, x_fu_88, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_x_1 <= ap_const_lv9_0;
        else 
            ap_sig_allocacmp_x_1 <= x_fu_88;
        end if; 
    end process;


    bytePlanes_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, bytePlanes_full_n, icmp_ln1090_reg_617, or_ln1110_1_reg_653, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_grp3, ap_CS_fsm_pp0_stage6, ap_block_pp0_stage6_grp6, or_ln1110_reg_649, ap_block_pp0_stage0)
    begin
        if ((((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage6_grp6) and (icmp_ln1090_reg_617 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6) and (or_ln1110_reg_649 = ap_const_lv1_1)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_grp3) and (icmp_ln1090_reg_617 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (or_ln1110_1_reg_653 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            bytePlanes_blk_n <= bytePlanes_full_n;
        else 
            bytePlanes_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    bytePlanes_din_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln1090_reg_617, or_ln1110_1_reg_653, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage6, ap_predicate_op105_write_state7, tmp_s_fu_527_p7, ap_block_pp0_stage3_01001_grp3, tmp_1_fu_558_p9, ap_block_pp0_stage6_01001_grp6, tmp_2_fu_589_p9, ap_block_pp0_stage0_01001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (or_ln1110_1_reg_653 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            bytePlanes_din <= tmp_2_fu_589_p9;
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage6_01001_grp6) and (ap_predicate_op105_write_state7 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6))) then 
            bytePlanes_din <= tmp_1_fu_558_p9;
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_01001_grp3) and (icmp_ln1090_reg_617 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            bytePlanes_din <= tmp_s_fu_527_p7;
        else 
            bytePlanes_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    bytePlanes_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln1090_reg_617, or_ln1110_1_reg_653, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage6, ap_block_pp0_stage0_11001, ap_block_pp0_stage3_11001_grp3, ap_predicate_op105_write_state7, ap_block_pp0_stage6_11001_grp6)
    begin
        if ((((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage6_11001_grp6) and (ap_predicate_op105_write_state7 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001_grp3) and (icmp_ln1090_reg_617 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (or_ln1110_1_reg_653 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            bytePlanes_write <= ap_const_logic_1;
        else 
            bytePlanes_write <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln1090_fu_440_p2 <= "1" when (unsigned(ap_sig_allocacmp_x_1) < unsigned(trunc_ln1)) else "0";
    icmp_ln1095_fu_452_p2 <= "1" when (signed(zext_ln1090_fu_436_p1) < signed(add_ln1095)) else "0";

    img_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, img_empty_n, icmp_ln1090_reg_617, ap_predicate_op115_read_state9, ap_CS_fsm_pp0_stage7, ap_predicate_op107_read_state8, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_grp3, ap_CS_fsm_pp0_stage6, ap_block_pp0_stage6_grp6, ap_block_pp0_stage0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_grp1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_grp2, or_ln1095_reg_621, or_ln1095_1_reg_625, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4_grp4, or_ln1095_2_reg_629, ap_CS_fsm_pp0_stage5, ap_block_pp0_stage5_grp5, or_ln1095_3_reg_633, or_ln1095_4_reg_637, ap_block_pp0_stage7_grp7)
    begin
        if ((((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_predicate_op107_read_state8 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_grp7) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage5_grp5) and (icmp_ln1090_reg_617 = ap_const_lv1_1) and (or_ln1095_3_reg_633 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_grp4) and (icmp_ln1090_reg_617 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (or_ln1095_2_reg_629 = ap_const_lv1_1)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_grp2) and (icmp_ln1090_reg_617 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (or_ln1095_reg_621 = ap_const_lv1_1)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp1) 
    and (icmp_ln1090_reg_617 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage6_grp6) and (icmp_ln1090_reg_617 = ap_const_lv1_1) and (or_ln1095_4_reg_637 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_grp3) and (icmp_ln1090_reg_617 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (or_ln1095_1_reg_625 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op115_read_state9 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            img_blk_n <= img_empty_n;
        else 
            img_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    img_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln1090_reg_617, ap_predicate_op115_read_state9, ap_CS_fsm_pp0_stage7, ap_predicate_op107_read_state8, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage6, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage5, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001_grp1, ap_predicate_op62_read_state3, ap_block_pp0_stage2_11001_grp2, ap_predicate_op70_read_state4, ap_block_pp0_stage3_11001_grp3, ap_predicate_op80_read_state5, ap_block_pp0_stage4_11001_grp4, ap_predicate_op88_read_state6, ap_block_pp0_stage5_11001_grp5, ap_predicate_op96_read_state7, ap_block_pp0_stage6_11001_grp6, ap_block_pp0_stage7_11001_grp7)
    begin
        if ((((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_predicate_op107_read_state8 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_11001_grp7) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage6_11001_grp6) and (ap_predicate_op96_read_state7 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage5_11001_grp5) and (ap_predicate_op88_read_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001_grp4) and (ap_predicate_op80_read_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001_grp3) and (ap_predicate_op70_read_state4 = ap_const_boolean_1) 
    and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp2) and (ap_predicate_op62_read_state3 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp1) and (icmp_ln1090_reg_617 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op115_read_state9 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            img_read <= ap_const_logic_1;
        else 
            img_read <= ap_const_logic_0;
        end if; 
    end process;

    or_ln1095_1_fu_464_p2 <= (icmp_ln1095_fu_452_p2 or icmp_ln1095_1);
    or_ln1095_2_fu_470_p2 <= (icmp_ln1095_fu_452_p2 or icmp9);
    or_ln1095_3_fu_476_p2 <= (icmp_ln1095_fu_452_p2 or icmp_ln1095_3);
    or_ln1095_4_fu_482_p2 <= (icmp_ln1095_fu_452_p2 or icmp_ln1095_4);
    or_ln1095_5_fu_488_p2 <= (icmp_ln1095_fu_452_p2 or icmp_ln1095_5);
    or_ln1095_6_fu_494_p2 <= (icmp_ln1095_fu_452_p2 or icmp_ln1077);
    or_ln1095_fu_458_p2 <= (icmp_ln1095_fu_452_p2 or icmp6);
    or_ln1110_1_fu_506_p2 <= (icmp_ln1110_1 or icmp_ln1095_fu_452_p2);
    or_ln1110_fu_500_p2 <= (icmp_ln1095_fu_452_p2 or empty);
    tmp_1_fu_558_p9 <= (((((((ap_phi_mux_empty_139_phi_fu_323_p4 & empty_140_reg_265) & empty_141_reg_276) & empty_142_reg_287) & empty_143_reg_232) & empty_144_reg_243) & empty_145_reg_254) & empty_146_reg_200);
    tmp_2_fu_589_p9 <= (((((((ap_phi_mux_empty_131_phi_fu_367_p4 & ap_phi_mux_empty_132_phi_fu_377_p4) & ap_phi_mux_empty_133_phi_fu_387_p4) & empty_134_reg_331) & empty_135_reg_342) & empty_136_reg_353) & empty_137_reg_298) & empty_138_reg_309);
    tmp_s_fu_527_p7 <= (((((ap_phi_mux_empty_147_phi_fu_214_p4 & ap_phi_mux_empty_148_phi_fu_225_p4) & empty_149_reg_171) & empty_150_reg_181) & trunc_ln1096_fu_517_p1) & img_read_reg_657);
    trunc_ln1096_10_fu_548_p1 <= img_dout(8 - 1 downto 0);
    trunc_ln1096_13_fu_553_p1 <= img_dout(8 - 1 downto 0);
    trunc_ln1096_16_fu_579_p1 <= img_dout(8 - 1 downto 0);
    trunc_ln1096_19_fu_584_p1 <= img_dout(8 - 1 downto 0);
    trunc_ln1096_3_fu_522_p1 <= img_dout(8 - 1 downto 0);
    trunc_ln1096_6_fu_543_p1 <= img_dout(8 - 1 downto 0);
    trunc_ln1096_fu_517_p1 <= ap_phi_reg_pp0_iter0_phi_ln1096_reg_191(8 - 1 downto 0);
    x_2_fu_446_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_x_1) + unsigned(ap_const_lv9_1));
    zext_ln1090_fu_436_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_x_1),10));
end behav;
