// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="hls_threshold_gray_hls_threshold_gray,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.132000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=241,HLS_SYN_LUT=445,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module hls_threshold_gray (
        ap_clk,
        ap_rst_n,
        s_axis_video_TDATA,
        s_axis_video_TVALID,
        s_axis_video_TREADY,
        m_axis_video_TDATA,
        m_axis_video_TVALID,
        m_axis_video_TREADY,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [23:0] s_axis_video_TDATA;
input   s_axis_video_TVALID;
output   s_axis_video_TREADY;
output  [23:0] m_axis_video_TDATA;
output   m_axis_video_TVALID;
input   m_axis_video_TREADY;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [7:0] thresh_val;
wire   [1:0] thresh_type;
wire  signed [31:0] width;
wire  signed [31:0] height;
reg   [1:0] thresh_type_read_reg_98;
wire    ap_CS_fsm_state2;
reg   [7:0] thresh_val_read_reg_103;
wire   [31:0] total_pixels_fu_91_p2;
reg   [31:0] total_pixels_reg_108;
wire    grp_hls_threshold_gray_Pipeline_VITIS_LOOP_24_1_fu_78_ap_start;
wire    grp_hls_threshold_gray_Pipeline_VITIS_LOOP_24_1_fu_78_ap_done;
wire    grp_hls_threshold_gray_Pipeline_VITIS_LOOP_24_1_fu_78_ap_idle;
wire    grp_hls_threshold_gray_Pipeline_VITIS_LOOP_24_1_fu_78_ap_ready;
wire    grp_hls_threshold_gray_Pipeline_VITIS_LOOP_24_1_fu_78_m_axis_video_TREADY;
wire   [23:0] grp_hls_threshold_gray_Pipeline_VITIS_LOOP_24_1_fu_78_m_axis_video_TDATA;
wire    grp_hls_threshold_gray_Pipeline_VITIS_LOOP_24_1_fu_78_m_axis_video_TVALID;
wire    grp_hls_threshold_gray_Pipeline_VITIS_LOOP_24_1_fu_78_s_axis_video_TREADY;
reg    grp_hls_threshold_gray_Pipeline_VITIS_LOOP_24_1_fu_78_ap_start_reg;
wire    ap_CS_fsm_state3;
reg   [23:0] m_axis_video_TDATA_reg;
wire    ap_CS_fsm_state4;
wire    regslice_both_m_axis_video_U_apdone_blk;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    regslice_both_s_axis_video_U_apdone_blk;
wire   [23:0] s_axis_video_TDATA_int_regslice;
wire    s_axis_video_TVALID_int_regslice;
reg    s_axis_video_TREADY_int_regslice;
wire    regslice_both_s_axis_video_U_ack_in;
reg   [23:0] m_axis_video_TDATA_int_regslice;
wire    m_axis_video_TREADY_int_regslice;
wire    regslice_both_m_axis_video_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 grp_hls_threshold_gray_Pipeline_VITIS_LOOP_24_1_fu_78_ap_start_reg = 1'b0;
end

hls_threshold_gray_hls_threshold_gray_Pipeline_VITIS_LOOP_24_1 grp_hls_threshold_gray_Pipeline_VITIS_LOOP_24_1_fu_78(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_hls_threshold_gray_Pipeline_VITIS_LOOP_24_1_fu_78_ap_start),
    .ap_done(grp_hls_threshold_gray_Pipeline_VITIS_LOOP_24_1_fu_78_ap_done),
    .ap_idle(grp_hls_threshold_gray_Pipeline_VITIS_LOOP_24_1_fu_78_ap_idle),
    .ap_ready(grp_hls_threshold_gray_Pipeline_VITIS_LOOP_24_1_fu_78_ap_ready),
    .s_axis_video_TVALID(s_axis_video_TVALID_int_regslice),
    .m_axis_video_TREADY(grp_hls_threshold_gray_Pipeline_VITIS_LOOP_24_1_fu_78_m_axis_video_TREADY),
    .total_pixels(total_pixels_reg_108),
    .m_axis_video_TDATA(grp_hls_threshold_gray_Pipeline_VITIS_LOOP_24_1_fu_78_m_axis_video_TDATA),
    .m_axis_video_TVALID(grp_hls_threshold_gray_Pipeline_VITIS_LOOP_24_1_fu_78_m_axis_video_TVALID),
    .s_axis_video_TDATA(s_axis_video_TDATA_int_regslice),
    .s_axis_video_TREADY(grp_hls_threshold_gray_Pipeline_VITIS_LOOP_24_1_fu_78_s_axis_video_TREADY),
    .thresh_val(thresh_val_read_reg_103),
    .thresh_type(thresh_type_read_reg_98)
);

hls_threshold_gray_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .thresh_val(thresh_val),
    .thresh_type(thresh_type),
    .width(width),
    .height(height),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

hls_threshold_gray_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U6(
    .din0(height),
    .din1(width),
    .dout(total_pixels_fu_91_p2)
);

hls_threshold_gray_regslice_both #(
    .DataWidth( 24 ))
regslice_both_s_axis_video_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video_TDATA),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_U_ack_in),
    .data_out(s_axis_video_TDATA_int_regslice),
    .vld_out(s_axis_video_TVALID_int_regslice),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_U_apdone_blk)
);

hls_threshold_gray_regslice_both #(
    .DataWidth( 24 ))
regslice_both_m_axis_video_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(m_axis_video_TDATA_int_regslice),
    .vld_in(grp_hls_threshold_gray_Pipeline_VITIS_LOOP_24_1_fu_78_m_axis_video_TVALID),
    .ack_in(m_axis_video_TREADY_int_regslice),
    .data_out(m_axis_video_TDATA),
    .vld_out(regslice_both_m_axis_video_U_vld_out),
    .ack_out(m_axis_video_TREADY),
    .apdone_blk(regslice_both_m_axis_video_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_hls_threshold_gray_Pipeline_VITIS_LOOP_24_1_fu_78_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_hls_threshold_gray_Pipeline_VITIS_LOOP_24_1_fu_78_ap_start_reg <= 1'b1;
        end else if ((grp_hls_threshold_gray_Pipeline_VITIS_LOOP_24_1_fu_78_ap_ready == 1'b1)) begin
            grp_hls_threshold_gray_Pipeline_VITIS_LOOP_24_1_fu_78_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_hls_threshold_gray_Pipeline_VITIS_LOOP_24_1_fu_78_m_axis_video_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        m_axis_video_TDATA_reg <= grp_hls_threshold_gray_Pipeline_VITIS_LOOP_24_1_fu_78_m_axis_video_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        thresh_type_read_reg_98 <= thresh_type;
        thresh_val_read_reg_103 <= thresh_val;
        total_pixels_reg_108 <= total_pixels_fu_91_p2;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_hls_threshold_gray_Pipeline_VITIS_LOOP_24_1_fu_78_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_m_axis_video_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (regslice_both_m_axis_video_U_apdone_blk == 1'b0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (regslice_both_m_axis_video_U_apdone_blk == 1'b0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((grp_hls_threshold_gray_Pipeline_VITIS_LOOP_24_1_fu_78_m_axis_video_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        m_axis_video_TDATA_int_regslice = grp_hls_threshold_gray_Pipeline_VITIS_LOOP_24_1_fu_78_m_axis_video_TDATA;
    end else begin
        m_axis_video_TDATA_int_regslice = m_axis_video_TDATA_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        s_axis_video_TREADY_int_regslice = grp_hls_threshold_gray_Pipeline_VITIS_LOOP_24_1_fu_78_s_axis_video_TREADY;
    end else begin
        s_axis_video_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_hls_threshold_gray_Pipeline_VITIS_LOOP_24_1_fu_78_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (regslice_both_m_axis_video_U_apdone_blk == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_hls_threshold_gray_Pipeline_VITIS_LOOP_24_1_fu_78_ap_start = grp_hls_threshold_gray_Pipeline_VITIS_LOOP_24_1_fu_78_ap_start_reg;

assign grp_hls_threshold_gray_Pipeline_VITIS_LOOP_24_1_fu_78_m_axis_video_TREADY = (m_axis_video_TREADY_int_regslice & ap_CS_fsm_state3);

assign m_axis_video_TVALID = regslice_both_m_axis_video_U_vld_out;

assign s_axis_video_TREADY = regslice_both_s_axis_video_U_ack_in;


reg find_kernel_block = 0;
// synthesis translate_off
`include "hls_threshold_gray_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //hls_threshold_gray

