

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "33", "34", "35", "36"],
		"CDFG" : "hls_filter_2d",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "15", "EstimateLatencyMax" : "67108878",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "s_axis_video", "Type" : "Axis", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_hls_filter_2d_Pipeline_VITIS_LOOP_51_1_fu_364", "Port" : "s_axis_video", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "m_axis_video", "Type" : "Axis", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_hls_filter_2d_Pipeline_VITIS_LOOP_51_1_fu_364", "Port" : "m_axis_video", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "width", "Type" : "None", "Direction" : "I"},
			{"Name" : "height", "Type" : "None", "Direction" : "I"},
			{"Name" : "kernel_0_0", "Type" : "None", "Direction" : "I"},
			{"Name" : "kernel_0_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "kernel_0_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "kernel_0_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "kernel_0_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "kernel_1_0", "Type" : "None", "Direction" : "I"},
			{"Name" : "kernel_1_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "kernel_1_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "kernel_1_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "kernel_1_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "kernel_2_0", "Type" : "None", "Direction" : "I"},
			{"Name" : "kernel_2_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "kernel_2_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "kernel_2_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "kernel_2_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "kernel_3_0", "Type" : "None", "Direction" : "I"},
			{"Name" : "kernel_3_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "kernel_3_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "kernel_3_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "kernel_3_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "kernel_4_0", "Type" : "None", "Direction" : "I"},
			{"Name" : "kernel_4_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "kernel_4_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "kernel_4_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "kernel_4_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "inv_divisor", "Type" : "None", "Direction" : "I"},
			{"Name" : "fraction_bits", "Type" : "None", "Direction" : "I"},
			{"Name" : "delta", "Type" : "None", "Direction" : "I"},
			{"Name" : "borderType", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_hls_filter_2d_Pipeline_VITIS_LOOP_51_1_fu_364", "Parent" : "0", "Child" : ["2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32"],
		"CDFG" : "hls_filter_2d_Pipeline_VITIS_LOOP_51_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "12", "EstimateLatencyMax" : "67108875",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "total_pixels", "Type" : "None", "Direction" : "I"},
			{"Name" : "flush_cycles", "Type" : "None", "Direction" : "I"},
			{"Name" : "total_cycles", "Type" : "None", "Direction" : "I"},
			{"Name" : "add_ln88", "Type" : "None", "Direction" : "I"},
			{"Name" : "width", "Type" : "None", "Direction" : "I"},
			{"Name" : "s_axis_video", "Type" : "Axis", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "s_axis_video_TDATA_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "add_ln140", "Type" : "None", "Direction" : "I"},
			{"Name" : "add_ln141", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln122", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln43", "Type" : "None", "Direction" : "I"},
			{"Name" : "height", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln117_17", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln117_16", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln117_15", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln117_14", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln117_13", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln117_12", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln117_11", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln117_10", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln117_9", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln117_8", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln117_7", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln117_6", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln117_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln117_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln117_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln117_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln117", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln117_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln51", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln117_23", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln117_22", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln117_21", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln117_20", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln117_19", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln117_18", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln122", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln140", "Type" : "None", "Direction" : "I"},
			{"Name" : "delta", "Type" : "None", "Direction" : "I"},
			{"Name" : "borderType", "Type" : "None", "Direction" : "I"},
			{"Name" : "add_ln155", "Type" : "None", "Direction" : "I"},
			{"Name" : "m_axis_video", "Type" : "Axis", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "m_axis_video_TDATA_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_51_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter9", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter9", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "2", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_hls_filter_2d_Pipeline_VITIS_LOOP_51_1_fu_364.line_buffer_3_U", "Parent" : "1"},
	{"ID" : "3", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_hls_filter_2d_Pipeline_VITIS_LOOP_51_1_fu_364.line_buffer_2_U", "Parent" : "1"},
	{"ID" : "4", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_hls_filter_2d_Pipeline_VITIS_LOOP_51_1_fu_364.line_buffer_1_U", "Parent" : "1"},
	{"ID" : "5", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_hls_filter_2d_Pipeline_VITIS_LOOP_51_1_fu_364.line_buffer_U", "Parent" : "1"},
	{"ID" : "6", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_hls_filter_2d_Pipeline_VITIS_LOOP_51_1_fu_364.mul_21s_32s_52_1_1_U1", "Parent" : "1"},
	{"ID" : "7", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_hls_filter_2d_Pipeline_VITIS_LOOP_51_1_fu_364.mul_8ns_8s_16_1_1_U2", "Parent" : "1"},
	{"ID" : "8", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_hls_filter_2d_Pipeline_VITIS_LOOP_51_1_fu_364.mul_8ns_8s_16_1_1_U3", "Parent" : "1"},
	{"ID" : "9", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_hls_filter_2d_Pipeline_VITIS_LOOP_51_1_fu_364.mul_8ns_8s_16_1_1_U4", "Parent" : "1"},
	{"ID" : "10", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_hls_filter_2d_Pipeline_VITIS_LOOP_51_1_fu_364.mul_8ns_8s_16_1_1_U5", "Parent" : "1"},
	{"ID" : "11", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_hls_filter_2d_Pipeline_VITIS_LOOP_51_1_fu_364.mul_8ns_8s_16_1_1_U6", "Parent" : "1"},
	{"ID" : "12", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_hls_filter_2d_Pipeline_VITIS_LOOP_51_1_fu_364.mul_8ns_8s_16_1_1_U7", "Parent" : "1"},
	{"ID" : "13", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_hls_filter_2d_Pipeline_VITIS_LOOP_51_1_fu_364.mul_8ns_8s_16_1_1_U8", "Parent" : "1"},
	{"ID" : "14", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_hls_filter_2d_Pipeline_VITIS_LOOP_51_1_fu_364.mul_8ns_8s_16_1_1_U9", "Parent" : "1"},
	{"ID" : "15", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_hls_filter_2d_Pipeline_VITIS_LOOP_51_1_fu_364.mul_8ns_8s_16_1_1_U10", "Parent" : "1"},
	{"ID" : "16", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_hls_filter_2d_Pipeline_VITIS_LOOP_51_1_fu_364.mac_muladd_8ns_8s_16s_17_4_1_U11", "Parent" : "1"},
	{"ID" : "17", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_hls_filter_2d_Pipeline_VITIS_LOOP_51_1_fu_364.mac_muladd_8ns_8s_16s_17_4_1_U12", "Parent" : "1"},
	{"ID" : "18", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_hls_filter_2d_Pipeline_VITIS_LOOP_51_1_fu_364.mac_muladd_8ns_8s_16s_17_4_1_U13", "Parent" : "1"},
	{"ID" : "19", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_hls_filter_2d_Pipeline_VITIS_LOOP_51_1_fu_364.mac_muladd_8ns_8s_16s_17_4_1_U14", "Parent" : "1"},
	{"ID" : "20", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_hls_filter_2d_Pipeline_VITIS_LOOP_51_1_fu_364.mac_muladd_8ns_8s_16s_17_4_1_U15", "Parent" : "1"},
	{"ID" : "21", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_hls_filter_2d_Pipeline_VITIS_LOOP_51_1_fu_364.mac_muladd_8ns_8s_16s_17_4_1_U16", "Parent" : "1"},
	{"ID" : "22", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_hls_filter_2d_Pipeline_VITIS_LOOP_51_1_fu_364.mac_muladd_8ns_8s_16s_17_4_1_U17", "Parent" : "1"},
	{"ID" : "23", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_hls_filter_2d_Pipeline_VITIS_LOOP_51_1_fu_364.mac_muladd_8ns_8s_16s_17_4_1_U18", "Parent" : "1"},
	{"ID" : "24", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_hls_filter_2d_Pipeline_VITIS_LOOP_51_1_fu_364.mac_muladd_8ns_8s_16s_17_4_1_U19", "Parent" : "1"},
	{"ID" : "25", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_hls_filter_2d_Pipeline_VITIS_LOOP_51_1_fu_364.mac_muladd_8ns_8s_17s_18_4_1_U20", "Parent" : "1"},
	{"ID" : "26", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_hls_filter_2d_Pipeline_VITIS_LOOP_51_1_fu_364.mac_muladd_8ns_8s_17s_18_4_1_U21", "Parent" : "1"},
	{"ID" : "27", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_hls_filter_2d_Pipeline_VITIS_LOOP_51_1_fu_364.mac_muladd_8ns_8s_17s_18_4_1_U22", "Parent" : "1"},
	{"ID" : "28", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_hls_filter_2d_Pipeline_VITIS_LOOP_51_1_fu_364.mac_muladd_8ns_8s_17s_18_4_1_U23", "Parent" : "1"},
	{"ID" : "29", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_hls_filter_2d_Pipeline_VITIS_LOOP_51_1_fu_364.mac_muladd_8ns_8s_17s_18_4_1_U24", "Parent" : "1"},
	{"ID" : "30", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_hls_filter_2d_Pipeline_VITIS_LOOP_51_1_fu_364.mac_muladd_8ns_8s_17s_18_4_1_U25", "Parent" : "1"},
	{"ID" : "31", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_hls_filter_2d_Pipeline_VITIS_LOOP_51_1_fu_364.mac_muladd_8ns_8s_17s_18_4_1_U26", "Parent" : "1"},
	{"ID" : "32", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_hls_filter_2d_Pipeline_VITIS_LOOP_51_1_fu_364.flow_control_loop_pipe_sequential_init_U", "Parent" : "1"},
	{"ID" : "33", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"},
	{"ID" : "34", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_13ns_13ns_26_1_1_U74", "Parent" : "0"},
	{"ID" : "35", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_s_axis_video_U", "Parent" : "0"},
	{"ID" : "36", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_m_axis_video_U", "Parent" : "0"}]}
