// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module hls_filter_2d_hls_filter_2d_Pipeline_VITIS_LOOP_51_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        s_axis_video_TVALID,
        m_axis_video_TREADY,
        total_pixels,
        flush_cycles,
        total_cycles,
        add_ln88,
        width,
        s_axis_video_TDATA,
        s_axis_video_TREADY,
        add_ln140,
        add_ln141,
        zext_ln122,
        zext_ln43,
        height,
        sext_ln117_17,
        sext_ln117_16,
        sext_ln117_15,
        sext_ln117_14,
        sext_ln117_13,
        sext_ln117_12,
        sext_ln117_11,
        sext_ln117_10,
        sext_ln117_9,
        sext_ln117_8,
        sext_ln117_7,
        sext_ln117_6,
        sext_ln117_5,
        sext_ln117_4,
        sext_ln117_3,
        sext_ln117_2,
        sext_ln117,
        sext_ln117_1,
        sext_ln51,
        sext_ln117_23,
        sext_ln117_22,
        sext_ln117_21,
        sext_ln117_20,
        sext_ln117_19,
        sext_ln117_18,
        sext_ln122,
        zext_ln140,
        delta,
        borderType,
        add_ln155,
        m_axis_video_TDATA,
        m_axis_video_TVALID
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   s_axis_video_TVALID;
input   m_axis_video_TREADY;
input  [25:0] total_pixels;
input  [14:0] flush_cycles;
input  [26:0] total_cycles;
input  [13:0] add_ln88;
input  [12:0] width;
input  [23:0] s_axis_video_TDATA;
output   s_axis_video_TREADY;
input  [13:0] add_ln140;
input  [13:0] add_ln141;
input  [12:0] zext_ln122;
input  [12:0] zext_ln43;
input  [12:0] height;
input  [7:0] sext_ln117_17;
input  [7:0] sext_ln117_16;
input  [7:0] sext_ln117_15;
input  [7:0] sext_ln117_14;
input  [7:0] sext_ln117_13;
input  [7:0] sext_ln117_12;
input  [7:0] sext_ln117_11;
input  [7:0] sext_ln117_10;
input  [7:0] sext_ln117_9;
input  [7:0] sext_ln117_8;
input  [7:0] sext_ln117_7;
input  [7:0] sext_ln117_6;
input  [7:0] sext_ln117_5;
input  [7:0] sext_ln117_4;
input  [7:0] sext_ln117_3;
input  [7:0] sext_ln117_2;
input  [7:0] sext_ln117;
input  [7:0] sext_ln117_1;
input  [7:0] sext_ln51;
input  [7:0] sext_ln117_23;
input  [7:0] sext_ln117_22;
input  [7:0] sext_ln117_21;
input  [7:0] sext_ln117_20;
input  [7:0] sext_ln117_19;
input  [7:0] sext_ln117_18;
input  [31:0] sext_ln122;
input  [4:0] zext_ln140;
input  [31:0] delta;
input  [0:0] borderType;
input  [13:0] add_ln155;
output  [23:0] m_axis_video_TDATA;
output   m_axis_video_TVALID;

reg ap_idle;
reg s_axis_video_TREADY;
reg m_axis_video_TVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln61_reg_2543;
reg    ap_block_state2_pp0_stage0_iter1;
reg   [0:0] icmp_ln97_reg_2547;
reg   [0:0] icmp_ln97_reg_2547_pp0_iter8_reg;
reg   [0:0] and_ln140_2_reg_2642;
reg   [0:0] and_ln140_2_reg_2642_pp0_iter8_reg;
wire   [0:0] borderType_read_reg_2355;
reg    ap_predicate_op504_write_state10;
reg    ap_block_state10_pp0_stage0_iter9;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln51_fu_792_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    s_axis_video_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    m_axis_video_TDATA_blk_n;
reg   [7:0] new_pixel_reg_601;
reg   [7:0] new_pixel_reg_601_pp0_iter2_reg;
reg    ap_block_pp0_stage0_11001;
reg   [7:0] new_pixel_reg_601_pp0_iter3_reg;
wire    ap_block_pp0_stage0_11001_grp0;
wire    ap_block_pp0_stage0_subdone_grp0;
wire   [0:0] borderType_read_read_fu_306_p2;
wire   [62:0] zext_ln140_cast_fu_627_p1;
reg   [62:0] zext_ln140_cast_reg_2392;
wire  signed [51:0] sext_ln122_cast_fu_631_p1;
reg  signed [51:0] sext_ln122_cast_reg_2397;
wire  signed [15:0] sext_ln117_18_cast_fu_635_p1;
reg  signed [15:0] sext_ln117_18_cast_reg_2402;
wire  signed [15:0] sext_ln117_19_cast_fu_639_p1;
reg  signed [15:0] sext_ln117_19_cast_reg_2407;
wire  signed [15:0] sext_ln117_20_cast_fu_643_p1;
reg  signed [15:0] sext_ln117_20_cast_reg_2412;
wire  signed [15:0] sext_ln117_21_cast_fu_647_p1;
reg  signed [15:0] sext_ln117_21_cast_reg_2417;
wire  signed [15:0] sext_ln117_22_cast_fu_651_p1;
reg  signed [15:0] sext_ln117_22_cast_reg_2422;
wire  signed [15:0] sext_ln117_23_cast_fu_655_p1;
reg  signed [15:0] sext_ln117_23_cast_reg_2427;
wire  signed [15:0] sext_ln51_cast_fu_659_p1;
reg  signed [15:0] sext_ln51_cast_reg_2432;
wire  signed [15:0] sext_ln117_1_cast_fu_663_p1;
reg  signed [15:0] sext_ln117_1_cast_reg_2437;
wire  signed [15:0] sext_ln117_cast_fu_667_p1;
reg  signed [15:0] sext_ln117_cast_reg_2442;
wire  signed [15:0] sext_ln117_2_cast_fu_671_p1;
reg  signed [15:0] sext_ln117_2_cast_reg_2447;
wire  signed [15:0] sext_ln117_3_cast_fu_675_p1;
reg  signed [15:0] sext_ln117_3_cast_reg_2452;
wire  signed [15:0] sext_ln117_4_cast_fu_679_p1;
reg  signed [15:0] sext_ln117_4_cast_reg_2457;
wire  signed [15:0] sext_ln117_5_cast_fu_683_p1;
reg  signed [15:0] sext_ln117_5_cast_reg_2462;
wire  signed [15:0] sext_ln117_6_cast_fu_687_p1;
reg  signed [15:0] sext_ln117_6_cast_reg_2467;
wire  signed [15:0] sext_ln117_7_cast_fu_691_p1;
reg  signed [15:0] sext_ln117_7_cast_reg_2472;
wire  signed [15:0] sext_ln117_8_cast_fu_695_p1;
reg  signed [15:0] sext_ln117_8_cast_reg_2477;
wire  signed [15:0] sext_ln117_9_cast_fu_699_p1;
reg  signed [15:0] sext_ln117_9_cast_reg_2482;
wire  signed [15:0] sext_ln117_10_cast_fu_703_p1;
reg  signed [15:0] sext_ln117_10_cast_reg_2487;
wire  signed [15:0] sext_ln117_11_cast_fu_707_p1;
reg  signed [15:0] sext_ln117_11_cast_reg_2492;
wire  signed [15:0] sext_ln117_12_cast_fu_711_p1;
reg  signed [15:0] sext_ln117_12_cast_reg_2497;
wire  signed [15:0] sext_ln117_13_cast_fu_715_p1;
reg  signed [15:0] sext_ln117_13_cast_reg_2502;
wire  signed [15:0] sext_ln117_14_cast_fu_719_p1;
reg  signed [15:0] sext_ln117_14_cast_reg_2507;
wire  signed [15:0] sext_ln117_15_cast_fu_723_p1;
reg  signed [15:0] sext_ln117_15_cast_reg_2512;
wire  signed [15:0] sext_ln117_16_cast_fu_727_p1;
reg  signed [15:0] sext_ln117_16_cast_reg_2517;
wire  signed [15:0] sext_ln117_17_cast_fu_731_p1;
reg  signed [15:0] sext_ln117_17_cast_reg_2522;
wire   [13:0] zext_ln43_cast_fu_735_p1;
reg   [13:0] zext_ln43_cast_reg_2527;
wire   [13:0] zext_ln122_cast_fu_739_p1;
reg   [13:0] zext_ln122_cast_reg_2535;
wire   [0:0] icmp_ln61_fu_774_p2;
wire   [0:0] icmp_ln97_fu_786_p2;
reg   [0:0] icmp_ln97_reg_2547_pp0_iter1_reg;
reg   [0:0] icmp_ln97_reg_2547_pp0_iter2_reg;
reg   [0:0] icmp_ln97_reg_2547_pp0_iter3_reg;
reg   [0:0] icmp_ln97_reg_2547_pp0_iter4_reg;
reg   [0:0] icmp_ln97_reg_2547_pp0_iter5_reg;
reg   [0:0] icmp_ln97_reg_2547_pp0_iter6_reg;
reg   [0:0] icmp_ln97_reg_2547_pp0_iter7_reg;
reg   [12:0] line_buffer_addr_reg_2555;
reg   [12:0] line_buffer_addr_reg_2555_pp0_iter2_reg;
reg   [12:0] line_buffer_addr_reg_2555_pp0_iter3_reg;
reg   [12:0] line_buffer_1_addr_reg_2560;
reg   [12:0] line_buffer_1_addr_reg_2560_pp0_iter2_reg;
reg   [12:0] line_buffer_2_addr_reg_2565;
wire   [0:0] icmp_ln81_fu_819_p2;
reg   [0:0] icmp_ln81_reg_2575;
reg   [0:0] icmp_ln81_reg_2575_pp0_iter2_reg;
reg   [0:0] icmp_ln81_reg_2575_pp0_iter3_reg;
reg   [7:0] val_79_reg_2579;
reg   [7:0] val_79_reg_2579_pp0_iter3_reg;
reg   [7:0] val_73_reg_2585;
wire   [13:0] zext_ln105_fu_858_p1;
reg   [13:0] zext_ln105_reg_2591;
wire   [0:0] or_ln112_1_fu_891_p2;
reg   [0:0] or_ln112_1_reg_2600;
reg   [0:0] or_ln112_1_reg_2600_pp0_iter4_reg;
wire   [0:0] icmp_ln112_3_fu_897_p2;
reg   [0:0] icmp_ln112_3_reg_2609;
wire   [0:0] or_ln112_8_fu_927_p2;
reg   [0:0] or_ln112_8_reg_2614;
wire   [0:0] icmp_ln112_7_fu_933_p2;
reg   [0:0] icmp_ln112_7_reg_2623;
wire   [0:0] icmp_ln112_8_fu_944_p2;
reg   [0:0] icmp_ln112_8_reg_2628;
wire   [0:0] xor_ln112_9_fu_960_p2;
reg   [0:0] xor_ln112_9_reg_2633;
wire   [0:0] and_ln140_2_fu_1020_p2;
reg   [0:0] and_ln140_2_reg_2642_pp0_iter4_reg;
reg   [0:0] and_ln140_2_reg_2642_pp0_iter5_reg;
reg   [0:0] and_ln140_2_reg_2642_pp0_iter6_reg;
reg   [0:0] and_ln140_2_reg_2642_pp0_iter7_reg;
wire   [0:0] out_paket_user_fu_1032_p2;
reg   [0:0] out_paket_user_reg_2646;
reg   [0:0] out_paket_user_reg_2646_pp0_iter4_reg;
reg   [0:0] out_paket_user_reg_2646_pp0_iter5_reg;
reg   [0:0] out_paket_user_reg_2646_pp0_iter6_reg;
reg   [0:0] out_paket_user_reg_2646_pp0_iter7_reg;
reg   [0:0] out_paket_user_reg_2646_pp0_iter8_reg;
wire   [0:0] or_ln112_fu_1153_p2;
reg   [0:0] or_ln112_reg_2651;
wire   [0:0] or_ln112_3_fu_1183_p2;
reg   [0:0] or_ln112_3_reg_2656;
wire   [0:0] xor_ln112_3_fu_1189_p2;
reg   [0:0] xor_ln112_3_reg_2661;
wire   [0:0] xor_ln112_4_fu_1204_p2;
reg   [0:0] xor_ln112_4_reg_2666;
wire   [0:0] xor_ln112_5_fu_1220_p2;
reg   [0:0] xor_ln112_5_reg_2671;
wire   [7:0] val_65_fu_1248_p3;
reg   [7:0] val_65_reg_2681;
reg   [7:0] val_65_reg_2681_pp0_iter5_reg;
wire   [7:0] val_68_fu_1278_p3;
reg   [7:0] val_68_reg_2691;
wire   [7:0] val_71_fu_1332_p3;
reg   [7:0] val_71_reg_2706;
wire   [7:0] val_72_fu_1346_p3;
reg   [7:0] val_72_reg_2711;
reg   [7:0] val_72_reg_2711_pp0_iter5_reg;
wire   [7:0] val_75_fu_1378_p3;
reg   [7:0] val_75_reg_2721;
reg   [7:0] val_75_reg_2721_pp0_iter5_reg;
wire   [7:0] val_77_fu_1414_p3;
reg   [7:0] val_77_reg_2731;
reg   [7:0] val_77_reg_2731_pp0_iter5_reg;
wire   [7:0] val_78_fu_1428_p3;
reg   [7:0] val_78_reg_2736;
wire   [7:0] val_80_fu_1442_p3;
reg   [7:0] val_80_reg_2741;
reg   [7:0] val_80_reg_2741_pp0_iter5_reg;
wire   [7:0] val_83_fu_1489_p3;
reg   [7:0] val_83_reg_2756;
wire   [7:0] val_84_fu_1502_p3;
reg   [7:0] val_84_reg_2761;
reg   [7:0] val_84_reg_2761_pp0_iter5_reg;
wire   [7:0] val_86_fu_1515_p3;
reg   [7:0] val_86_reg_2766;
wire   [0:0] icmp_ln155_fu_1540_p2;
reg   [0:0] icmp_ln155_reg_2776;
reg   [0:0] icmp_ln155_reg_2776_pp0_iter5_reg;
reg   [0:0] icmp_ln155_reg_2776_pp0_iter6_reg;
reg   [0:0] icmp_ln155_reg_2776_pp0_iter7_reg;
reg   [0:0] icmp_ln155_reg_2776_pp0_iter8_reg;
wire   [7:0] val_58_fu_1651_p3;
reg   [7:0] val_58_reg_2781;
wire   [7:0] val_62_fu_1695_p3;
reg   [7:0] val_62_reg_2796;
wire   [7:0] val_63_fu_1707_p3;
reg   [7:0] val_63_reg_2801;
wire   [17:0] add_ln116_20_fu_1888_p2;
reg   [17:0] add_ln116_20_reg_2911;
wire   [51:0] mul_ln122_fu_623_p2;
reg   [51:0] mul_ln122_reg_2916;
wire   [12:0] line_buffer_3_address0;
wire   [7:0] line_buffer_3_q0;
wire   [7:0] line_buffer_2_q0;
wire   [7:0] line_buffer_1_q0;
wire   [7:0] line_buffer_q0;
reg   [7:0] ap_phi_mux_new_pixel_phi_fu_605_p4;
wire   [7:0] trunc_ln65_fu_806_p1;
reg   [7:0] ap_phi_reg_pp0_iter1_new_pixel_reg_601;
wire   [7:0] ap_phi_reg_pp0_iter0_new_pixel_reg_601;
wire   [13:0] ap_phi_reg_pp0_iter0_add_ln88_pn_reg_614;
reg   [13:0] ap_phi_reg_pp0_iter1_add_ln88_pn_reg_614;
reg   [13:0] ap_phi_reg_pp0_iter2_add_ln88_pn_reg_614;
reg   [13:0] ap_phi_reg_pp0_iter3_add_ln88_pn_reg_614;
reg   [13:0] ap_phi_reg_pp0_iter4_add_ln88_pn_reg_614;
wire   [63:0] zext_ln77_fu_811_p1;
reg   [26:0] i_fu_188;
wire   [26:0] i_3_fu_780_p2;
wire    ap_loop_init;
reg   [26:0] ap_sig_allocacmp_i_1;
reg   [7:0] val_fu_192;
reg   [7:0] val_2_fu_196;
reg   [7:0] val_4_fu_200;
reg   [7:0] val_6_fu_204;
reg   [7:0] val_10_fu_208;
reg   [7:0] val_12_fu_212;
reg   [7:0] val_14_fu_216;
reg   [7:0] val_16_fu_220;
reg   [7:0] val_20_fu_224;
reg   [7:0] val21_fu_228;
reg   [12:0] x_fu_232;
wire   [12:0] x_5_fu_839_p3;
reg   [7:0] val_22_fu_236;
reg   [7:0] val_24_fu_240;
reg   [7:0] val_26_fu_244;
reg   [7:0] val_30_fu_248;
reg   [7:0] val_32_fu_252;
reg   [7:0] val_34_fu_256;
reg   [7:0] val_36_fu_260;
reg   [7:0] val_40_fu_264;
reg   [7:0] val_42_fu_268;
reg   [7:0] val_44_fu_272;
reg   [12:0] img_y_2_fu_276;
wire   [12:0] out_y_1_fu_1063_p3;
reg   [12:0] img_x_2_fu_280;
wire   [12:0] out_x_1_fu_1055_p3;
reg    ap_block_pp0_stage0_01001;
reg    line_buffer_3_ce0_local;
reg    line_buffer_3_we0_local;
reg    line_buffer_2_ce0_local;
reg    line_buffer_2_we0_local;
reg    line_buffer_1_ce0_local;
reg    line_buffer_1_we0_local;
reg    line_buffer_ce0_local;
reg    line_buffer_we0_local;
wire  signed [31:0] mul_ln122_fu_623_p1;
wire   [26:0] zext_ln44_fu_743_p1;
wire   [26:0] zext_ln44_1_fu_747_p1;
wire   [13:0] zext_ln88_fu_824_p1;
wire   [0:0] icmp_ln88_fu_828_p2;
wire   [12:0] x_4_fu_833_p2;
wire   [13:0] zext_ln107_fu_862_p1;
wire   [13:0] img_y_fu_866_p2;
wire   [0:0] icmp_ln112_fu_880_p2;
wire   [0:0] tmp_1_fu_872_p3;
wire   [0:0] xor_ln112_fu_885_p2;
wire   [13:0] img_y_6_fu_902_p2;
wire   [0:0] icmp_ln112_6_fu_916_p2;
wire   [0:0] tmp_4_fu_908_p3;
wire   [0:0] xor_ln112_6_fu_921_p2;
wire   [13:0] img_y_7_fu_938_p2;
wire   [13:0] img_y_8_fu_949_p2;
wire   [0:0] icmp_ln112_9_fu_955_p2;
wire   [11:0] tmp_7_fu_966_p4;
wire   [11:0] tmp_8_fu_987_p4;
wire   [0:0] icmp_ln141_fu_1003_p2;
wire   [0:0] icmp_ln140_2_fu_997_p2;
wire   [0:0] icmp_ln140_1_fu_982_p2;
wire   [0:0] icmp_ln140_fu_976_p2;
wire   [0:0] and_ln140_1_fu_1014_p2;
wire   [0:0] and_ln140_fu_1008_p2;
wire   [12:0] or_ln150_fu_1026_p2;
wire   [0:0] icmp_ln162_fu_1038_p2;
wire   [12:0] out_x_fu_1049_p2;
wire   [12:0] out_y_fu_1043_p2;
wire   [13:0] img_x_fu_1129_p2;
wire   [0:0] icmp_ln112_1_fu_1142_p2;
wire   [0:0] xor_ln112_1_fu_1147_p2;
wire   [0:0] tmp_2_fu_1134_p3;
wire   [13:0] img_x_6_fu_1159_p2;
wire   [0:0] icmp_ln112_2_fu_1172_p2;
wire   [0:0] xor_ln112_2_fu_1177_p2;
wire   [0:0] tmp_3_fu_1164_p3;
wire   [13:0] img_x_7_fu_1194_p2;
wire   [0:0] icmp_ln112_4_fu_1199_p2;
wire   [13:0] img_x_8_fu_1210_p2;
wire   [0:0] icmp_ln112_5_fu_1215_p2;
wire   [0:0] or_ln112_9_fu_1226_p2;
wire   [7:0] val_64_fu_1231_p3;
wire   [0:0] or_ln112_10_fu_1243_p2;
wire   [0:0] or_ln112_11_fu_1256_p2;
wire   [7:0] val_66_fu_1261_p3;
wire   [0:0] or_ln112_12_fu_1273_p2;
wire   [0:0] or_ln112_13_fu_1286_p2;
wire   [7:0] val_69_fu_1291_p3;
wire   [0:0] xor_ln112_7_fu_1303_p2;
wire   [0:0] or_ln112_14_fu_1308_p2;
wire   [7:0] val_70_fu_1314_p3;
wire   [0:0] or_ln112_15_fu_1326_p2;
wire   [0:0] or_ln112_16_fu_1340_p2;
wire   [0:0] or_ln112_17_fu_1354_p2;
wire   [7:0] val_74_fu_1360_p3;
wire   [0:0] or_ln112_18_fu_1372_p2;
wire   [0:0] xor_ln112_8_fu_1385_p2;
wire   [0:0] or_ln112_19_fu_1390_p2;
wire   [7:0] val_76_fu_1396_p3;
wire   [0:0] or_ln112_20_fu_1408_p2;
wire   [0:0] or_ln112_21_fu_1422_p2;
wire   [0:0] or_ln112_22_fu_1436_p2;
wire   [0:0] or_ln112_23_fu_1450_p2;
wire   [7:0] val_81_fu_1456_p3;
wire   [0:0] or_ln112_24_fu_1467_p2;
wire   [7:0] val_82_fu_1472_p3;
wire   [0:0] or_ln112_25_fu_1484_p2;
wire   [0:0] or_ln112_26_fu_1497_p2;
wire   [0:0] or_ln112_27_fu_1510_p2;
wire   [0:0] or_ln112_28_fu_1523_p2;
wire   [7:0] val_87_fu_1528_p3;
wire   [0:0] or_ln112_2_fu_1647_p2;
wire   [0:0] or_ln112_4_fu_1659_p2;
wire   [7:0] val_59_fu_1663_p3;
wire   [0:0] or_ln112_5_fu_1675_p2;
wire   [7:0] val_60_fu_1679_p3;
wire   [0:0] or_ln112_6_fu_1691_p2;
wire   [0:0] or_ln112_7_fu_1703_p2;
wire   [7:0] mul_ln116_1_fu_1780_p0;
wire  signed [7:0] mul_ln116_1_fu_1780_p1;
wire  signed [15:0] mul_ln116_1_fu_1780_p2;
wire   [7:0] mul_ln116_3_fu_1789_p0;
wire  signed [7:0] mul_ln116_3_fu_1789_p1;
wire  signed [15:0] mul_ln116_3_fu_1789_p2;
wire   [7:0] mul_ln116_5_fu_1798_p0;
wire  signed [7:0] mul_ln116_5_fu_1798_p1;
wire  signed [15:0] mul_ln116_5_fu_1798_p2;
wire   [7:0] mul_ln116_11_fu_1807_p0;
wire  signed [7:0] mul_ln116_11_fu_1807_p1;
wire  signed [15:0] mul_ln116_11_fu_1807_p2;
wire   [7:0] mul_ln116_13_fu_1816_p0;
wire  signed [7:0] mul_ln116_13_fu_1816_p1;
wire  signed [15:0] mul_ln116_13_fu_1816_p2;
wire   [7:0] mul_ln116_14_fu_1825_p0;
wire  signed [7:0] mul_ln116_14_fu_1825_p1;
wire  signed [15:0] mul_ln116_14_fu_1825_p2;
wire   [7:0] mul_ln116_16_fu_1834_p0;
wire  signed [7:0] mul_ln116_16_fu_1834_p1;
wire  signed [15:0] mul_ln116_16_fu_1834_p2;
wire   [7:0] mul_ln116_20_fu_1843_p0;
wire  signed [7:0] mul_ln116_20_fu_1843_p1;
wire  signed [15:0] mul_ln116_20_fu_1843_p2;
wire   [7:0] mul_ln116_24_fu_1852_p0;
wire  signed [7:0] mul_ln116_24_fu_1852_p1;
wire  signed [15:0] mul_ln116_24_fu_1852_p2;
wire  signed [16:0] grp_fu_2101_p3;
wire  signed [16:0] grp_fu_2077_p3;
wire  signed [16:0] grp_fu_2085_p3;
wire  signed [16:0] grp_fu_2069_p3;
wire  signed [16:0] grp_fu_2125_p3;
wire  signed [16:0] grp_fu_2109_p3;
wire  signed [16:0] grp_fu_2117_p3;
wire  signed [16:0] grp_fu_2093_p3;
wire  signed [16:0] grp_fu_2133_p3;
wire  signed [17:0] sext_ln116_44_fu_1885_p1;
wire  signed [17:0] sext_ln116_43_fu_1882_p1;
wire  signed [17:0] grp_fu_2141_p3;
wire  signed [17:0] grp_fu_2165_p3;
wire  signed [18:0] sext_ln116_28_fu_1897_p1;
wire  signed [18:0] sext_ln116_26_fu_1894_p1;
wire   [18:0] add_ln116_4_fu_1900_p2;
wire  signed [17:0] grp_fu_2181_p3;
wire  signed [17:0] grp_fu_2149_p3;
wire  signed [18:0] sext_ln116_33_fu_1913_p1;
wire  signed [18:0] sext_ln116_31_fu_1910_p1;
wire   [18:0] add_ln116_9_fu_1916_p2;
wire  signed [19:0] sext_ln116_34_fu_1922_p1;
wire  signed [19:0] sext_ln116_29_fu_1906_p1;
wire   [19:0] add_ln116_10_fu_1926_p2;
wire  signed [17:0] grp_fu_2157_p3;
wire  signed [17:0] grp_fu_2189_p3;
wire  signed [18:0] sext_ln116_39_fu_1939_p1;
wire  signed [18:0] sext_ln116_37_fu_1936_p1;
wire   [18:0] add_ln116_15_fu_1942_p2;
wire  signed [17:0] grp_fu_2173_p3;
wire  signed [18:0] sext_ln116_45_fu_1955_p1;
wire  signed [18:0] sext_ln116_42_fu_1952_p1;
wire   [18:0] add_ln116_21_fu_1958_p2;
wire  signed [19:0] sext_ln116_46_fu_1964_p1;
wire  signed [19:0] sext_ln116_40_fu_1948_p1;
wire   [19:0] add_ln116_22_fu_1968_p2;
wire  signed [20:0] sext_ln116_47_fu_1974_p1;
wire  signed [20:0] sext_ln116_35_fu_1932_p1;
wire  signed [20:0] sum_fu_1978_p2;
wire  signed [62:0] sext_ln122_2_fu_1989_p1;
wire   [62:0] ashr_ln122_fu_1992_p2;
wire   [31:0] sum_1_fu_1997_p1;
wire   [31:0] sum_2_fu_2001_p2;
wire   [0:0] tmp_5_fu_2010_p3;
wire   [30:0] trunc_ln98_fu_2006_p1;
wire   [30:0] sum_3_fu_2018_p3;
wire   [22:0] tmp_6_fu_2026_p4;
wire   [0:0] icmp_ln129_fu_2036_p2;
wire   [7:0] trunc_ln148_fu_2042_p1;
wire   [7:0] out_paket_data_fu_2046_p3;
wire   [16:0] tmp_fu_2054_p5;
wire   [7:0] grp_fu_2069_p0;
wire  signed [7:0] grp_fu_2069_p1;
wire   [7:0] grp_fu_2077_p0;
wire  signed [7:0] grp_fu_2077_p1;
wire   [7:0] grp_fu_2085_p0;
wire  signed [7:0] grp_fu_2085_p1;
wire   [7:0] grp_fu_2093_p0;
wire  signed [7:0] grp_fu_2093_p1;
wire   [7:0] grp_fu_2101_p0;
wire  signed [7:0] grp_fu_2101_p1;
wire   [7:0] grp_fu_2109_p0;
wire  signed [7:0] grp_fu_2109_p1;
wire   [7:0] grp_fu_2117_p0;
wire  signed [7:0] grp_fu_2117_p1;
wire   [7:0] grp_fu_2125_p0;
wire  signed [7:0] grp_fu_2125_p1;
wire   [7:0] grp_fu_2133_p0;
wire  signed [7:0] grp_fu_2133_p1;
wire   [7:0] grp_fu_2141_p0;
wire  signed [7:0] grp_fu_2141_p1;
wire   [7:0] grp_fu_2149_p0;
wire  signed [7:0] grp_fu_2149_p1;
wire   [7:0] grp_fu_2157_p0;
wire  signed [7:0] grp_fu_2157_p1;
wire   [7:0] grp_fu_2165_p0;
wire  signed [7:0] grp_fu_2165_p1;
wire   [7:0] grp_fu_2173_p0;
wire  signed [7:0] grp_fu_2173_p1;
wire   [7:0] grp_fu_2181_p0;
wire  signed [7:0] grp_fu_2181_p1;
wire   [7:0] grp_fu_2189_p0;
wire  signed [7:0] grp_fu_2189_p1;
reg    grp_fu_2069_ce;
reg    grp_fu_2077_ce;
reg    grp_fu_2085_ce;
reg    grp_fu_2093_ce;
reg    grp_fu_2101_ce;
reg    grp_fu_2109_ce;
reg    grp_fu_2117_ce;
reg    grp_fu_2125_ce;
reg    grp_fu_2133_ce;
reg    grp_fu_2141_ce;
reg    grp_fu_2149_ce;
reg    grp_fu_2157_ce;
reg    grp_fu_2165_ce;
reg    grp_fu_2173_ce;
reg    grp_fu_2181_ce;
reg    grp_fu_2189_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [15:0] grp_fu_2069_p00;
wire   [15:0] grp_fu_2077_p00;
wire   [15:0] grp_fu_2085_p00;
wire   [15:0] grp_fu_2093_p00;
wire   [15:0] grp_fu_2101_p00;
wire   [15:0] grp_fu_2109_p00;
wire   [15:0] grp_fu_2117_p00;
wire   [15:0] grp_fu_2125_p00;
wire   [15:0] grp_fu_2133_p00;
wire   [15:0] grp_fu_2141_p00;
wire   [15:0] grp_fu_2149_p00;
wire   [15:0] grp_fu_2157_p00;
wire   [15:0] grp_fu_2165_p00;
wire   [15:0] grp_fu_2173_p00;
wire   [15:0] grp_fu_2181_p00;
wire   [15:0] grp_fu_2189_p00;
wire   [15:0] mul_ln116_11_fu_1807_p00;
wire   [15:0] mul_ln116_13_fu_1816_p00;
wire   [15:0] mul_ln116_14_fu_1825_p00;
wire   [15:0] mul_ln116_16_fu_1834_p00;
wire   [15:0] mul_ln116_1_fu_1780_p00;
wire   [15:0] mul_ln116_20_fu_1843_p00;
wire   [15:0] mul_ln116_24_fu_1852_p00;
wire   [15:0] mul_ln116_3_fu_1789_p00;
wire   [15:0] mul_ln116_5_fu_1798_p00;
reg    ap_condition_810;
reg    ap_condition_829;
reg    ap_condition_804;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 i_fu_188 = 27'd0;
#0 val_fu_192 = 8'd0;
#0 val_2_fu_196 = 8'd0;
#0 val_4_fu_200 = 8'd0;
#0 val_6_fu_204 = 8'd0;
#0 val_10_fu_208 = 8'd0;
#0 val_12_fu_212 = 8'd0;
#0 val_14_fu_216 = 8'd0;
#0 val_16_fu_220 = 8'd0;
#0 val_20_fu_224 = 8'd0;
#0 val21_fu_228 = 8'd0;
#0 x_fu_232 = 13'd0;
#0 val_22_fu_236 = 8'd0;
#0 val_24_fu_240 = 8'd0;
#0 val_26_fu_244 = 8'd0;
#0 val_30_fu_248 = 8'd0;
#0 val_32_fu_252 = 8'd0;
#0 val_34_fu_256 = 8'd0;
#0 val_36_fu_260 = 8'd0;
#0 val_40_fu_264 = 8'd0;
#0 val_42_fu_268 = 8'd0;
#0 val_44_fu_272 = 8'd0;
#0 img_y_2_fu_276 = 13'd0;
#0 img_x_2_fu_280 = 13'd0;
#0 ap_done_reg = 1'b0;
end

hls_filter_2d_hls_filter_2d_Pipeline_VITIS_LOOP_51_1_line_buffer_3_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 7680 ),
    .AddressWidth( 13 ))
line_buffer_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(line_buffer_3_address0),
    .ce0(line_buffer_3_ce0_local),
    .we0(line_buffer_3_we0_local),
    .d0(ap_phi_mux_new_pixel_phi_fu_605_p4),
    .q0(line_buffer_3_q0)
);

hls_filter_2d_hls_filter_2d_Pipeline_VITIS_LOOP_51_1_line_buffer_3_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 7680 ),
    .AddressWidth( 13 ))
line_buffer_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(line_buffer_2_addr_reg_2565),
    .ce0(line_buffer_2_ce0_local),
    .we0(line_buffer_2_we0_local),
    .d0(line_buffer_3_q0),
    .q0(line_buffer_2_q0)
);

hls_filter_2d_hls_filter_2d_Pipeline_VITIS_LOOP_51_1_line_buffer_3_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 7680 ),
    .AddressWidth( 13 ))
line_buffer_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(line_buffer_1_addr_reg_2560_pp0_iter2_reg),
    .ce0(line_buffer_1_ce0_local),
    .we0(line_buffer_1_we0_local),
    .d0(line_buffer_2_q0),
    .q0(line_buffer_1_q0)
);

hls_filter_2d_hls_filter_2d_Pipeline_VITIS_LOOP_51_1_line_buffer_3_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 7680 ),
    .AddressWidth( 13 ))
line_buffer_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(line_buffer_addr_reg_2555_pp0_iter3_reg),
    .ce0(line_buffer_ce0_local),
    .we0(line_buffer_we0_local),
    .d0(line_buffer_1_q0),
    .q0(line_buffer_q0)
);

hls_filter_2d_mul_21s_32s_52_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 21 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 52 ))
mul_21s_32s_52_1_1_U1(
    .din0(sum_fu_1978_p2),
    .din1(mul_ln122_fu_623_p1),
    .dout(mul_ln122_fu_623_p2)
);

hls_filter_2d_mul_8ns_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8s_16_1_1_U2(
    .din0(mul_ln116_1_fu_1780_p0),
    .din1(mul_ln116_1_fu_1780_p1),
    .dout(mul_ln116_1_fu_1780_p2)
);

hls_filter_2d_mul_8ns_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8s_16_1_1_U3(
    .din0(mul_ln116_3_fu_1789_p0),
    .din1(mul_ln116_3_fu_1789_p1),
    .dout(mul_ln116_3_fu_1789_p2)
);

hls_filter_2d_mul_8ns_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8s_16_1_1_U4(
    .din0(mul_ln116_5_fu_1798_p0),
    .din1(mul_ln116_5_fu_1798_p1),
    .dout(mul_ln116_5_fu_1798_p2)
);

hls_filter_2d_mul_8ns_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8s_16_1_1_U5(
    .din0(mul_ln116_11_fu_1807_p0),
    .din1(mul_ln116_11_fu_1807_p1),
    .dout(mul_ln116_11_fu_1807_p2)
);

hls_filter_2d_mul_8ns_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8s_16_1_1_U6(
    .din0(mul_ln116_13_fu_1816_p0),
    .din1(mul_ln116_13_fu_1816_p1),
    .dout(mul_ln116_13_fu_1816_p2)
);

hls_filter_2d_mul_8ns_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8s_16_1_1_U7(
    .din0(mul_ln116_14_fu_1825_p0),
    .din1(mul_ln116_14_fu_1825_p1),
    .dout(mul_ln116_14_fu_1825_p2)
);

hls_filter_2d_mul_8ns_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8s_16_1_1_U8(
    .din0(mul_ln116_16_fu_1834_p0),
    .din1(mul_ln116_16_fu_1834_p1),
    .dout(mul_ln116_16_fu_1834_p2)
);

hls_filter_2d_mul_8ns_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8s_16_1_1_U9(
    .din0(mul_ln116_20_fu_1843_p0),
    .din1(mul_ln116_20_fu_1843_p1),
    .dout(mul_ln116_20_fu_1843_p2)
);

hls_filter_2d_mul_8ns_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8s_16_1_1_U10(
    .din0(mul_ln116_24_fu_1852_p0),
    .din1(mul_ln116_24_fu_1852_p1),
    .dout(mul_ln116_24_fu_1852_p2)
);

hls_filter_2d_mac_muladd_8ns_8s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8s_16s_17_4_1_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2069_p0),
    .din1(grp_fu_2069_p1),
    .din2(mul_ln116_1_fu_1780_p2),
    .ce(grp_fu_2069_ce),
    .dout(grp_fu_2069_p3)
);

hls_filter_2d_mac_muladd_8ns_8s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8s_16s_17_4_1_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2077_p0),
    .din1(grp_fu_2077_p1),
    .din2(mul_ln116_20_fu_1843_p2),
    .ce(grp_fu_2077_ce),
    .dout(grp_fu_2077_p3)
);

hls_filter_2d_mac_muladd_8ns_8s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8s_16s_17_4_1_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2085_p0),
    .din1(grp_fu_2085_p1),
    .din2(mul_ln116_24_fu_1852_p2),
    .ce(grp_fu_2085_ce),
    .dout(grp_fu_2085_p3)
);

hls_filter_2d_mac_muladd_8ns_8s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8s_16s_17_4_1_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2093_p0),
    .din1(grp_fu_2093_p1),
    .din2(mul_ln116_13_fu_1816_p2),
    .ce(grp_fu_2093_ce),
    .dout(grp_fu_2093_p3)
);

hls_filter_2d_mac_muladd_8ns_8s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8s_16s_17_4_1_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2101_p0),
    .din1(grp_fu_2101_p1),
    .din2(mul_ln116_5_fu_1798_p2),
    .ce(grp_fu_2101_ce),
    .dout(grp_fu_2101_p3)
);

hls_filter_2d_mac_muladd_8ns_8s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8s_16s_17_4_1_U16(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2109_p0),
    .din1(grp_fu_2109_p1),
    .din2(mul_ln116_11_fu_1807_p2),
    .ce(grp_fu_2109_ce),
    .dout(grp_fu_2109_p3)
);

hls_filter_2d_mac_muladd_8ns_8s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8s_16s_17_4_1_U17(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2117_p0),
    .din1(grp_fu_2117_p1),
    .din2(mul_ln116_16_fu_1834_p2),
    .ce(grp_fu_2117_ce),
    .dout(grp_fu_2117_p3)
);

hls_filter_2d_mac_muladd_8ns_8s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8s_16s_17_4_1_U18(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2125_p0),
    .din1(grp_fu_2125_p1),
    .din2(mul_ln116_14_fu_1825_p2),
    .ce(grp_fu_2125_ce),
    .dout(grp_fu_2125_p3)
);

hls_filter_2d_mac_muladd_8ns_8s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8s_16s_17_4_1_U19(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2133_p0),
    .din1(grp_fu_2133_p1),
    .din2(mul_ln116_3_fu_1789_p2),
    .ce(grp_fu_2133_ce),
    .dout(grp_fu_2133_p3)
);

hls_filter_2d_mac_muladd_8ns_8s_17s_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 18 ))
mac_muladd_8ns_8s_17s_18_4_1_U20(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2141_p0),
    .din1(grp_fu_2141_p1),
    .din2(grp_fu_2101_p3),
    .ce(grp_fu_2141_ce),
    .dout(grp_fu_2141_p3)
);

hls_filter_2d_mac_muladd_8ns_8s_17s_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 18 ))
mac_muladd_8ns_8s_17s_18_4_1_U21(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2149_p0),
    .din1(grp_fu_2149_p1),
    .din2(grp_fu_2069_p3),
    .ce(grp_fu_2149_ce),
    .dout(grp_fu_2149_p3)
);

hls_filter_2d_mac_muladd_8ns_8s_17s_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 18 ))
mac_muladd_8ns_8s_17s_18_4_1_U22(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2157_p0),
    .din1(grp_fu_2157_p1),
    .din2(grp_fu_2125_p3),
    .ce(grp_fu_2157_ce),
    .dout(grp_fu_2157_p3)
);

hls_filter_2d_mac_muladd_8ns_8s_17s_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 18 ))
mac_muladd_8ns_8s_17s_18_4_1_U23(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2165_p0),
    .din1(grp_fu_2165_p1),
    .din2(grp_fu_2077_p3),
    .ce(grp_fu_2165_ce),
    .dout(grp_fu_2165_p3)
);

hls_filter_2d_mac_muladd_8ns_8s_17s_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 18 ))
mac_muladd_8ns_8s_17s_18_4_1_U24(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2173_p0),
    .din1(grp_fu_2173_p1),
    .din2(grp_fu_2117_p3),
    .ce(grp_fu_2173_ce),
    .dout(grp_fu_2173_p3)
);

hls_filter_2d_mac_muladd_8ns_8s_17s_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 18 ))
mac_muladd_8ns_8s_17s_18_4_1_U25(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2181_p0),
    .din1(grp_fu_2181_p1),
    .din2(grp_fu_2085_p3),
    .ce(grp_fu_2181_ce),
    .dout(grp_fu_2181_p3)
);

hls_filter_2d_mac_muladd_8ns_8s_17s_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 18 ))
mac_muladd_8ns_8s_17s_18_4_1_U26(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2189_p0),
    .din1(grp_fu_2189_p1),
    .din2(grp_fu_2109_p3),
    .ce(grp_fu_2189_ce),
    .dout(grp_fu_2189_p3)
);

hls_filter_2d_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter9_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter8_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter9_reg <= 1'b0;
    end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_810)) begin
        if (((icmp_ln97_fu_786_p2 == 1'd0) & (borderType_read_read_fu_306_p2 == 1'd1))) begin
            ap_phi_reg_pp0_iter1_add_ln88_pn_reg_614 <= add_ln88;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_add_ln88_pn_reg_614 <= ap_phi_reg_pp0_iter0_add_ln88_pn_reg_614;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_810)) begin
        if ((icmp_ln61_fu_774_p2 == 1'd0)) begin
            ap_phi_reg_pp0_iter1_new_pixel_reg_601 <= 8'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_new_pixel_reg_601 <= ap_phi_reg_pp0_iter0_new_pixel_reg_601;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if ((1'b1 == ap_condition_829)) begin
            ap_phi_reg_pp0_iter4_add_ln88_pn_reg_614 <= add_ln155;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_add_ln88_pn_reg_614 <= ap_phi_reg_pp0_iter3_add_ln88_pn_reg_614;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
            i_fu_188 <= i_3_fu_780_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_188 <= 27'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            img_x_2_fu_280 <= 13'd0;
        end else if (((icmp_ln97_reg_2547_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            img_x_2_fu_280 <= out_x_1_fu_1055_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            img_y_2_fu_276 <= 13'd0;
        end else if (((icmp_ln97_reg_2547_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            img_y_2_fu_276 <= out_y_1_fu_1063_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_804)) begin
        if ((icmp_ln61_reg_2543 == 1'd1)) begin
            new_pixel_reg_601 <= trunc_ln65_fu_806_p1;
        end else if ((1'b1 == 1'b1)) begin
            new_pixel_reg_601 <= ap_phi_reg_pp0_iter1_new_pixel_reg_601;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            x_fu_232 <= 13'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            x_fu_232 <= x_5_fu_839_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln116_20_reg_2911 <= add_ln116_20_fu_1888_p2;
        and_ln140_2_reg_2642 <= and_ln140_2_fu_1020_p2;
        and_ln140_2_reg_2642_pp0_iter4_reg <= and_ln140_2_reg_2642;
        and_ln140_2_reg_2642_pp0_iter5_reg <= and_ln140_2_reg_2642_pp0_iter4_reg;
        and_ln140_2_reg_2642_pp0_iter6_reg <= and_ln140_2_reg_2642_pp0_iter5_reg;
        and_ln140_2_reg_2642_pp0_iter7_reg <= and_ln140_2_reg_2642_pp0_iter6_reg;
        and_ln140_2_reg_2642_pp0_iter8_reg <= and_ln140_2_reg_2642_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        icmp_ln112_3_reg_2609 <= icmp_ln112_3_fu_897_p2;
        icmp_ln112_7_reg_2623 <= icmp_ln112_7_fu_933_p2;
        icmp_ln112_8_reg_2628 <= icmp_ln112_8_fu_944_p2;
        icmp_ln155_reg_2776 <= icmp_ln155_fu_1540_p2;
        icmp_ln155_reg_2776_pp0_iter5_reg <= icmp_ln155_reg_2776;
        icmp_ln155_reg_2776_pp0_iter6_reg <= icmp_ln155_reg_2776_pp0_iter5_reg;
        icmp_ln155_reg_2776_pp0_iter7_reg <= icmp_ln155_reg_2776_pp0_iter6_reg;
        icmp_ln155_reg_2776_pp0_iter8_reg <= icmp_ln155_reg_2776_pp0_iter7_reg;
        icmp_ln81_reg_2575_pp0_iter2_reg <= icmp_ln81_reg_2575;
        icmp_ln81_reg_2575_pp0_iter3_reg <= icmp_ln81_reg_2575_pp0_iter2_reg;
        icmp_ln97_reg_2547_pp0_iter2_reg <= icmp_ln97_reg_2547_pp0_iter1_reg;
        icmp_ln97_reg_2547_pp0_iter3_reg <= icmp_ln97_reg_2547_pp0_iter2_reg;
        icmp_ln97_reg_2547_pp0_iter4_reg <= icmp_ln97_reg_2547_pp0_iter3_reg;
        icmp_ln97_reg_2547_pp0_iter5_reg <= icmp_ln97_reg_2547_pp0_iter4_reg;
        icmp_ln97_reg_2547_pp0_iter6_reg <= icmp_ln97_reg_2547_pp0_iter5_reg;
        icmp_ln97_reg_2547_pp0_iter7_reg <= icmp_ln97_reg_2547_pp0_iter6_reg;
        icmp_ln97_reg_2547_pp0_iter8_reg <= icmp_ln97_reg_2547_pp0_iter7_reg;
        line_buffer_1_addr_reg_2560_pp0_iter2_reg <= line_buffer_1_addr_reg_2560;
        line_buffer_addr_reg_2555_pp0_iter2_reg <= line_buffer_addr_reg_2555;
        line_buffer_addr_reg_2555_pp0_iter3_reg <= line_buffer_addr_reg_2555_pp0_iter2_reg;
        mul_ln122_reg_2916 <= mul_ln122_fu_623_p2;
        new_pixel_reg_601_pp0_iter2_reg <= new_pixel_reg_601;
        new_pixel_reg_601_pp0_iter3_reg <= new_pixel_reg_601_pp0_iter2_reg;
        or_ln112_1_reg_2600 <= or_ln112_1_fu_891_p2;
        or_ln112_1_reg_2600_pp0_iter4_reg <= or_ln112_1_reg_2600;
        or_ln112_3_reg_2656 <= or_ln112_3_fu_1183_p2;
        or_ln112_8_reg_2614 <= or_ln112_8_fu_927_p2;
        or_ln112_reg_2651 <= or_ln112_fu_1153_p2;
        out_paket_user_reg_2646 <= out_paket_user_fu_1032_p2;
        out_paket_user_reg_2646_pp0_iter4_reg <= out_paket_user_reg_2646;
        out_paket_user_reg_2646_pp0_iter5_reg <= out_paket_user_reg_2646_pp0_iter4_reg;
        out_paket_user_reg_2646_pp0_iter6_reg <= out_paket_user_reg_2646_pp0_iter5_reg;
        out_paket_user_reg_2646_pp0_iter7_reg <= out_paket_user_reg_2646_pp0_iter6_reg;
        out_paket_user_reg_2646_pp0_iter8_reg <= out_paket_user_reg_2646_pp0_iter7_reg;
        val_58_reg_2781 <= val_58_fu_1651_p3;
        val_62_reg_2796 <= val_62_fu_1695_p3;
        val_63_reg_2801 <= val_63_fu_1707_p3;
        val_65_reg_2681 <= val_65_fu_1248_p3;
        val_65_reg_2681_pp0_iter5_reg <= val_65_reg_2681;
        val_68_reg_2691 <= val_68_fu_1278_p3;
        val_71_reg_2706 <= val_71_fu_1332_p3;
        val_72_reg_2711 <= val_72_fu_1346_p3;
        val_72_reg_2711_pp0_iter5_reg <= val_72_reg_2711;
        val_75_reg_2721 <= val_75_fu_1378_p3;
        val_75_reg_2721_pp0_iter5_reg <= val_75_reg_2721;
        val_77_reg_2731 <= val_77_fu_1414_p3;
        val_77_reg_2731_pp0_iter5_reg <= val_77_reg_2731;
        val_78_reg_2736 <= val_78_fu_1428_p3;
        val_79_reg_2579_pp0_iter3_reg <= val_79_reg_2579;
        val_80_reg_2741 <= val_80_fu_1442_p3;
        val_80_reg_2741_pp0_iter5_reg <= val_80_reg_2741;
        val_83_reg_2756 <= val_83_fu_1489_p3;
        val_84_reg_2761 <= val_84_fu_1502_p3;
        val_84_reg_2761_pp0_iter5_reg <= val_84_reg_2761;
        val_86_reg_2766 <= val_86_fu_1515_p3;
        xor_ln112_3_reg_2661 <= xor_ln112_3_fu_1189_p2;
        xor_ln112_4_reg_2666 <= xor_ln112_4_fu_1204_p2;
        xor_ln112_5_reg_2671 <= xor_ln112_5_fu_1220_p2;
        xor_ln112_9_reg_2633 <= xor_ln112_9_fu_960_p2;
        zext_ln105_reg_2591[12 : 0] <= zext_ln105_fu_858_p1[12 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln61_reg_2543 <= icmp_ln61_fu_774_p2;
        icmp_ln81_reg_2575 <= icmp_ln81_fu_819_p2;
        icmp_ln97_reg_2547 <= icmp_ln97_fu_786_p2;
        icmp_ln97_reg_2547_pp0_iter1_reg <= icmp_ln97_reg_2547;
        line_buffer_1_addr_reg_2560 <= zext_ln77_fu_811_p1;
        line_buffer_2_addr_reg_2565 <= zext_ln77_fu_811_p1;
        line_buffer_addr_reg_2555 <= zext_ln77_fu_811_p1;
        sext_ln117_10_cast_reg_2487 <= sext_ln117_10_cast_fu_703_p1;
        sext_ln117_11_cast_reg_2492 <= sext_ln117_11_cast_fu_707_p1;
        sext_ln117_12_cast_reg_2497 <= sext_ln117_12_cast_fu_711_p1;
        sext_ln117_13_cast_reg_2502 <= sext_ln117_13_cast_fu_715_p1;
        sext_ln117_14_cast_reg_2507 <= sext_ln117_14_cast_fu_719_p1;
        sext_ln117_15_cast_reg_2512 <= sext_ln117_15_cast_fu_723_p1;
        sext_ln117_16_cast_reg_2517 <= sext_ln117_16_cast_fu_727_p1;
        sext_ln117_17_cast_reg_2522 <= sext_ln117_17_cast_fu_731_p1;
        sext_ln117_18_cast_reg_2402 <= sext_ln117_18_cast_fu_635_p1;
        sext_ln117_19_cast_reg_2407 <= sext_ln117_19_cast_fu_639_p1;
        sext_ln117_1_cast_reg_2437 <= sext_ln117_1_cast_fu_663_p1;
        sext_ln117_20_cast_reg_2412 <= sext_ln117_20_cast_fu_643_p1;
        sext_ln117_21_cast_reg_2417 <= sext_ln117_21_cast_fu_647_p1;
        sext_ln117_22_cast_reg_2422 <= sext_ln117_22_cast_fu_651_p1;
        sext_ln117_23_cast_reg_2427 <= sext_ln117_23_cast_fu_655_p1;
        sext_ln117_2_cast_reg_2447 <= sext_ln117_2_cast_fu_671_p1;
        sext_ln117_3_cast_reg_2452 <= sext_ln117_3_cast_fu_675_p1;
        sext_ln117_4_cast_reg_2457 <= sext_ln117_4_cast_fu_679_p1;
        sext_ln117_5_cast_reg_2462 <= sext_ln117_5_cast_fu_683_p1;
        sext_ln117_6_cast_reg_2467 <= sext_ln117_6_cast_fu_687_p1;
        sext_ln117_7_cast_reg_2472 <= sext_ln117_7_cast_fu_691_p1;
        sext_ln117_8_cast_reg_2477 <= sext_ln117_8_cast_fu_695_p1;
        sext_ln117_9_cast_reg_2482 <= sext_ln117_9_cast_fu_699_p1;
        sext_ln117_cast_reg_2442 <= sext_ln117_cast_fu_667_p1;
        sext_ln122_cast_reg_2397 <= sext_ln122_cast_fu_631_p1;
        sext_ln51_cast_reg_2432 <= sext_ln51_cast_fu_659_p1;
        zext_ln122_cast_reg_2535[12 : 0] <= zext_ln122_cast_fu_739_p1[12 : 0];
        zext_ln140_cast_reg_2392[4 : 0] <= zext_ln140_cast_fu_627_p1[4 : 0];
        zext_ln43_cast_reg_2527[12 : 0] <= zext_ln43_cast_fu_735_p1[12 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter2_add_ln88_pn_reg_614 <= ap_phi_reg_pp0_iter1_add_ln88_pn_reg_614;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_reg_pp0_iter3_add_ln88_pn_reg_614 <= ap_phi_reg_pp0_iter2_add_ln88_pn_reg_614;
        val_79_reg_2579 <= line_buffer_3_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        val21_fu_228 <= val_44_fu_272;
        val_20_fu_224 <= val_42_fu_268;
        val_42_fu_268 <= line_buffer_q0;
        val_44_fu_272 <= val_20_fu_224;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        val_10_fu_208 <= val_32_fu_252;
        val_12_fu_212 <= val_34_fu_256;
        val_14_fu_216 <= val_36_fu_260;
        val_16_fu_220 <= val_40_fu_264;
        val_22_fu_236 <= new_pixel_reg_601_pp0_iter3_reg;
        val_24_fu_240 <= val_fu_192;
        val_26_fu_244 <= val_79_reg_2579_pp0_iter3_reg;
        val_2_fu_196 <= val_24_fu_240;
        val_30_fu_248 <= val_4_fu_200;
        val_32_fu_252 <= val_73_reg_2585;
        val_34_fu_256 <= val_10_fu_208;
        val_36_fu_260 <= line_buffer_1_q0;
        val_40_fu_264 <= val_14_fu_216;
        val_4_fu_200 <= val_26_fu_244;
        val_6_fu_204 <= val_30_fu_248;
        val_fu_192 <= val_22_fu_236;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        val_73_reg_2585 <= line_buffer_2_q0;
    end
end

always @ (*) begin
    if (((icmp_ln51_fu_792_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter9_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln61_reg_2543 == 1'd1)) begin
        ap_phi_mux_new_pixel_phi_fu_605_p4 = trunc_ln65_fu_806_p1;
    end else begin
        ap_phi_mux_new_pixel_phi_fu_605_p4 = ap_phi_reg_pp0_iter1_new_pixel_reg_601;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_1 = 27'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_188;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_2069_ce = 1'b1;
    end else begin
        grp_fu_2069_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_2077_ce = 1'b1;
    end else begin
        grp_fu_2077_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_2085_ce = 1'b1;
    end else begin
        grp_fu_2085_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_2093_ce = 1'b1;
    end else begin
        grp_fu_2093_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_2101_ce = 1'b1;
    end else begin
        grp_fu_2101_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_2109_ce = 1'b1;
    end else begin
        grp_fu_2109_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_2117_ce = 1'b1;
    end else begin
        grp_fu_2117_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_2125_ce = 1'b1;
    end else begin
        grp_fu_2125_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_2133_ce = 1'b1;
    end else begin
        grp_fu_2133_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_2141_ce = 1'b1;
    end else begin
        grp_fu_2141_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_2149_ce = 1'b1;
    end else begin
        grp_fu_2149_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_2157_ce = 1'b1;
    end else begin
        grp_fu_2157_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_2165_ce = 1'b1;
    end else begin
        grp_fu_2165_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_2173_ce = 1'b1;
    end else begin
        grp_fu_2173_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_2181_ce = 1'b1;
    end else begin
        grp_fu_2181_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_2189_ce = 1'b1;
    end else begin
        grp_fu_2189_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        line_buffer_1_ce0_local = 1'b1;
    end else begin
        line_buffer_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln81_reg_2575_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        line_buffer_1_we0_local = 1'b1;
    end else begin
        line_buffer_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        line_buffer_2_ce0_local = 1'b1;
    end else begin
        line_buffer_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln81_reg_2575 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        line_buffer_2_we0_local = 1'b1;
    end else begin
        line_buffer_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_3_ce0_local = 1'b1;
    end else begin
        line_buffer_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln81_fu_819_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_3_we0_local = 1'b1;
    end else begin
        line_buffer_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        line_buffer_ce0_local = 1'b1;
    end else begin
        line_buffer_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln81_reg_2575_pp0_iter3_reg == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        line_buffer_we0_local = 1'b1;
    end else begin
        line_buffer_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op504_write_state10 == 1'b1) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        m_axis_video_TDATA_blk_n = m_axis_video_TREADY;
    end else begin
        m_axis_video_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op504_write_state10 == 1'b1) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        m_axis_video_TVALID = 1'b1;
    end else begin
        m_axis_video_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln61_reg_2543 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_axis_video_TDATA_blk_n = s_axis_video_TVALID;
    end else begin
        s_axis_video_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln61_reg_2543 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_axis_video_TREADY = 1'b1;
    end else begin
        s_axis_video_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln116_10_fu_1926_p2 = ($signed(sext_ln116_34_fu_1922_p1) + $signed(sext_ln116_29_fu_1906_p1));

assign add_ln116_15_fu_1942_p2 = ($signed(sext_ln116_39_fu_1939_p1) + $signed(sext_ln116_37_fu_1936_p1));

assign add_ln116_20_fu_1888_p2 = ($signed(sext_ln116_44_fu_1885_p1) + $signed(sext_ln116_43_fu_1882_p1));

assign add_ln116_21_fu_1958_p2 = ($signed(sext_ln116_45_fu_1955_p1) + $signed(sext_ln116_42_fu_1952_p1));

assign add_ln116_22_fu_1968_p2 = ($signed(sext_ln116_46_fu_1964_p1) + $signed(sext_ln116_40_fu_1948_p1));

assign add_ln116_4_fu_1900_p2 = ($signed(sext_ln116_28_fu_1897_p1) + $signed(sext_ln116_26_fu_1894_p1));

assign add_ln116_9_fu_1916_p2 = ($signed(sext_ln116_33_fu_1913_p1) + $signed(sext_ln116_31_fu_1910_p1));

assign and_ln140_1_fu_1014_p2 = (icmp_ln140_fu_976_p2 & icmp_ln140_1_fu_982_p2);

assign and_ln140_2_fu_1020_p2 = (and_ln140_fu_1008_p2 & and_ln140_1_fu_1014_p2);

assign and_ln140_fu_1008_p2 = (icmp_ln141_fu_1003_p2 & icmp_ln140_2_fu_997_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage0_iter9)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage0_iter9)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage0_iter9)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state10_pp0_stage0_iter9 = ((ap_predicate_op504_write_state10 == 1'b1) & (m_axis_video_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((icmp_ln61_reg_2543 == 1'd1) & (s_axis_video_TVALID == 1'b0));
end

always @ (*) begin
    ap_condition_804 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_810 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_829 = ((borderType_read_reg_2355 == 1'd0) & (1'd1 == and_ln140_2_fu_1020_p2) & (icmp_ln97_reg_2547_pp0_iter2_reg == 1'd0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_add_ln88_pn_reg_614 = 'bx;

assign ap_phi_reg_pp0_iter0_new_pixel_reg_601 = 'bx;

always @ (*) begin
    ap_predicate_op504_write_state10 = (((borderType == 1'd1) & (icmp_ln97_reg_2547_pp0_iter8_reg == 1'd0)) | ((icmp_ln97_reg_2547_pp0_iter8_reg == 1'd0) & (1'd1 == and_ln140_2_reg_2642_pp0_iter8_reg)));
end

assign ap_ready = ap_ready_sig;

assign ashr_ln122_fu_1992_p2 = $signed(sext_ln122_2_fu_1989_p1) >>> zext_ln140_cast_reg_2392;

assign borderType_read_read_fu_306_p2 = borderType;

assign borderType_read_reg_2355 = borderType;

assign grp_fu_2069_p0 = grp_fu_2069_p00;

assign grp_fu_2069_p00 = val_76_fu_1396_p3;

assign grp_fu_2069_p1 = sext_ln117_15_cast_reg_2512;

assign grp_fu_2077_p0 = grp_fu_2077_p00;

assign grp_fu_2077_p00 = val_74_fu_1360_p3;

assign grp_fu_2077_p1 = sext_ln117_13_cast_reg_2502;

assign grp_fu_2085_p0 = grp_fu_2085_p00;

assign grp_fu_2085_p00 = val_70_fu_1314_p3;

assign grp_fu_2085_p1 = sext_ln117_10_cast_reg_2487;

assign grp_fu_2093_p0 = grp_fu_2093_p00;

assign grp_fu_2093_p00 = val_69_fu_1291_p3;

assign grp_fu_2093_p1 = sext_ln117_9_cast_reg_2482;

assign grp_fu_2101_p0 = grp_fu_2101_p00;

assign grp_fu_2101_p00 = val_66_fu_1261_p3;

assign grp_fu_2101_p1 = sext_ln117_7_cast_reg_2472;

assign grp_fu_2109_p0 = grp_fu_2109_p00;

assign grp_fu_2109_p00 = val_64_fu_1231_p3;

assign grp_fu_2109_p1 = sext_ln117_5_cast_reg_2462;

assign grp_fu_2117_p0 = grp_fu_2117_p00;

assign grp_fu_2117_p00 = val_87_fu_1528_p3;

assign grp_fu_2117_p1 = sext_ln51_cast_reg_2432;

assign grp_fu_2125_p0 = grp_fu_2125_p00;

assign grp_fu_2125_p00 = val_82_fu_1472_p3;

assign grp_fu_2125_p1 = sext_ln117_20_cast_reg_2412;

assign grp_fu_2133_p0 = grp_fu_2133_p00;

assign grp_fu_2133_p00 = val_81_fu_1456_p3;

assign grp_fu_2133_p1 = sext_ln117_19_cast_reg_2407;

assign grp_fu_2141_p0 = grp_fu_2141_p00;

assign grp_fu_2141_p00 = val_78_reg_2736;

assign grp_fu_2141_p1 = sext_ln117_17_cast_reg_2522;

assign grp_fu_2149_p0 = grp_fu_2149_p00;

assign grp_fu_2149_p00 = val_71_reg_2706;

assign grp_fu_2149_p1 = sext_ln117_11_cast_reg_2492;

assign grp_fu_2157_p0 = grp_fu_2157_p00;

assign grp_fu_2157_p00 = val_68_reg_2691;

assign grp_fu_2157_p1 = sext_ln117_8_cast_reg_2477;

assign grp_fu_2165_p0 = grp_fu_2165_p00;

assign grp_fu_2165_p00 = val_60_fu_1679_p3;

assign grp_fu_2165_p1 = sext_ln117_2_cast_reg_2447;

assign grp_fu_2173_p0 = grp_fu_2173_p00;

assign grp_fu_2173_p00 = val_59_fu_1663_p3;

assign grp_fu_2173_p1 = sext_ln117_1_cast_reg_2437;

assign grp_fu_2181_p0 = grp_fu_2181_p00;

assign grp_fu_2181_p00 = val_86_reg_2766;

assign grp_fu_2181_p1 = sext_ln117_23_cast_reg_2427;

assign grp_fu_2189_p0 = grp_fu_2189_p00;

assign grp_fu_2189_p00 = val_83_reg_2756;

assign grp_fu_2189_p1 = sext_ln117_21_cast_reg_2417;

assign i_3_fu_780_p2 = (ap_sig_allocacmp_i_1 + 27'd1);

assign icmp_ln112_1_fu_1142_p2 = (($signed(img_x_fu_1129_p2) < $signed(zext_ln43_cast_reg_2527)) ? 1'b1 : 1'b0);

assign icmp_ln112_2_fu_1172_p2 = (($signed(img_x_6_fu_1159_p2) < $signed(zext_ln43_cast_reg_2527)) ? 1'b1 : 1'b0);

assign icmp_ln112_3_fu_897_p2 = ((img_x_2_fu_280 < width) ? 1'b1 : 1'b0);

assign icmp_ln112_4_fu_1199_p2 = ((img_x_7_fu_1194_p2 < zext_ln43_cast_reg_2527) ? 1'b1 : 1'b0);

assign icmp_ln112_5_fu_1215_p2 = ((img_x_8_fu_1210_p2 < zext_ln43_cast_reg_2527) ? 1'b1 : 1'b0);

assign icmp_ln112_6_fu_916_p2 = (($signed(img_y_6_fu_902_p2) < $signed(zext_ln122_cast_reg_2535)) ? 1'b1 : 1'b0);

assign icmp_ln112_7_fu_933_p2 = ((img_y_2_fu_276 < height) ? 1'b1 : 1'b0);

assign icmp_ln112_8_fu_944_p2 = ((img_y_7_fu_938_p2 < zext_ln122_cast_reg_2535) ? 1'b1 : 1'b0);

assign icmp_ln112_9_fu_955_p2 = ((img_y_8_fu_949_p2 < zext_ln122_cast_reg_2535) ? 1'b1 : 1'b0);

assign icmp_ln112_fu_880_p2 = (($signed(img_y_fu_866_p2) < $signed(zext_ln122_cast_reg_2535)) ? 1'b1 : 1'b0);

assign icmp_ln129_fu_2036_p2 = ((tmp_6_fu_2026_p4 != 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln140_1_fu_982_p2 = (($signed(add_ln140) > $signed(zext_ln105_fu_858_p1)) ? 1'b1 : 1'b0);

assign icmp_ln140_2_fu_997_p2 = ((tmp_8_fu_987_p4 != 12'd0) ? 1'b1 : 1'b0);

assign icmp_ln140_fu_976_p2 = ((tmp_7_fu_966_p4 != 12'd0) ? 1'b1 : 1'b0);

assign icmp_ln141_fu_1003_p2 = (($signed(add_ln141) > $signed(zext_ln107_fu_862_p1)) ? 1'b1 : 1'b0);

assign icmp_ln155_fu_1540_p2 = ((ap_phi_reg_pp0_iter4_add_ln88_pn_reg_614 == zext_ln105_reg_2591) ? 1'b1 : 1'b0);

assign icmp_ln162_fu_1038_p2 = ((add_ln88 == zext_ln105_fu_858_p1) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_792_p2 = ((i_3_fu_780_p2 == total_cycles) ? 1'b1 : 1'b0);

assign icmp_ln61_fu_774_p2 = ((ap_sig_allocacmp_i_1 < zext_ln44_fu_743_p1) ? 1'b1 : 1'b0);

assign icmp_ln81_fu_819_p2 = ((x_fu_232 < width) ? 1'b1 : 1'b0);

assign icmp_ln88_fu_828_p2 = ((add_ln88 == zext_ln88_fu_824_p1) ? 1'b1 : 1'b0);

assign icmp_ln97_fu_786_p2 = ((ap_sig_allocacmp_i_1 < zext_ln44_1_fu_747_p1) ? 1'b1 : 1'b0);

assign img_x_6_fu_1159_p2 = ($signed(zext_ln105_reg_2591) + $signed(14'd16383));

assign img_x_7_fu_1194_p2 = (zext_ln105_reg_2591 + 14'd1);

assign img_x_8_fu_1210_p2 = (zext_ln105_reg_2591 + 14'd2);

assign img_x_fu_1129_p2 = ($signed(zext_ln105_reg_2591) + $signed(14'd16382));

assign img_y_6_fu_902_p2 = ($signed(zext_ln107_fu_862_p1) + $signed(14'd16383));

assign img_y_7_fu_938_p2 = (zext_ln107_fu_862_p1 + 14'd1);

assign img_y_8_fu_949_p2 = (zext_ln107_fu_862_p1 + 14'd2);

assign img_y_fu_866_p2 = ($signed(zext_ln107_fu_862_p1) + $signed(14'd16382));

assign line_buffer_3_address0 = zext_ln77_fu_811_p1;

assign m_axis_video_TDATA = tmp_fu_2054_p5;

assign mul_ln116_11_fu_1807_p0 = mul_ln116_11_fu_1807_p00;

assign mul_ln116_11_fu_1807_p00 = val_65_reg_2681_pp0_iter5_reg;

assign mul_ln116_11_fu_1807_p1 = sext_ln117_6_cast_reg_2467;

assign mul_ln116_13_fu_1816_p0 = mul_ln116_13_fu_1816_p00;

assign mul_ln116_13_fu_1816_p00 = val_63_reg_2801;

assign mul_ln116_13_fu_1816_p1 = sext_ln117_4_cast_reg_2457;

assign mul_ln116_14_fu_1825_p0 = mul_ln116_14_fu_1825_p00;

assign mul_ln116_14_fu_1825_p00 = val_62_reg_2796;

assign mul_ln116_14_fu_1825_p1 = sext_ln117_3_cast_reg_2452;

assign mul_ln116_16_fu_1834_p0 = mul_ln116_16_fu_1834_p00;

assign mul_ln116_16_fu_1834_p00 = val_58_reg_2781;

assign mul_ln116_16_fu_1834_p1 = sext_ln117_cast_reg_2442;

assign mul_ln116_1_fu_1780_p0 = mul_ln116_1_fu_1780_p00;

assign mul_ln116_1_fu_1780_p00 = val_77_reg_2731_pp0_iter5_reg;

assign mul_ln116_1_fu_1780_p1 = sext_ln117_16_cast_reg_2517;

assign mul_ln116_20_fu_1843_p0 = mul_ln116_20_fu_1843_p00;

assign mul_ln116_20_fu_1843_p00 = val_84_reg_2761_pp0_iter5_reg;

assign mul_ln116_20_fu_1843_p1 = sext_ln117_22_cast_reg_2422;

assign mul_ln116_24_fu_1852_p0 = mul_ln116_24_fu_1852_p00;

assign mul_ln116_24_fu_1852_p00 = val_80_reg_2741_pp0_iter5_reg;

assign mul_ln116_24_fu_1852_p1 = sext_ln117_18_cast_reg_2402;

assign mul_ln116_3_fu_1789_p0 = mul_ln116_3_fu_1789_p00;

assign mul_ln116_3_fu_1789_p00 = val_75_reg_2721_pp0_iter5_reg;

assign mul_ln116_3_fu_1789_p1 = sext_ln117_14_cast_reg_2507;

assign mul_ln116_5_fu_1798_p0 = mul_ln116_5_fu_1798_p00;

assign mul_ln116_5_fu_1798_p00 = val_72_reg_2711_pp0_iter5_reg;

assign mul_ln116_5_fu_1798_p1 = sext_ln117_12_cast_reg_2497;

assign mul_ln122_fu_623_p1 = sext_ln122_cast_reg_2397;

assign or_ln112_10_fu_1243_p2 = (or_ln112_8_reg_2614 | or_ln112_3_fu_1183_p2);

assign or_ln112_11_fu_1256_p2 = (xor_ln112_3_fu_1189_p2 | or_ln112_8_reg_2614);

assign or_ln112_12_fu_1273_p2 = (xor_ln112_4_fu_1204_p2 | or_ln112_8_reg_2614);

assign or_ln112_13_fu_1286_p2 = (xor_ln112_5_fu_1220_p2 | or_ln112_8_reg_2614);

assign or_ln112_14_fu_1308_p2 = (xor_ln112_7_fu_1303_p2 | or_ln112_fu_1153_p2);

assign or_ln112_15_fu_1326_p2 = (xor_ln112_7_fu_1303_p2 | or_ln112_3_fu_1183_p2);

assign or_ln112_16_fu_1340_p2 = (xor_ln112_7_fu_1303_p2 | xor_ln112_3_fu_1189_p2);

assign or_ln112_17_fu_1354_p2 = (xor_ln112_7_fu_1303_p2 | xor_ln112_4_fu_1204_p2);

assign or_ln112_18_fu_1372_p2 = (xor_ln112_7_fu_1303_p2 | xor_ln112_5_fu_1220_p2);

assign or_ln112_19_fu_1390_p2 = (xor_ln112_8_fu_1385_p2 | or_ln112_fu_1153_p2);

assign or_ln112_1_fu_891_p2 = (xor_ln112_fu_885_p2 | tmp_1_fu_872_p3);

assign or_ln112_20_fu_1408_p2 = (xor_ln112_8_fu_1385_p2 | or_ln112_3_fu_1183_p2);

assign or_ln112_21_fu_1422_p2 = (xor_ln112_8_fu_1385_p2 | xor_ln112_3_fu_1189_p2);

assign or_ln112_22_fu_1436_p2 = (xor_ln112_8_fu_1385_p2 | xor_ln112_4_fu_1204_p2);

assign or_ln112_23_fu_1450_p2 = (xor_ln112_8_fu_1385_p2 | xor_ln112_5_fu_1220_p2);

assign or_ln112_24_fu_1467_p2 = (xor_ln112_9_reg_2633 | or_ln112_fu_1153_p2);

assign or_ln112_25_fu_1484_p2 = (xor_ln112_9_reg_2633 | or_ln112_3_fu_1183_p2);

assign or_ln112_26_fu_1497_p2 = (xor_ln112_9_reg_2633 | xor_ln112_3_fu_1189_p2);

assign or_ln112_27_fu_1510_p2 = (xor_ln112_9_reg_2633 | xor_ln112_4_fu_1204_p2);

assign or_ln112_28_fu_1523_p2 = (xor_ln112_9_reg_2633 | xor_ln112_5_fu_1220_p2);

assign or_ln112_2_fu_1647_p2 = (or_ln112_reg_2651 | or_ln112_1_reg_2600_pp0_iter4_reg);

assign or_ln112_3_fu_1183_p2 = (xor_ln112_2_fu_1177_p2 | tmp_3_fu_1164_p3);

assign or_ln112_4_fu_1659_p2 = (or_ln112_3_reg_2656 | or_ln112_1_reg_2600_pp0_iter4_reg);

assign or_ln112_5_fu_1675_p2 = (xor_ln112_3_reg_2661 | or_ln112_1_reg_2600_pp0_iter4_reg);

assign or_ln112_6_fu_1691_p2 = (xor_ln112_4_reg_2666 | or_ln112_1_reg_2600_pp0_iter4_reg);

assign or_ln112_7_fu_1703_p2 = (xor_ln112_5_reg_2671 | or_ln112_1_reg_2600_pp0_iter4_reg);

assign or_ln112_8_fu_927_p2 = (xor_ln112_6_fu_921_p2 | tmp_4_fu_908_p3);

assign or_ln112_9_fu_1226_p2 = (or_ln112_fu_1153_p2 | or_ln112_8_reg_2614);

assign or_ln112_fu_1153_p2 = (xor_ln112_1_fu_1147_p2 | tmp_2_fu_1134_p3);

assign or_ln150_fu_1026_p2 = (img_y_2_fu_276 | img_x_2_fu_280);

assign out_paket_data_fu_2046_p3 = ((icmp_ln129_fu_2036_p2[0:0] == 1'b1) ? 8'd255 : trunc_ln148_fu_2042_p1);

assign out_paket_user_fu_1032_p2 = ((or_ln150_fu_1026_p2 == 13'd0) ? 1'b1 : 1'b0);

assign out_x_1_fu_1055_p3 = ((icmp_ln162_fu_1038_p2[0:0] == 1'b1) ? 13'd0 : out_x_fu_1049_p2);

assign out_x_fu_1049_p2 = (img_x_2_fu_280 + 13'd1);

assign out_y_1_fu_1063_p3 = ((icmp_ln162_fu_1038_p2[0:0] == 1'b1) ? out_y_fu_1043_p2 : img_y_2_fu_276);

assign out_y_fu_1043_p2 = (img_y_2_fu_276 + 13'd1);

assign sext_ln116_26_fu_1894_p1 = grp_fu_2141_p3;

assign sext_ln116_28_fu_1897_p1 = grp_fu_2165_p3;

assign sext_ln116_29_fu_1906_p1 = $signed(add_ln116_4_fu_1900_p2);

assign sext_ln116_31_fu_1910_p1 = grp_fu_2181_p3;

assign sext_ln116_33_fu_1913_p1 = grp_fu_2149_p3;

assign sext_ln116_34_fu_1922_p1 = $signed(add_ln116_9_fu_1916_p2);

assign sext_ln116_35_fu_1932_p1 = $signed(add_ln116_10_fu_1926_p2);

assign sext_ln116_37_fu_1936_p1 = grp_fu_2157_p3;

assign sext_ln116_39_fu_1939_p1 = grp_fu_2189_p3;

assign sext_ln116_40_fu_1948_p1 = $signed(add_ln116_15_fu_1942_p2);

assign sext_ln116_42_fu_1952_p1 = grp_fu_2173_p3;

assign sext_ln116_43_fu_1882_p1 = grp_fu_2093_p3;

assign sext_ln116_44_fu_1885_p1 = grp_fu_2133_p3;

assign sext_ln116_45_fu_1955_p1 = $signed(add_ln116_20_reg_2911);

assign sext_ln116_46_fu_1964_p1 = $signed(add_ln116_21_fu_1958_p2);

assign sext_ln116_47_fu_1974_p1 = $signed(add_ln116_22_fu_1968_p2);

assign sext_ln117_10_cast_fu_703_p1 = $signed(sext_ln117_10);

assign sext_ln117_11_cast_fu_707_p1 = $signed(sext_ln117_11);

assign sext_ln117_12_cast_fu_711_p1 = $signed(sext_ln117_12);

assign sext_ln117_13_cast_fu_715_p1 = $signed(sext_ln117_13);

assign sext_ln117_14_cast_fu_719_p1 = $signed(sext_ln117_14);

assign sext_ln117_15_cast_fu_723_p1 = $signed(sext_ln117_15);

assign sext_ln117_16_cast_fu_727_p1 = $signed(sext_ln117_16);

assign sext_ln117_17_cast_fu_731_p1 = $signed(sext_ln117_17);

assign sext_ln117_18_cast_fu_635_p1 = $signed(sext_ln117_18);

assign sext_ln117_19_cast_fu_639_p1 = $signed(sext_ln117_19);

assign sext_ln117_1_cast_fu_663_p1 = $signed(sext_ln117_1);

assign sext_ln117_20_cast_fu_643_p1 = $signed(sext_ln117_20);

assign sext_ln117_21_cast_fu_647_p1 = $signed(sext_ln117_21);

assign sext_ln117_22_cast_fu_651_p1 = $signed(sext_ln117_22);

assign sext_ln117_23_cast_fu_655_p1 = $signed(sext_ln117_23);

assign sext_ln117_2_cast_fu_671_p1 = $signed(sext_ln117_2);

assign sext_ln117_3_cast_fu_675_p1 = $signed(sext_ln117_3);

assign sext_ln117_4_cast_fu_679_p1 = $signed(sext_ln117_4);

assign sext_ln117_5_cast_fu_683_p1 = $signed(sext_ln117_5);

assign sext_ln117_6_cast_fu_687_p1 = $signed(sext_ln117_6);

assign sext_ln117_7_cast_fu_691_p1 = $signed(sext_ln117_7);

assign sext_ln117_8_cast_fu_695_p1 = $signed(sext_ln117_8);

assign sext_ln117_9_cast_fu_699_p1 = $signed(sext_ln117_9);

assign sext_ln117_cast_fu_667_p1 = $signed(sext_ln117);

assign sext_ln122_2_fu_1989_p1 = $signed(mul_ln122_reg_2916);

assign sext_ln122_cast_fu_631_p1 = $signed(sext_ln122);

assign sext_ln51_cast_fu_659_p1 = $signed(sext_ln51);

assign sum_1_fu_1997_p1 = ashr_ln122_fu_1992_p2[31:0];

assign sum_2_fu_2001_p2 = (sum_1_fu_1997_p1 + delta);

assign sum_3_fu_2018_p3 = ((tmp_5_fu_2010_p3[0:0] == 1'b1) ? 31'd0 : trunc_ln98_fu_2006_p1);

assign sum_fu_1978_p2 = ($signed(sext_ln116_47_fu_1974_p1) + $signed(sext_ln116_35_fu_1932_p1));

assign tmp_1_fu_872_p3 = img_y_fu_866_p2[32'd13];

assign tmp_2_fu_1134_p3 = img_x_fu_1129_p2[32'd13];

assign tmp_3_fu_1164_p3 = img_x_6_fu_1159_p2[32'd13];

assign tmp_4_fu_908_p3 = img_y_6_fu_902_p2[32'd13];

assign tmp_5_fu_2010_p3 = sum_2_fu_2001_p2[32'd31];

assign tmp_6_fu_2026_p4 = {{sum_3_fu_2018_p3[30:8]}};

assign tmp_7_fu_966_p4 = {{img_x_2_fu_280[12:1]}};

assign tmp_8_fu_987_p4 = {{img_y_2_fu_276[12:1]}};

assign tmp_fu_2054_p5 = {{{{icmp_ln155_reg_2776_pp0_iter8_reg}, {7'd0}}, {out_paket_user_reg_2646_pp0_iter8_reg}}, {out_paket_data_fu_2046_p3}};

assign trunc_ln148_fu_2042_p1 = sum_3_fu_2018_p3[7:0];

assign trunc_ln65_fu_806_p1 = s_axis_video_TDATA[7:0];

assign trunc_ln98_fu_2006_p1 = sum_2_fu_2001_p2[30:0];

assign val_58_fu_1651_p3 = ((or_ln112_2_fu_1647_p2[0:0] == 1'b1) ? 8'd0 : val21_fu_228);

assign val_59_fu_1663_p3 = ((or_ln112_4_fu_1659_p2[0:0] == 1'b1) ? 8'd0 : val_44_fu_272);

assign val_60_fu_1679_p3 = ((or_ln112_5_fu_1675_p2[0:0] == 1'b1) ? 8'd0 : val_20_fu_224);

assign val_62_fu_1695_p3 = ((or_ln112_6_fu_1691_p2[0:0] == 1'b1) ? 8'd0 : val_42_fu_268);

assign val_63_fu_1707_p3 = ((or_ln112_7_fu_1703_p2[0:0] == 1'b1) ? 8'd0 : line_buffer_q0);

assign val_64_fu_1231_p3 = ((or_ln112_9_fu_1226_p2[0:0] == 1'b1) ? 8'd0 : val_16_fu_220);

assign val_65_fu_1248_p3 = ((or_ln112_10_fu_1243_p2[0:0] == 1'b1) ? 8'd0 : val_40_fu_264);

assign val_66_fu_1261_p3 = ((or_ln112_11_fu_1256_p2[0:0] == 1'b1) ? 8'd0 : val_14_fu_216);

assign val_68_fu_1278_p3 = ((or_ln112_12_fu_1273_p2[0:0] == 1'b1) ? 8'd0 : val_36_fu_260);

assign val_69_fu_1291_p3 = ((or_ln112_13_fu_1286_p2[0:0] == 1'b1) ? 8'd0 : line_buffer_1_q0);

assign val_70_fu_1314_p3 = ((or_ln112_14_fu_1308_p2[0:0] == 1'b1) ? 8'd0 : val_12_fu_212);

assign val_71_fu_1332_p3 = ((or_ln112_15_fu_1326_p2[0:0] == 1'b1) ? 8'd0 : val_34_fu_256);

assign val_72_fu_1346_p3 = ((or_ln112_16_fu_1340_p2[0:0] == 1'b1) ? 8'd0 : val_10_fu_208);

assign val_74_fu_1360_p3 = ((or_ln112_17_fu_1354_p2[0:0] == 1'b1) ? 8'd0 : val_32_fu_252);

assign val_75_fu_1378_p3 = ((or_ln112_18_fu_1372_p2[0:0] == 1'b1) ? 8'd0 : val_73_reg_2585);

assign val_76_fu_1396_p3 = ((or_ln112_19_fu_1390_p2[0:0] == 1'b1) ? 8'd0 : val_6_fu_204);

assign val_77_fu_1414_p3 = ((or_ln112_20_fu_1408_p2[0:0] == 1'b1) ? 8'd0 : val_30_fu_248);

assign val_78_fu_1428_p3 = ((or_ln112_21_fu_1422_p2[0:0] == 1'b1) ? 8'd0 : val_4_fu_200);

assign val_80_fu_1442_p3 = ((or_ln112_22_fu_1436_p2[0:0] == 1'b1) ? 8'd0 : val_26_fu_244);

assign val_81_fu_1456_p3 = ((or_ln112_23_fu_1450_p2[0:0] == 1'b1) ? 8'd0 : val_79_reg_2579_pp0_iter3_reg);

assign val_82_fu_1472_p3 = ((or_ln112_24_fu_1467_p2[0:0] == 1'b1) ? 8'd0 : val_2_fu_196);

assign val_83_fu_1489_p3 = ((or_ln112_25_fu_1484_p2[0:0] == 1'b1) ? 8'd0 : val_24_fu_240);

assign val_84_fu_1502_p3 = ((or_ln112_26_fu_1497_p2[0:0] == 1'b1) ? 8'd0 : val_fu_192);

assign val_86_fu_1515_p3 = ((or_ln112_27_fu_1510_p2[0:0] == 1'b1) ? 8'd0 : val_22_fu_236);

assign val_87_fu_1528_p3 = ((or_ln112_28_fu_1523_p2[0:0] == 1'b1) ? 8'd0 : new_pixel_reg_601_pp0_iter3_reg);

assign x_4_fu_833_p2 = (x_fu_232 + 13'd1);

assign x_5_fu_839_p3 = ((icmp_ln88_fu_828_p2[0:0] == 1'b1) ? 13'd0 : x_4_fu_833_p2);

assign xor_ln112_1_fu_1147_p2 = (icmp_ln112_1_fu_1142_p2 ^ 1'd1);

assign xor_ln112_2_fu_1177_p2 = (icmp_ln112_2_fu_1172_p2 ^ 1'd1);

assign xor_ln112_3_fu_1189_p2 = (icmp_ln112_3_reg_2609 ^ 1'd1);

assign xor_ln112_4_fu_1204_p2 = (icmp_ln112_4_fu_1199_p2 ^ 1'd1);

assign xor_ln112_5_fu_1220_p2 = (icmp_ln112_5_fu_1215_p2 ^ 1'd1);

assign xor_ln112_6_fu_921_p2 = (icmp_ln112_6_fu_916_p2 ^ 1'd1);

assign xor_ln112_7_fu_1303_p2 = (icmp_ln112_7_reg_2623 ^ 1'd1);

assign xor_ln112_8_fu_1385_p2 = (icmp_ln112_8_reg_2628 ^ 1'd1);

assign xor_ln112_9_fu_960_p2 = (icmp_ln112_9_fu_955_p2 ^ 1'd1);

assign xor_ln112_fu_885_p2 = (icmp_ln112_fu_880_p2 ^ 1'd1);

assign zext_ln105_fu_858_p1 = img_x_2_fu_280;

assign zext_ln107_fu_862_p1 = img_y_2_fu_276;

assign zext_ln122_cast_fu_739_p1 = zext_ln122;

assign zext_ln140_cast_fu_627_p1 = zext_ln140;

assign zext_ln43_cast_fu_735_p1 = zext_ln43;

assign zext_ln44_1_fu_747_p1 = flush_cycles;

assign zext_ln44_fu_743_p1 = total_pixels;

assign zext_ln77_fu_811_p1 = x_fu_232;

assign zext_ln88_fu_824_p1 = x_fu_232;

always @ (posedge ap_clk) begin
    zext_ln140_cast_reg_2392[62:5] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln43_cast_reg_2527[13] <= 1'b0;
    zext_ln122_cast_reg_2535[13] <= 1'b0;
    zext_ln105_reg_2591[13] <= 1'b0;
end

endmodule //hls_filter_2d_hls_filter_2d_Pipeline_VITIS_LOOP_51_1
