# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/display_port/display_port.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==display_port || ORIG_REF_NAME==display_port} -quiet] -quiet

# IP: bd/display_port/ip/display_port_zynq_ultra_ps_e_0_0/display_port_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==display_port_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==display_port_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/display_port/ip/display_port_clk_wiz_0/display_port_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==display_port_clk_wiz_0 || ORIG_REF_NAME==display_port_clk_wiz_0} -quiet] -quiet

# IP: bd/display_port/ip/display_port_v_tpg_0_0/display_port_v_tpg_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==display_port_v_tpg_0_0 || ORIG_REF_NAME==display_port_v_tpg_0_0} -quiet] -quiet

# IP: bd/display_port/ip/display_port_v_tc_0_0/display_port_v_tc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==display_port_v_tc_0_0 || ORIG_REF_NAME==display_port_v_tc_0_0} -quiet] -quiet

# IP: bd/display_port/ip/display_port_v_axi4s_vid_out_0_0/display_port_v_axi4s_vid_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==display_port_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==display_port_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/display_port/ip/display_port_axi_smc_0/display_port_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==display_port_axi_smc_0 || ORIG_REF_NAME==display_port_axi_smc_0} -quiet] -quiet

# IP: bd/display_port/ip/display_port_rst_clk_wiz_100M_0/display_port_rst_clk_wiz_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==display_port_rst_clk_wiz_100M_0 || ORIG_REF_NAME==display_port_rst_clk_wiz_100M_0} -quiet] -quiet

# IP: bd/display_port/ip/display_port_rst_clk_wiz_300M_0/display_port_rst_clk_wiz_300M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==display_port_rst_clk_wiz_300M_0 || ORIG_REF_NAME==display_port_rst_clk_wiz_300M_0} -quiet] -quiet

# IP: bd/display_port/ip/display_port_xlconcat_0_0/display_port_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==display_port_xlconcat_0_0 || ORIG_REF_NAME==display_port_xlconcat_0_0} -quiet] -quiet

# XDC: d:/Repos/_DP/DP/Vivado/DisplayPortTest/DisplayPortTest.gen/sources_1/bd/display_port/display_port_ooc.xdc
